### ISSUE TITLE
[modules] Move the build from `Maven` to `Gradle`

### ISSUE THREAD

**Issue by paplorinc** [vavr-io/vavr#1277]
`Maven` is configuration based, isn't really meant for non-standard project structures.
Having one really complicates things as the `conventions over configurations` breaks down to `configurations`.
It's also extremely verbose and forced in non-trivial cases.

E.g. mixing `Java` and `Scala` in `Gradle` is as simple as

``` Groovy
apply plugin: 'scala'
```

I don't know all the requirements this build should provide, let's investigate the pros and cons.

**Comment by danieldietrich** [comment]
We need to publish the jars to Maven central, see http://central.sonatype.org/pages/gradle.html

Additionally we have

- a self-written code generator written in Scala that is executed before Java compile. With Maven we use the scala maven plugin but we are able to execute only scripts. With a Gradle build maybe it is possible to remove the code duplications of the Scala code generators in each Maven module.

Some minor things:

- we check interface changes between github tags with a maven plugin
- we check for version updates of dependencies and Maven plugins
- ...

**Comment by paplorinc** [comment]
The code generator could simply be run before the compile (should integrate nicely with Idea).
In that case generated code shouldn't even be committed (probably solving https://github.com/javaslang/javaslang/issues/1265 also)

**Comment by danieldietrich** [comment]
We need to commit them to see changes on code reviews (one line in the generator might change thousands of lines in code).

I decided to commit them once because. Users should be able to browse the actual code online.

**Comment by Conorrr** [comment]
Are you open to public contributions for migrating to Gradle?

**Comment by danieldietrich** [comment]
@Conorrr yes, I would really appreciate it!

Maybe it should be done in smaller steps:

1. Early open a PR for discussion
2. Make a multi module Gradle project and focus on the Java build
3. Change the .travis.yml for CI builds accordingly
4. Add the existing Scala generator if possible
5. Make it releasable. Currently we use OSS Sonatype. I don't know if there is a better alternative?

**Comment by tmtron** [comment]
> 5.   Make it releasable. Currently we use OSS Sonatype. I don't know if there is a better alternative?

You should take a look at Bintray: I think it's easier than OSS Sonatype. The artifacts are published on JCenter and [synced to MavenCentral](https://github.com/bintray/gradle-bintray-plugin#maven-central-sync)

Here's a gradle-plugin to work with Bintray: [gradle-bintray-plugin](https://github.com/bintray/gradle-bintray-plugin#readme)

**Comment by danieldietrich** [comment]
Done in master (for one module). Others will _have to_ follow now :)
