### ISSUE TITLE
Increase code coverage to include all methods and most branches

### ISSUE THREAD

**Issue by paplorinc** [vavr-io/vavr#1279]
Based on [codecov](https://codecov.io/github/javaslang/javaslang?view=all#sort=missing&dir=desc) there seems to be lots of missing tests for important methods e.g.:
- [`TreeMap`'s and `AbstractMultimap`'s `toJavaMap`](https://codecov.io/github/javaslang/javaslang/javaslang/src/main/java/javaslang/collection/AbstractMultimap.java?ref=7bacb55a33ae53cdd0685a40a56542c52daeeeb5#l-440)
- [Lots of `Case`es in `API`](https://codecov.io/github/javaslang/javaslang/javaslang/src-gen/main/java/javaslang/API.java?ref=a7ec39d38014fa4bbf6565a316ad5f67ea551d8f)
- [a few important branches in `RedBlackTree`](https://codecov.io/github/javaslang/javaslang/javaslang/src/main/java/javaslang/collection/RedBlackTree.java?ref=a7ec39d38014fa4bbf6565a316ad5f67ea551d8f#l-752)
- [`Lazy`.`peek`](https://codecov.io/github/javaslang/javaslang/javaslang/src/main/java/javaslang/Lazy.java?ref=a7ec39d38014fa4bbf6565a316ad5f67ea551d8f#l-186)
- [Most of `$.java`](https://codecov.io/github/javaslang/javaslang/javaslang/src/main/java/javaslang/%24.java?ref=a7ec39d38014fa4bbf6565a316ad5f67ea551d8f)

Many should definitely be covered with some basic tests -- but let's not forget that line coverage is not the same as feature coverage.
Just because a line is covered, many features might still need to be tested.

**Comment by danieldietrich** [comment]
Yep.

**Comment by danieldietrich** [comment]
Ongoing task, will move it to 2.2.0

**Comment by danieldietrich** [comment]
This is an acceptance criteria, not an issue. The current coverage of Vavr 1.0 is 100%. We will try to keep it that way.
