### ISSUE TITLE
Add Seq.shuffle()

### ISSUE THREAD

**Issue by eduardmanas** [vavr-io/vavr#1318]
I suggest to add a method that randomly permutes the elements in a sequence, similar to `Collections.shuffle()`.

These are the methods that should be added:
- `Seq.shuffle()`
- `Seq.shuffle(Random random)`

At the moment, these are the "not so nice" steps we need to do to randomize a sequence:

```
    java.util.List<Integer> integers = list.toJavaList();
    Collections.shuffle(integers);
    return List.ofAll(integers);
```

By adding a `shuffle()` method to the `Seq` interface, we would be able to do things like `seq.permutations().shuffle()` or `List.range(5, 10).shuffle()`.

**Comment by danieldietrich** [comment]
@io7m an implementation requires the following:

1. Add method `shuffle()` to `Seq` and all subtypes of `Seq`. The method has the return type of the declaring class.

```java
interface Seq<T> {
    /**
     * <Some meaningful javadoc>
     */
    Seq<T> shuffle();
}

interface LinearSeq<T> extends Seq<T> {
    @Override
    LinearSeq<T> shuffle();
}

// ... and so on
```

The implementing classes delegate to `javaslang.collection.Collections`:

```java
final class Collections {
    static <T, S extends Seq<T>> S shuffle(S source, Function<? super Iterable<T>, S> ofAll) {
        if (source.length() <= 1) {
            return source();
        } else {
            final java.util.List<T> list = list.toJavaList();
            Collections.shuffle(list);
            return ofAll.apply(list);
        }
    }
}

interface List<T> extends LinearSeq<T> {
    @Override
    default List<T> shuffle() {
        return Collections.shuffle(this, List::ofAll);
    }
}
```

Note: I did not compile the code above - it shows the basic idea.

**Comment by fabianboeller** [comment]
@danieldietrich @io7m 
Thanks for your effort with Vavr! 
Was there a specific reason why the deterministic variant of shuffle `Seq.shuffle(Random random)` from the original request was not implemented back then?
Currently, it is still necessary to do a workaround for this one.

**Comment by io7m** [comment]
This was just straightforward forgetfulness on my part. I'd actually forgotten I'd written this code too... :roll_eyes:

**Comment by danieldietrich** [comment]
@fabianboeller thx! No, we should add `Seq.shuffle(Random)`! I will re-open this issue.

**Comment by io7m** [comment]
I'm on it.

**Comment by danieldietrich** [comment]
Nice, thank you!

**Comment by danieldietrich** [comment]
Done with the speed of light by @io7m 💫
