### ISSUE TITLE
Add missing methods to PriorityQueue

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1346]
Check if there are still methods of Traversable that need to be overridden and implement them. Maybe return types need to be adjusted.

We once had a unit test that dynamically checked the type hierarchy if we missed to override methods. This test had a whitelist because some methods intentionally weren't overridden. Maybe we need to re-enable that test...

**Comment by danieldietrich** [comment]
@paplorinc Can this be closed?

**Comment by paplorinc** [comment]
I don't know, I haven't worked on this explicitly, not sure why it was opened.

**Comment by danieldietrich** [comment]
Ok, thanks. Will take a look...

**Comment by danieldietrich** [comment]
PriorityQueue will probably not part of Vavr 1. We want to focus on the most frequently used collections. Maybe we will release some kind of add-on collections package later.
