### ISSUE TITLE
Add Try.mapFailure(Function<Throwable, Throwable>)

### ISSUE THREAD

**Issue by ronanM** [vavr-io/vavr#1521]
Sometimes it could be useful to map the failure to add more information, for example by chaining the exception.

``` java
Try<Item> itemTry = ....

itemTry.flatMap(item -> 
  doSomethingTry(item.quantity()) // This could fail, but without a useful information.
  .mapFailure(ex -> new Exception("Error while computing item with id: " + item.id(), ex))
)
...

Try<...> doSomethingTry(int quantity) {...}
```

For the moment it could be done using `recoverWith(...)` and a static `mapFailure(...)`:

``` java
itemTry.flatMap(item -> 
  doSomethingTry(item.quantity()) // This could fail, but without a useful information.
  .recoverWith(mapFailure(ex -> new Exception("Error while computing item with id: " + item.id(), ex)))
)

public static <T> Function<? super Throwable, ? extends Try<? extends T>> 
mapFailure(Function<? super Throwable, ? extends Throwable> f) {
    return ex -> failure(f.apply(ex));
}
```

**Comment by danieldietrich** [comment]
Hi @ronanM,
thank you for your suggestion.
We could rather do it with `recoverWith` than introducing a new method:

```java
itemTry.flatMap(item ->
        doSomethingTry(item.quantity()) // This could fail, but without a useful information.
        .recoverWith(ex -> Try.failure(new Exception("Error while computing item with id: " + item.id(), ex)))
);
```

Another equivalent solution is to use `map` and `getOrElseThrow`:

```java
itemTry.mapTry(item ->
        doSomethingTry(item.quantity()) // This could fail, but without a useful information.
        .getOrElseThrow(ex -> new Exception("Error while computing item with id: " + item.id(), ex))
);
```

Maybe there are more solutions to the problem than I've shown above. I think we really do not need another method.

I will close the issue for now and also your PR.

Please don't worry when I close an issue. This is a step forward, not backward. We always learn s.th. new, me included!

**Comment by tinversenorm** [comment]
I'd like to reopen this for discussion. I think semantically `mapFailure` makes more sense and would be easier to read than `recoverWith` to add more information to a `Try.failure`. RecoverWith seems to be intended to recover a failure case and convert it to a success. The naming certainly indicates this.

**Comment by danieldietrich** [comment]
@tinversenorm you are right, it makes sense. It is already part of VAVR 1.0. There is a preview release of the control package: https://static.javadoc.io/io.vavr/vavr/1.0.0-alpha-2/io/vavr/control/Try.html#mapFailure(io.vavr.control.CheckedFunction)

**Comment by erikjara** [comment]
Hi @danieldietrich 

I'm sorry to comment this closed thread, but there's no sign of this method on 1.0.0-alpha-3 version and up, so will be discarded for final version?

Incidentally, thank you for this wonderful library, I'm using on my workplace repos and work flawless.

**Comment by erikjara** [comment]
Hi @danieldietrich 

I'm sorry to comment this closed thread, but there's no sign of this method on 1.0.0-alpha-3 version and up, so will be discarded for final version? (I can create the Pull Request if necessary).

Incidentally, thank you for this wonderful library, I'm using on my workplace repos and work flawless.

**Comment by PratikBhusal** [comment]
> but there's no sign of this method on 1.0.0-alpha-3 version and up

Here is the commit that added the method to master:
https://github.com/vavr-io/vavr/commit/459d188bce03eb4c14a16fe94587dfe37b118b86

Here is the last commit that had the method in master:
https://github.com/vavr-io/vavr/blob/28896a83a607e35775c4ad2be0ef822c034ed17a/vavr/src/main/java/io/vavr/control/Try.java#L593-L605

It was removed in the following commit from master:
https://github.com/vavr-io/vavr/compare/28896a8...4fa635a5f640d871c58d967b1aa0e459f5c7777c#diff-95fadb44425ac06924a37066a537a4be05819dace1207e155cbe26ec47144813L599-R598

To see the changes between the first commit that had the method and 1.0.0-alpha-3:
https://github.com/vavr-io/vavr/compare/459d188...vavr-1.0.0-alpha-3#diff-62c83e39394d03a2ace34c80b861281bd8cd75bf80cb0b9ac8506cf7c433314cL576-R639

To see the changes between the last commit that had the method and 1.0.0-alpha-3:

https://github.com/vavr-io/vavr/compare/28896a83a607e35775c4ad2be0ef822c034ed17a...vavr-1.0.0-alpha-3#diff-62c83e39394d03a2ace34c80b861281bd8cd75bf80cb0b9ac8506cf7c433314cL599-R639

**Comment by pivovarit** [comment]
I'd like to circle-back here. There's some redundancy in the API already that will need to be handled before releasing another major version. However, given the current situation, it makes sense to reintroduce this method

**Comment by pivovarit** [comment]
Merged :)

**Comment by Deano217** [comment]
This method does not seem to be in 1.0.1. I thought based on this issue and #2759 that this method would've been re-added in the latest version. Am I missing something?

**Comment by pivovarit** [comment]
That old `1.0.0-alpha-*` is effectively `2.x`, but we could definitely bring it back in the next small release

**Comment by Deano217** [comment]
> That old `1.0.0-alpha-*` is effectively `2.x`, but we could definitely bring it back in the next small release

That would be great. Thanks for your work on this project.
