### ISSUE TITLE
Align to Scala 2.12 Future API

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1531]
Viktor Klang created great blog posts on the changes of Future in Scala 2.12:
- [x] [Missing canonical combinators: flatten](http://viktorklang.com/blog/Futures-in-Scala-2.12-part-1) (see #241) - _we use flatMap(t -&gt; t) instead_
- [ ] [Missing canonical combinators: zipWith](http://viktorklang.com/blog/Futures-in-Scala-2.12-part-2)
- [ ] [Missing canonical combinators: transform](http://viktorklang.com/blog/Futures-in-Scala-2.12-part-3)
- [ ] [Missing canonical combinators: transformWith](http://viktorklang.com/blog/Futures-in-Scala-2.12-part-4)
- [x] [Missing canonical combinators: Deprecations: onSuccess and onFailure](http://viktorklang.com/blog/Futures-in-Scala-2.12-part-5) - _in Vavr these methods return the Future instance, so they can be chained. In our case forEach is not a total version of onSuccess. We keep all methods._
- [ ] [Missing utilities: unit & never](http://viktorklang.com/blog/Futures-in-Scala-2.12-part-6)
- [x] [Deprecations and Refactors](http://viktorklang.com/blog/Futures-in-Scala-2.12-part-7) _We have refactors, see #2093, especially we removed Promise._
- [x] [Goodbye, sun.misc.Unsafe](http://viktorklang.com/blog/Futures-in-Scala-2.12-part-8) - _this does not apply to Vavr_
- [x] [Feature: Improved Promise Linking (I promise!)](http://viktorklang.com/blog/Futures-in-Scala-2.12-part-9) - _Currently out of scope for us. I think the risk in Java isn't that high for OOME because there is no tailrec. _

We should add additional combinators and see if the other blog posts (6-9) are relevant to Javaslang's Future.

See also #1529.

**Comment by paplorinc** [comment]
FYI: http://www.scala-lang.org/news/2.12.0

**Comment by hepin1989** [comment]
Alias to Scala 2.13

**Comment by danieldietrich** [comment]
Our Future implementation will be dropped. There will be no Vavr 1.0 module `vavr-concurrent`.

Reason: Implementing our own concurrency library is too error-prone, concurrency is a hard problem. There are many(!) alternatives, first of all Java's native CompletableFuture
