### ISSUE TITLE
[public visibility] Make our GitHub homepage a better appetizer

### ISSUE THREAD

**Issue by l0rinc** [vavr-io/vavr#1648]
The current https://github.com/javaslang/javaslang homepage is quite dry, newcomers won't be sold instantly by the idea - every link clicked halves the audience.

The best examples from the tests and http://www.javaslang.io/javaslang-docs should be included in the home page (also see https://github.com/functionaljava/functionaljava and https://github.com/slamdata/matryoshka for good examples) in a short but concise manner (maybe even comparing it to Java and stating it publicly that we're following Scala) ... maybe even include some benchmarks and everything that would address the concerns of most people.

Also, the project's description needs to be compacted as well (i.e. `object-oriented programming with the elegance and ro… http://javaslang.io`)

**Comment by danieldietrich** [comment]
I thought the same several times. We will give the page a fresh look and release it together with 2.1.0. I will make it available under a different url before in order to get some feedback.

**Comment by pivovarit** [comment]
@danieldietrich keep in mind that if you need some consultations about the graphical side of things, Filip will be there to help :)

**Comment by danieldietrich** [comment]
@pivovarit thank you, I will contact him!

**Comment by danieldietrich** [comment]
See also #1163
