### ISSUE TITLE
Adjust the return types of factory methods and remove casts from API aliases

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1727]

**Comment by AlparSzabados** [comment]
Can you please provide more information? (could you find an example?)

**Comment by danieldietrich** [comment]
@AlparSzabados please wait with this one. This idea came to me while investigating a pattern matching improvement but it might be obsolete.

Also we need to concentrate on Milestone 2.1.0 issues. Almost all 3.0.0 issues are not backward compatible. In order to keep the technical release process as simple as possible we first do 2.1.0, after that release we do 3.0.0 changes.

**Comment by AlparSzabados** [comment]
Alright, thank you for the answer. I will look for something else to fix.

**Comment by danieldietrich** [comment]
Obsolete. We will keep the concepts of Value and Pattern/unapply() distinct.
