### ISSUE TITLE
Make AbstractIterator package-private

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1729]
We use AbtractIterator in order to ensure the NoSuchElementExceptions on empty.next() call are homogenous along all Iterator impls throughout Javaslang and to reduce code duplication.

We should keep the number of types as simple as possible. There is no need to share our impl with the users.

**Comment by ruslansennov** [comment]
Someone (I dont remember exactly) asked for public visibility

**Comment by danieldietrich** [comment]
you (I think) :)

Currently we use AbstractIterator only in the javaslang.collection package. Iterator itself is used almost everywhere but it is instantiated by using the factory methods. I think it could be made package private. Let users write Iterators how they are used to write them!

**Comment by ruslansennov** [comment]
> you (I think) :)

NO!!! :smile: 

> Currently we use AbstractIterator only in the javaslang.collection package. Iterator itself is used almost everywhere but it is instantiated by using the factory methods. I think it could be made package private. Let users write Iterators how they are used to write them!

I agree with you

**Comment by danieldietrich** [comment]
@ruslansennov 

![1269602956_dr-mccoy-and-captain-kirk-approve](https://cloud.githubusercontent.com/assets/743833/20778241/b2db13e8-b76c-11e6-9d24-d56bf744713e.gif)
