### ISSUE TITLE
Fix backward compatibilty issue regarding *Map.of(Object...) in 2.1.0-alpha

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1757]
@talios [mentioned](https://gitter.im/javaslang/javaslang?at=584e0d4fc29531ac5d4f7dba) that the *Map.of(Object...) factory methods disappeared in 2.1.0-alpha (in favor of(KVKVKV)) because the former was unsafe.

For the reason of backward compatibility we need to re-add them, marked as `@Deprecated`.

**Hint:** Wait for #1716, which will generate these automatically throughout all Map types!

**Comment by ruslansennov** [comment]
Daniel, I'm ready to begin, but I'm not sure that we should do this because now we have new groupId, artifactId and artifatcVersion :)

**Comment by danieldietrich** [comment]
@ruslansennov I plan to do many changes in the upcoming release vavr-0.9.0 that affect backward compatibility.

The reason is that because of the new package names the upcoming release is no drop-in replacement anymore.

If someone wants to migrate his/her code to the new version, he needs control over the code. If he/she has control over the code, also the breaking changes can be easily fixed, presupposed a migration path exists.

In fact I see the name change as a lucky coincidence. Finally we are able to fix many issues. The backward compatibility slowed us down immensely.

**Comment by danieldietrich** [comment]
@ruslansennov

> Daniel, I'm ready to begin

Go ahead!

**Comment by danieldietrich** [comment]
Fixed with #1954
