### ISSUE TITLE
Implement an efficient PriorityQueue.iterator() method

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1808]
Currently we use inefficient code like this when iterating PriorityQueue elements:

```java
    @Override
    public List<T> toList() {
        List<T> results = List.empty();
        for (PriorityQueue<T> queue = this; !queue.isEmpty(); ) {
            final Tuple2<T, PriorityQueue<T>> dequeue = queue.dequeue();
            results = results.prepend(dequeue._1);
            queue = dequeue._2;
        }
        return results.reverse();
    }
```

The underlying Tree should offer a traversal method that can be used by the iterator.

**Comment by paplorinc** [comment]
I'm afraid this is as optimal as it gets. The tree is lazily calculated on every `dequeue`, you cannot currently iterate it otherwise, just by removing elements from it.

**Comment by danieldietrich** [comment]
If there is a _tree_, there is a _[traverse](https://en.wikipedia.org/wiki/Tree_traversal)_. We will see...

**Comment by danieldietrich** [comment]
PriorityQueue will probably not part of Vavr 1. We want to focus on the most frequently used collections. Maybe we will release some kind of add-on collections package later.
