### ISSUE TITLE
The underlying PriorityQueue Tree should offer a dequeue() that returns a Tree

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1809]
Currently PriorityQueue.take() delegates to dequeue(), which returns a Tuple2 of the head element and the tail PriorityQueue:

```java
    @Override
    public PriorityQueue<T> tail() {
        if (isEmpty()) {
            throw new UnsupportedOperationException("tail of empty " + stringPrefix());
        } else {
            return dequeue()._2;
        }
    }
```

 This leads to unnecessary GC pressure. E.g. drop() calls n times tail(), which currently creates n Tuple2 instances which are immediately thrown away:

```java
    @Override
    public PriorityQueue<T> drop(int n) {
        PriorityQueue<T> result = this;
        for (long i = n; i > 0 && !result.isEmpty(); i--) {
            result = result.tail();
        }
        return result;
    }
```

**Comment by paplorinc** [comment]
What do you base your assumption, of `GC pressure`?
Have you measured whether the garbage is eliminated by escape analysis, or is it just a hunch :)?

**Comment by danieldietrich** [comment]
@paplorinc kiddo, will you tell me that creating Tuples that are not needed for the final result will not be consumed by the GC. Nice try :)

**Comment by danieldietrich** [comment]
PriorityQueue and Tree will probably not part of Vavr 1. We want to focus on the most frequently used collections. Maybe we will release some kind of add-on collections package later.
