### ISSUE TITLE
Remove Try.Checked* functional interfaces

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1812]
The Try.Checked* functions are a workaround. With Project Valhalla (primitive generics) we will remove the Try.Checked* methods and have

CheckedFunction0<R> extends CheckedFunction1<void, R> (or maybe remove Function0 completely)
CheckedFunction0<void> instead of Try.CheckedRunnable
CheckedFunction0<R> instead of Try.CheckedSupplier<R>
CheckedFunction1<T, boolean> instead of Try.CheckedPredicate<T>
...

**Comment by ruslansennov** [comment]
see #1968 #1975

**Comment by danieldietrich** [comment]
Yes, but we only moved them (and not removed them).

To remove them we need primitive generics, like

```java
Function<void, T>    == Supplier<T>
Function<void, void> == Runnable
...
```

**Comment by danieldietrich** [comment]
For now we are finished. The story goes on when Java gets primitive generics.
