### ISSUE TITLE
[public visibility] Add release/snapshot gradle/maven configs to the main github page

### ISSUE THREAD

**Issue by paplorinc** [vavr-io/vavr#1822]
http://www.javaslang.io/javaslang-docs/#_getting_started should appear in the main github `README.md` also.

People are more interested in how to *use* Javaslang, than how to *build* it or *run* its benchmarks. :)

**Comment by danieldietrich** [comment]
Yes, that makes sense. We should in turn move part of the current README.md to the CONTRIBUTION.md.
