### ISSUE TITLE
Shift / rotate

### ISSUE THREAD

**Issue by devinrsmith** [vavr-io/vavr#1863]
I missed an obvious method here: https://github.com/javaslang/javaslang/issues/1862... so I'll just ask a question here instead of proposing something!

Is there a `rotate` or `shift` method? 

Thanks.

**Comment by danieldietrich** [comment]
Currently there is only cycle() in Stream, which can be used in conjunction with take() and drop(). Given that you achieve the same as rotate() or shift().

I'm o.k. with adding rotate() and/or shift(), but we need a clear specification of the API interface. I think it makes sense to add it only to sequential collections, i.e. Seq.

**Comment by devinrsmith** [comment]
I think the semantics and API interface could be pretty straightforward:

`[rotate|shift]Right(n) = takeRight(n % len).appendAll(dropRight(n % len))`
`[rotate|shift]Left(n) = drop(n % len).appendAll(take(n % len))`

(Might need some special handling when `n < 0`, or limit to `n >= 0`)

I'm not sure how the library prefers to handle "out of bounds", and this method could limit `0 <= n < len` and get rid of the remainder op if necessary.

**Comment by danieldietrich** [comment]
That looks good. I would not throw, instead `[rotate|shift]Right(n)` should delegate to `[rotate|shift]Left(-n)` for negative `n` vice versa. The `n % len` saves us from out of bounds failures.

In this context I would prefer `rotate` over `shift`. What we have is a [circular shift](https://en.wikipedia.org/wiki/Circular_shift), so `shift` would be confusing here.
