### ISSUE TITLE
Consider adding javaslang.concurrent.Future#get(timeout)

### ISSUE THREAD

**Issue by anaumidis** [vavr-io/vavr#1871]
It would be nice to have a `Try<T> get(Long timeout)` in a `Future`.

**Comment by anaumidis** [comment]
Maybe it'll be better to use [Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html) here.

**Comment by davinkevin** [comment]
I'm really waiting this functionality to migrate my codebase to Vʌvr 😉

**Comment by danieldietrich** [comment]
@davinkevin Future will get some love after 0.9.0 - soon!
