### ISSUE TITLE
Ensure <collection>.ofAll(Iterable) returns the Iterable if it has the correct type

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1873]
Example:

```java
public static <T> PriorityQueue<T> ofAll(Comparator<? super T> comparator, Iterable<? extends T> elements) {
    Objects.requireNonNull(elements, "elements is null");
    if (elements instanceof PriorityQueue) {
        return (PriorityQueue<T>) elements;
    } else {
        ...
    }
}
```

**Comment by ruslansennov** [comment]
I believe this is wrong way (for `PriorityQueue` at least). Someone may want to create instance based on another one with new comparator

**Comment by danieldietrich** [comment]
@ruslansennov absolutely right - I've overseen that.

* SortedSets have a Comparator
* BitSet has an toInt Function
* Multimaps have a value container
* ...

**Comment by ruslansennov** [comment]
We can do it like in `TreeSet`
```java
if (values instanceof TreeSet && ((TreeSet) values).comparator() == comparator) {
    return (TreeSet<T>) values;
} else {
    // ...
}
```

**Comment by danieldietrich** [comment]
@ruslansennov That looks like a good solution! The check isn't costly compared to creating new instances.

**Comment by pivovarit** [comment]
Done some investigating. Summarizing here:

`Array` has it already:
https://github.com/vavr-io/vavr/blob/dcd456536b26df01fcc1930baf7a2a832c808819/src/main/java/io/vavr/collection/Array.java#L147-L149

`HashSet` has it already:
https://github.com/vavr-io/vavr/blob/a53c966a27eb3ddbf88cab3de31801a35d29ea9e/src/main/java/io/vavr/collection/HashSet.java#L157-L159

`CharSeq` has it already:
https://github.com/vavr-io/vavr/blob/b45b755726780534eec8e46ba02b9a80c7b6f3b4/src/main/java/io/vavr/collection/CharSeq.java#L133-L135

`LinkedHashSet` has it already:
https://github.com/vavr-io/vavr/blob/bef625a6b1bce8e5fbfca3a4113ad1fc51fce264/src/main/java/io/vavr/collection/LinkedHashSet.java#L161-L163

`List` has it already:
https://github.com/vavr-io/vavr/blob/dcd456536b26df01fcc1930baf7a2a832c808819/src/main/java/io/vavr/collection/List.java#L237-L239

`PriorityQueue` has it already:
https://github.com/vavr-io/vavr/blob/6dc555e705e894583918a90500e518750a417599/src/main/java/io/vavr/collection/PriorityQueue.java#L228-L230

`Queue` has it already:
https://github.com/vavr-io/vavr/blob/b45b755726780534eec8e46ba02b9a80c7b6f3b4/src/main/java/io/vavr/collection/Queue.java#L156-L158

`TreeSet` has it already:
https://github.com/vavr-io/vavr/blob/6dc555e705e894583918a90500e518750a417599/src/main/java/io/vavr/collection/TreeSet.java#L202-L204

`Vector` has it already:
https://github.com/vavr-io/vavr/blob/fd8e652947c69e96885aacecaeb7a7a548587f22/src/main/java/io/vavr/collection/Vector.java#L181-L183

`Stream` has it already:
https://github.com/vavr-io/vavr/blob/b45b755726780534eec8e46ba02b9a80c7b6f3b4/src/main/java/io/vavr/collection/Stream.java#L379-L381

**Comment by pivovarit** [comment]
`BitSet` doesn't but I'm not sure if it is desired: https://github.com/vavr-io/vavr/pull/2539

**Comment by danieldietrich** [comment]
This looks already good. Let's close this issue. Thanks for your investigation!
