### ISSUE TITLE
Add a HashMap.collector(Function, Function) for key/value mapping.

### ISSUE THREAD

**Issue by talios** [vavr-io/vavr#1889]
Java 8 comes with `java.util.stream.Collectors#toMap(java.util.function.Function<? super T,? extends K>, java.util.function.Function<? super T,? extends U>)` which is really useful for collecting a stream of values into a specific key/value shape.

Currently Javaslang requires one to first `map` to a `Tuple2` and _then_ use `HashMap.collector()` which works fine in a lot of cases, but depending on your code base, the calling function might not have access to the stream itself.

Providing a `HashMap.collector(Function)` (key map function, value using Identity) and a `HashMap.collector(Function,Function)` (key and value mapping functions) similar to that provided by the JDK would be a big win.

**Comment by danieldietrich** [comment]
I will move all incoming feature-requests to 3.0.0 now - otherwise we will never see 2.1.0.

**Comment by danieldietrich** [comment]
Fixed with #2017 by @ruslansennov
