### ISSUE TITLE
Introduce Tailrec for Stackless recursion

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1901]
See also http://trane.io

**Comment by paplorinc** [comment]
Could you please provide more info?
How would automatic stackless recursion be possible on the `JVM`?

**Comment by danieldietrich** [comment]
I had in mind to create a generalized Tailrec type, very similar to [this](https://github.com/traneio/future/blob/dc041e66be0bfa431039b969487732d6ac9b1d39/future-java/src/main/java/io/trane/future/Tailrec.java).

**Usage:**

```java
public Future<Integer> factorial(Integer i) {
    Tailrec.apply(() ->
        if (i ==0) return Future.value(1);
        else factorial(i - 1).map(j -> i * j);
    );
}
```

_(copied from the javadocs, see link above)_

**Comment by paplorinc** [comment]
In what language is the above example written in?

It's certainly not `Java`, it lacks several `return` statements and braces, the wrapper `Integer` seems pointless and it's not even formatted properly... and worst of all, it's not stack safe, it simply calls itself, which introduces a new stack element (several actually) for each call.

**Comment by danieldietrich** [comment]
It is copy-pasted from the javadoc. However, it is a java class. Please follow the link (I already provided above):

https://github.com/traneio/future/blob/dc041e66be0bfa431039b969487732d6ac9b1d39/future-java/src/main/java/io/trane/future/Tailrec.java

**Comment by paplorinc** [comment]
I have seen it, it's still not Java :)

**Comment by danieldietrich** [comment]
Really!? Maybe [Project Lombok](https://projectlombok.org/index.html) is used??

**Comment by paplorinc** [comment]
I doubt it, they just probably haven't checked the code ...

**Comment by paplorinc** [comment]
Why do you think this will avoid the stack exactly?

**Comment by danieldietrich** [comment]
Don't have the time currently to explain it. Mario Fusco wrote about it (I think there are at least slides on slideshare), Functional Programming in Java may have a section about it and cyclops-react project also had s.th. similar...

**Comment by danieldietrich** [comment]
Instead of introducing a new (public) type `Trampoline` we should consider to add a method

```java
function*.trampoline()
```

See [how Kotlin does it](http://groovy-lang.org/closures.html#_trampoline)

**Comment by paplorinc** [comment]
Related: https://medium.com/@johnmcclean/trampolining-a-practical-guide-for-awesome-java-developers-4b657d9c3076

**Comment by danieldietrich** [comment]
Also related: https://de.slideshare.net/mariofusco/lazine (page 33 ff)

**Comment by danieldietrich** [comment]
Technically it is possible, but it is artificial to do so. Looks like new, intermediate object instances are created on each recursion step in order to move the stack activity to the heap. That's no option for is.
