### ISSUE TITLE
Alternative to Validation.combine()

### ISSUE THREAD

**Issue by fagossa** [vavr-io/vavr#1938]
Hi everyone,

I'm proposing an update to the `Validation` functor.

Let's assume we have this class
```
class Person {
  private String name;
  private String email;
  private int age;
  ...
}
```

As per the official documentation, the correct way to create a validation is as follows:

```
Validation
    .combine(
        validateName(name),
        validateEmail(email),
        validateAge(age))
    .ap(Person::new)
```

`combine` has 8 overrides, supporting as many different validations instances.

However, for classes with many parameters this approach could not be adequate.

What I'm proposing is a workaround to the 8 parameter limitation.

The idea is to create a builder that internally stores a `List` of validations and we are able to trigger the whole thing at will. Like this:

```
Validation<List<String>, Person> validation =
  new Validation.Builder<String, Person>()
        .combine(p -> validateAge(p))
        .combine(p -> validateName(p))
        .combine(p -> validateEmail(p))
        .apply(person);
```

I would be glad to make a PR. But, first I would like to check with you if it is worth it before going any further.

What do you thing?

regards

**Comment by fagossa** [comment]
Perhaps this is somehow related to [Issue 1565](https://github.com/javaslang/javaslang/issues/1565).

**Comment by danieldietrich** [comment]
@fagossa This definitely sounds interesting. What is the return type of the first combine call?

```java
new Validation.Builder<String, Person>().combine(p -> validateAge(p))
```

A List can only hold values of one type, say `T`. How are the List objects correctly typed when calling `.apply(Person::new)`.

(You wrote `.apply(person)` but I think you meant `.apply(Person::new)`)

**Comment by fagossa** [comment]
@danieldietrich 

`combine` is now a fluid `append` for the list containing our different `Validation`'s.

```
public Builder<E, O> combine(Function<O, Validation<List<E>, O>> func) {
    functions.add(func);
    return this;
}
```

I really ment 
```
.apply(person)
```

And this is probably the biggest flaw of this approach: you specify a `T` and the whole validation process is executed on that instance (e.g. an instance of Person).

**Comment by danieldietrich** [comment]
Interesting approach. It is (more or less) equivalent to

```java
static <T, E> List<E> validate(T value, Function<? super T, ? extends Option<? extends E>>... validators) {
    return List.of(validators).flatMap(validator -> validator.apply(value));
}
```

Example:

```java
List<String> errors = validate(person,
        p -> validateAge(p),
        p -> validateName(p),
        p -> validateEmail(p)
);
```

---

It is too early to create a PR now. I will take your issue into account when revisiting Validation.

There are too many open issues regarding Validation at the moment, e.g. Validation&lt;String, T&gt; vs. Validation&lt;List&lt;String&gt;, T&gt; after combination (but also other things).

I need to understand the whole scenery before fixing one specific point.

**Comment by danieldietrich** [comment]
Validation in this form will probably not part of Vavr 1.0 - it does not scale well because of the restriction to Function8.
Instead we should think about a redesign from scratch or leave it away and stick to alternatives like Either.sequence...

**Comment by GabpmcpML** [comment]
Hi! I need a way for modeling OR function with Validation monoid... But I can't because combine is a AND function. Any idea?

**Comment by fagossa** [comment]
@GabpmcpML I'm not aware of exactly what you are looking for; I think you might need another Semigroup for `Validation` because you want to change the notion of `combine` and dunno if that's possible with `vavr`. For an adhoc approach I think you could still use `Validation` but you might need to provide an equivalent of `combine`, something along `MyValidation.combineAny(varargs)`, then just iterate over the elements and applying your logic

**Comment by GabpmcpML** [comment]
@fagossa `combine` models a product, not a sum. I need validate an optional argument. Only validate if has a some value but composing with combine.
