### ISSUE TITLE
Try.of() shouldn't soften exceptions by changing exception category for rethrown (fatal) exceptions

### ISSUE THREAD

**Issue by nfekete** [vavr-io/vavr#1964]
`Try.of()` currently catches all exceptions and rethrows them if fatal in a wrapper exception. The wrapper for fatal exceptions is `javaslang.control.Try.FatalException`, which extends `java.lang.RuntimeException`, this way it changes exception categories and softens `Error`s (possibly `java.lang.VirtualMachineError` and subclasses) to `RuntimeException`s.

**Comment by nfekete** [comment]
See for example google guava introduced [ExecutionError](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/util/concurrent/ExecutionError.html) as a counterpart of JDK's [ExecutionException](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutionException.html) to wrap `Error`s to keep the semantics of the exception type categories. Also [UncheckedExecutionException](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/util/concurrent/UncheckedExecutionException.html) for wrapping `RuntimeException`.

**Comment by danieldietrich** [comment]
I thought you meant including 'NotImplementedError' into the set of fatal exceptions when you said to create a ticket for Try.Fatal :)

This issue will be solved when we solve #1722.

**Comment by nfekete** [comment]
No, why would I want to make it fatal? I was arguing for great lengths to make `TODO()` use a softer exception, not a more severe one :)
