### ISSUE TITLE
A question about the Collection interfaces

### ISSUE THREAD

**Issue by landawn** [vavr-io/vavr#1974]
I see there are a lot of common methods defined in List/Set/Queue/Array/... and wondering why there is no a common interface to abstract the common methods to make the interfaces more concise/consistent?

**Comment by danieldietrich** [comment]
There are common interfaces LinearSeq and IndexedSeq - and on top of them Seq and Traversable.

Which methods do you mean for example?

**Comment by landawn** [comment]
For example, filter/map/flatMap/distinct/top/... Can these methods be defined/implemented in a basic abstract class? or move them to a separated interface, like Steam API to Collection in java.util?

**Comment by danieldietrich** [comment]
We have already package-private classes for that purpose in io.vavr.collection, e.g. Collections, Maps, Multimaps, Comparators, AbstractMultimap and AbstractQueue. But I think there is potential to further simplify things.

However, please note that there is a JDK bug, that prevents us from using method references when we use package-private abstract classes. See #1326

**Comment by danieldietrich** [comment]
I will close this ticket. Improvements are ongoing progress.

**Comment by landawn** [comment]
Ok, thanks
