### ISSUE TITLE
Thoughts on adding Tuple2.empty(), Tuple3.empty()  ....... ?

### ISSUE THREAD

**Issue by bhchandra** [vavr-io/vavr#1977]
Recently I came across a situation where if a condition failed returning Tuple2.empty() would have been good.
Any thoughts on adding Tuple{2,3,4....}.empty() ? 

Unrelated question: 
Is there going to be renaming of the packages from javaslang to vavr?

Thanks for the great library.

**Comment by danieldietrich** [comment]
Hi,

> Any thoughts on adding Tuple{2,3,4....}.empty() ?

I think that is not possible. What should be an instance of an empty Tuple2? We will not use `null` as placeholder for nothing!

E.g. the following is **no** option for us:

```java
// = Tuple2(null, null)
Tuple2<Void, Void> empty = Tuple2.empty();
```

**Comment by danieldietrich** [comment]
Btw, we did the same with `Option` by adding

```java
interface Option {
    static Option<Void> nothing() {
        return Some(null);
    }
}
```

This confused our users. We will remove it with the upcoming release.

**Comment by bhchandra** [comment]
Thank you for answering!
