### ISSUE TITLE
Valid Maven central repo

### ISSUE THREAD

**Issue by maystrovyy** [vavr-io/vavr#1989]
What about valid Maven central dependency?

**Comment by danieldietrich** [comment]
@maystrovyy Thank you for asking but I don't understand your question. Please be more specific.

Is there currently an invalid dependency? Where? Within one of our pom.xml files?

**Comment by emmanueltouzery** [comment]
i think he means the "maven-central: unknown" on the vavr home page. which is due to no vavr artifacts having been released yet, pending 0.9.0.

**Comment by danieldietrich** [comment]
Ahh, ok - yes :) we are aware of it.

Spoiler alert: It will be solved today or tomorrow.
