### ISSUE TITLE
Document Vector (and other collection) performance characteristics?

### ISSUE THREAD

**Issue by chronodm** [vavr-io/vavr#1999]
The [old Vector documentation](https://static.javadoc.io/io.javaslang/javaslang/2.0.1/javaslang/collection/Vector.html) only says “It provides the best performance in between Array (with constant time element access) and List (with constant time element addition)”. The [current documentation](https://github.com/vavr-io/vavr/blob/af679318de4406abe30583e8253c89da61c1c8c6/vavr/src/main/java/io/vavr/collection/Vector.java#L23-L24) is better but still somewhat sketchy: “effectively constant time access to any element … many other operations (e.g. `tail`, `drop`, `slice`) are also effectively constant.”

I did some back-of-the-envelope performance testing comparing 1000-element and 5000-element vectors and found that while indexed access was roughly O(1), appending was O(log n), and`removeAt()` from the end of the list (the worst-case delete scenario, I hope) was O(2ⁿ). Meanwhile, testing indexed retrieval with 10⁶ elements showed a linear drop in performance—about 1000× slower, vs. about 500× slower for `java.util.ArrayList` (which was unsurprisingly much, much faster to begin with).

At any rate, I need to re-run my back-of-the-envelope tests with Vavr `Array`, but it would be great if Vavr had something like [Scala’s performance characteristics table](http://docs.scala-lang.org/overviews/collections/performance-characteristics) for Javaslang (though I notice Scala doesn't document remove performance for sequences, and doesn't seem to even implement `removeAt()` or similar for the immutable ones; possibly because performance is known to be terrible?).

Failing that (or even in addition) it would be good to have an overview in the [Seq section](http://www.vavr.io/vavr-docs/#_seq) of the main docs to help developers choose implementations for specific applications.

**Comment by paplorinc** [comment]
hey @chronodm,

We have actual, non-envelope JMH [performance tests for Vector](https://github.com/vavr-io/vavr/blob/master/vavr-benchmark/src/test/java/io/vavr/collection/VectorBenchmark.java).
You can check the file's history for measurements or run them yourself.

Removal of any element should be at most `O(n)`, and many other effectively constant operations are actually `log32` (which is always so small (<7) that you can treat it as if it were a constant)

For simple performance characteristics check out https://github.com/vavr-io/vavr/blob/master/vavr/src/main/java/io/vavr/collection/package-info.java (as JavaDoc)

If you think something is missing, please let us know :)

**Comment by danieldietrich** [comment]
We already have performance characteristics as part of the javadoc, as Lorinc said.
