### ISSUE TITLE
The link to API Docs in homepage points to Javaslang instead of Vavr docs

### ISSUE THREAD

**Issue by anaumidis** [vavr-io/vavr#2000]
The link currently points to [http://www.javadoc.io/doc/io.javaslang/javaslang](http://www.javadoc.io/doc/io.javaslang/javaslang) 
instead of [http://www.javadoc.io/doc/io.vavr/vavr](http://www.javadoc.io/doc/io.vavr/vavr)

**Comment by danieldietrich** [comment]
Fixed with vavr-io/vavr-io.github.io#6
