### ISSUE TITLE
io.vavr.API.Map(Tuple2<?, ?> t...) doesn't compile if even number of params

### ISSUE THREAD

**Issue by davinkevin** [vavr-io/vavr#2003]
I have a pr7oblem to use the new io.vavr.API.Map static method, due to its overloading when the number of parameters is even, I can't use it to define a Map with N (even) Tuple2.
So, this code doesn't compile :
```
    public void shouldMapFromTuplesReturnNotNull() {
        Map<String, Object> map = Map(
                Tuple("Foo", new Object()),
                Tuple("Foo", new Object()),
                Tuple("Foo", new Object()),
                Tuple("Foo", new Object())
        );
        assertThat(map).isNotNull();
    }
```

But it compiles if I add or remove one Tuple :
```
        Map<String, Object> map = Map(
                Tuple("Foo", new Object()),
                Tuple("Foo", new Object()),
                Tuple("Foo", new Object())
        );
        assertThat(map).isNotNull();
```

The error returned by the compiler is the following :
```
/home/travis/build/davinkevin/vavr-issues/src/test/java/MapTest.java:[23,39] incompatible types: io.vavr.collection.Map<io.vavr.Tuple2<java.lang.Integer,java.lang.String>,io.vavr.Tuple2<java.lang.Integer,java.lang.String>> cannot be converted to io.vavr.collection.Map<java.lang.Integer,java.lang.String>
```

I think it's normal due to the overload, but this behavior is unexpected...
Thanks for your help (I've search on the issue tracker and didn't find any information about that...)

You can find a project with the code example [here](https://github.com/davinkevin/vavr-issues/blob/master/src/test/java/MapTest.java) and the travis build with the error [here](https://travis-ci.org/davinkevin/vavr-issues)

PS : Sorry for the title, I didn't find better title...

**Comment by danieldietrich** [comment]
Hi @davinkevin,
you are right, it is not possible. We should have had tested it. Unfortunately we have to remove `API.Map(Tuple...)`.
Please use one of the `HashMap.of*(...)` methods.
Thx,
Daniel

**Comment by davinkevin** [comment]
I found a potential solution, but it requires to add information to help the compiler : 

```java
    public void shouldMapFromTuplesReturnNotNull() {
        Map<String, Object> map = API.<String, Object>Map(
                Tuple("Foo", new Object()),
                Tuple("Foo", new Object()),
                Tuple("Foo", new Object()),
                Tuple("Foo", new Object())
        );
        assertThat(map).isNotNull();
    }
```

You can find the code with modification [here](https://github.com/davinkevin/vavr-issues/blob/2003-compilation-problem-for-map/src/test/java/MapTest.java) and the travis build [here](https://travis-ci.org/davinkevin/vavr-issues/builds/237840345)
