### ISSUE TITLE
Consider the addition of a Try.WithResources*#run(CheckedConsumer*) method

### ISSUE THREAD

**Issue by anaumidis** [vavr-io/vavr#2004]
There are cases when we want to run some function that returns `void`.

While there is a `Try.run` that accepts a `CheckedRunnable`, when using the new Try.WithResources* API there is no equivalent method.

I see that there is only `CheckedConsumer` that accepts one argument but `Try.WithResources*` accepts up to 8 arguments so it'll require creating CheckedConsumers1..8 that accepts up to 8 arguments.

**Comment by flopezlasanta** [comment]
Possibly duplicate of https://github.com/vavr-io/vavr/issues/1263 ?

**Comment by danieldietrich** [comment]
@anaumidis thx!
@flopezlasanta yes, indeed - I've updated the referenced issue and will close this as duplicate
