### ISSUE TITLE
ConcatIterator iteration performance is bad when ConcatIterator is built by nesting other ConcatIterators

### ISSUE THREAD

**Issue by nfekete** [vavr-io/vavr#2005]
ConcatIterator has very bad iteration performance when the concatenated iterators are ConcatIterators themselves to some degree (not necessarily deep).

I've made a JMH test for this use case, and the numbers vs scala's iterators are looking like this:

| Impl               |   Params |          Score  ±  |   Error |   Unit | scala_persistent | vavr_persistent
|--------------------|----------|--------------------|---------|--------|------------------|----------------
| scala_persistent   |       10 |   2,115,225.97  |  ± 14.18% |  ops/s |                  |        188.51×
| scala_persistent   |       20 |   1,180,047.73  |   ± 7.15% |  ops/s |                  |     100537.32×
| vavr_persistent    |       10 |      11,220.68  |  ± 10.62% |  ops/s |           0.01×  |               
| vavr_persistent    |       20 |          11.74  |   ± 2.64% |  ops/s |           0.00×  |               

The test parameter in this case was represents both the nesting level of ConcatIterators *and* the number of values in the final iterator.

This means, that in the last vavr_persistent test with size=20, vavr was able to iterate only ~12 times a second over an iterator of just 20 elements.

There are multiple inefficiencies in the ConcatIterator implementation, like `current.hasNext()` [being called unnecessarily multiple times](https://github.com/vavr-io/vavr/blob/b3a746df440a81d1312f41d7e4431e5e545dd240/vavr/src/main/java/io/vavr/collection/Iterator.java#L2009-L2012), and the value for `hasNext()` could be cached until the next invocation of `next()`, but these account only for a constant factor. The main issue is that ConcatIterator keeps an inefficient structure for the iteration when nesting ConcatIterators.

**Comment by ruslansennov** [comment]
> The main issue is that ConcatIterator keeps an inefficient structure for the iteration when nesting ConcatIterators.

Do you have any thoughts about this?

**Comment by nfekete** [comment]
What I see is that when you're building an iterator by concatenating iterators which are themselves composed by concatenating iterators, possibly to some (not necessarily deep) levels, the overhead of delegating through the structure gets amplified very much. Even with those optimization that are easy (non-structural) that I mentioned about avoiding redundant `hasNext` invocations and caching `hasNext` boolean values if until `next()` is called, it's still slower than scala's solution. Though it's pretty significant improvement (from 100 000x slower to 10-20x slower). But I think the end goal would be to have something of similar performance as scala's, or even faster, if it's possible.

I see two ways to do it: optimize the structure at iteration time (scala seemingly does this) or at construction time. I'm currently evaluating how scala's solution would look like in vavr, but I'm not sure at all how a pretty verbatim translation of scala's code into vavr would be from licensing point of view. Scala's license allows it? How do we feel about verbatim translations?

**Comment by ruslansennov** [comment]
caching `hasNext` boolean values reduces complexity from exponential to something like linear
```
Target             Operation   Impl                  Params  Count            Score  ±     Error    Unit  scala_persistent  vavr_persistent
IteratorBenchmark  Concat      scala_persistent          10      5     2,583,938.92  ±     6.51%   ops/s                            14.02×
IteratorBenchmark  Concat      scala_persistent          20      5     1,444,009.89  ±     7.05%   ops/s                            20.48×
IteratorBenchmark  Concat      vavr_persistent           10      5       184,253.30  ±    12.01%   ops/s            0.07×                 
IteratorBenchmark  Concat      vavr_persistent           20      5        70,522.63  ±     1.46%   ops/s            0.05×                 
```
But this is not enough :smile:

**Comment by nfekete** [comment]
Yes, exactly. I made those easy optimizations quickly but didn't post them as I considered them still not enough. I got similar results as you.

**Comment by nfekete** [comment]
Verbatim translation of scala's solution would yield this result:

Impl                 | Params | Count  |          Score | ±     Error |   Unit | scala_persistent | vavr_persistent
---------------------|--------|--------|----------------|-------------|--------|------------------|----------------
scala_persistent     |     10 |     5  |   2,094,907.21 | ± 8.39% |  ops/s |                  |          1.69×
scala_persistent     |     20 |     5  |   1,127,814.37 | ± 4.44% |  ops/s |                  |          1.31×
vavr_persistent      |     10 |     5  |   1,242,418.52 | ± 10.06% |  ops/s |           0.59×  |               
vavr_persistent      |     20 |     5  |     859,934.93 | ± 7.18% |  ops/s |           0.76×  |               

It's still slower, but not by orders of magnitude.

**Comment by nfekete** [comment]
Please advise what to do :) I'm kinda short on time, but I can think on a solution to this if the porting the scala code is not acceptable for some reason. Or if it's okay, I can add the scala port to the PR.

**Comment by nfekete** [comment]
Oh, and BTW, is this necessary: [AbstractIterator.java#L31-L33](https://github.com/vavr-io/vavr/blob/c1f731a340d9fc1bf9c4e73b350cea5fd924ca68/vavr/src/main/java/io/vavr/collection/AbstractIterator.java#L31-L33)? This check in AbstractIterator also hurts performance in this particular case, or more generally, with complex Iterator structures.

**Comment by ruslansennov** [comment]
> Or if it's okay, I can add the scala port to the PR.

Thank you! The only problem is the licensing of the Scala code. I also (as you) do not know the details, maybe we need to ask someone from the Scala developers

> Oh, and BTW, is this necessary: `AbstractIterator.java#L31-L33`?

Yes, this is an common code that should inform users about the case of an empty iterator with appropriate message. I don't see any problem here because the `hasNext()` method must be fast (at least for the second and all next calls) in each iterator implementation.

**Comment by danieldietrich** [comment]
Fixed
