### ISSUE TITLE
Stream.dropUntil can be stuck in an infinite loop

### ISSUE THREAD

**Issue by bacey** [vavr-io/vavr#2007]
Hi!

I think I found a small bug:

```
// THIS PASSES
@Test
public void shouldNotStuckInAnInfiniteLoopWhenUsingDropUntilOnAFiniteStream() {
    final Stream<Integer> naturalNumbers = Stream.iterate(0, i -> i + 1).take(20);
    final Stream<Integer> naturalNumbersBiggerThanTen = naturalNumbers.dropUntil(i -> i > 10);
    final Integer firstNaturalNumberBiggerThanTen = naturalNumbersBiggerThanTen.head();

    assertThat(firstNaturalNumberBiggerThanTen).isEqualTo(11);
}

// THIS DOES NOT PASS
@Test
public void shouldNotStuckInAnInfiniteLoopWhenUsingDropUntilOnAnInfiniteStream() {
    final Stream<Integer> naturalNumbers = Stream.iterate(0, i -> i + 1);
    final Stream<Integer> naturalNumbersBiggerThanTen = naturalNumbers.dropUntil(i -> i > 10);
    final Integer firstNaturalNumberBiggerThanTen = naturalNumbersBiggerThanTen.head();

    assertThat(firstNaturalNumberBiggerThanTen).isEqualTo(11);
}
```

In the second test (`shouldNotStuckInAnInfiniteLoopWhenUsingDropUntilOnAnInfiniteStream`), the `dropUntil` function is stuck in an infinite loop.

Quoting Gregor Trefs @gtrefs:
> The length of an infinite stream is infinite. `dropUntil` relies on `Collections.dropUntil` where `length` is used to iterate over the elements in a `Seq`. The length of a stream is a fold left counting the elements. For an infite stream, this ends in an infinte loop. In Scala, the following works: `Stream.iterate(0)(_ + 1).dropwHile(_ <= 10)` while the counter part in vavr seems not to work `Stream.iterate(0, i -> i + 1).dropWhile(i -> i <= 10);`.

Tested on the v0.9.0 branch.

**Comment by ruslansennov** [comment]
Also we have very bad performance at least for `Stream` and `List` because of `get()` complexity is `O(N)`

#1749 should be reviewed again

**Comment by gtrefs** [comment]
@ruslansennov 
You are right. It looks like unifying the implementation in `Collections` is the culprit.
Before:
```Java
default Stream<T> dropWhile(Predicate<? super T> predicate) {	
       Objects.requireNonNull(predicate, "predicate is null");
        Stream<T> stream = this;	
        while (!stream.isEmpty() && predicate.test(stream.head())) {		
            stream = stream.tail();		
        }		
        return stream;		
    }
```

After (call to Collections):
```Java
   @SuppressWarnings("unchecked")
    static <T, S extends Seq<T>> S dropUntil(S seq, Predicate<? super T> predicate) {
        Objects.requireNonNull(predicate, "predicate is null");
        for (int i = 0; i < seq.length(); i++) {
            if (predicate.test(seq.get(i))) {
                return (S) seq.drop(i);
            }
        }
        return (S) seq.take(0);
    }
```

Though, I am not sure how one can improve the the complexity?

**Comment by ruslansennov** [comment]
> Though, I am not sure how one can improve the complexity?

Current algorithm is `O(N^2)` for `Stream` and '`List`, so we can't use `Collections.dropUntil` in these cases and it seems we should roll back the changes
