### ISSUE TITLE
Actions not executed for cancelled futures

### ISSUE THREAD

**Issue by ummels** [vavr-io/vavr#2010]
According to the [documentation](http://static.javadoc.io/io.vavr/vavr/0.9.0/io/vavr/concurrent/Future.html#onFailure-java.util.function.Consumer-), actions registered with `onFailure` should be executed when a future is cancelled. However, this does not seem to be the case as the following code prints nothing:

```
Future<?> f = Future.of(() -> { while (true) {} });
f.onFailure(e -> println("Failure"));
f.cancel();
if (!f.isFailure())
    println("Oops");
Thread.sleep(1000L);
System.exit(0);
```

**Comment by nfekete** [comment]
Note that while this doesn't affect the bug itself, `while (true) {}` is not interruptible, i.e., it will never release the thread back to the `ExecutorService`, even if you call `cancel()`.

**Comment by ummels** [comment]
Thanks for the info. I guess `while (true) { Thread.sleep(100L); }` would be a better example.

**Comment by ruslansennov** [comment]
It seems that the problem code is [FutureImpl.java#L199](https://github.com/vavr-io/vavr/blob/04732331a6dd24c39669012e00de6953dd65b8d7/vavr/src/main/java/io/vavr/concurrent/FutureImpl.java#L199). Computation fails in `Try` block with `InterruptedException` which is fatal according to [Try.java#L1493](https://github.com/vavr-io/vavr/blob/04732331a6dd24c39669012e00de6953dd65b8d7/vavr/src/main/java/io/vavr/control/Try.java#L1493). 

I believe we should use classic `try {} catch () {}` block here.
See #1976

**Comment by ruslansennov** [comment]
And maybe `actions.forEach(this::perform)` should be [here](https://github.com/vavr-io/vavr/blob/04732331a6dd24c39669012e00de6953dd65b8d7/vavr/src/main/java/io/vavr/concurrent/FutureImpl.java#L132)

**Comment by ruslansennov** [comment]
see #1963

**Comment by danieldietrich** [comment]
I think the `FutureImpl.cancel(boolean)` function needs to look like this:

```java
    @Override
    public boolean cancel(boolean mayInterruptIfRunning) {
        synchronized (lock) {
            if (isCompleted()) {
                return false;
            } else {
                return Try.of(() -> job == null || job.cancel(mayInterruptIfRunning)).onSuccess(cancelled -> {
                    if (cancelled) {
                        complete(Try.failure(new CancellationException()));
                    }
                }).getOrElse(false);
            }
        }
    }
```

Interestingly we already have a unit test:

```java
    @SuppressWarnings("InfiniteLoopStatement")
    @Test
    public void shouldInterruptLockedFuture() {
        final Future<?> future = Future.of(() -> {
            while (true) {
                Try.run(() -> Thread.sleep(100));
            }
        });
        future.onComplete(r -> fail("future should lock forever"));
        future.cancel();
        assertCancelled(future);
    }
```

After the fix is applied, the test onComplete handler, which throws an AssertionError, is executed. Currently the onComplete actions are executed on different threads (which will be changed with #1530), so the unit test is still green.
