### ISSUE TITLE
User Guide Documentation Correction?

### ISSUE THREAD

**Issue by ahlusar1989** [vavr-io/vavr#2013]
Referencing the legend.

There is a typo in the documentation: `amotized` should be `amortized`, if I am not mistaken?

**Comment by ruslansennov** [comment]
Hi @ahlusar1989 
This issue belongs to `vavr-io/vavr-docs` project. Could you provide a PR to fix it?

**Comment by ahlusar1989** [comment]
Happy to @ruslansennov!
