### ISSUE TITLE
Seq returned by Map.values() should know its own size

### ISSUE THREAD

**Issue by chronodm** [vavr-io/vavr#2020]
The implementations of `Map.values()` all return a `Stream`. This makes operations like `map.values().toJavaSet()` unnecessarily expensive on large maps, since (for reasons I admit I'm unclear on) they require the `size()` of the `Stream`, and this needs to be calculated with `foldLeft`.

![profiler snapshot](https://user-images.githubusercontent.com/2934647/27599942-2a1ee686-5b1f-11e7-8330-2631acbbee5d.png)

**Comment by ruslansennov** [comment]
@chronodm thanks for report

**Comment by dmolesUC3** [comment]
No problem. I ran a quick test with Array.of(map.values()).map(t._2) and it was quite a bit faster, but making that copy might have memory implications we don't want.

**Comment by chronodm** [comment]
No problem. I ran a quick test with `Array.of(map.values()).map(t._2)` and it was quite a bit faster, but making that copy might have memory implications we don't want.

**Comment by danieldietrich** [comment]
This is a cross-cutting issue.
