### ISSUE TITLE
Multimaps generics

### ISSUE THREAD

**Issue by ruslansennov** [vavr-io/vavr#2027]
```java
// compiles fine
HashMultimap<Integer,String> map1 = HashMultimap.<String>withSortedSet().of(1,"1");
// compilation fails with "Inferred type is not within its bound"
HashMultimap<Integer,String> map2 = HashMultimap.withSortedSet().of(1,"1");
```
The same for `LinkedHashMultimap` and `TreeMultimap`. Also see #2026 
Can be fixed by changing the builder's signature from
```java
public static <V extends Comparable<? super V>> Builder<V> withSortedSet() {
    return new Builder<>(ContainerType.SORTED_SET, TreeSet::empty);
}
```
to
```java
public static <V extends Comparable<?>> Builder<V> withSortedSet() {
    return new Builder<>(ContainerType.SORTED_SET, TreeSet::empty);
}
```

**Comment by danieldietrich** [comment]
Mmhh, I'm not sure if we need `V` at all. I think all Multimap `Builder`s do not need any generics.

Also, for `TreeMultimap` the `V` does not need to be `Comparable` because only the keys are compared.

What do you think?

**Comment by ruslansennov** [comment]
> only the keys are compared

In the worst case we need to define two comparators. For example:

* `HashMap[Set]` - no comparators required
* `LinkedHashMap[SortedSet] - it is necessary to determine values comparator
* `TreeMap[Seq] - it is necessary to determine keys comparator
* `TreeMap[SortedSet] - it is necessary to determine the both comparators

**Comment by danieldietrich** [comment]
You are right, thank you!
