### ISSUE TITLE
accept TupleN as parameter for FunctionN

### ISSUE THREAD

**Issue by jangalinski** [vavr-io/vavr#2034]
I can write

```
Tuple3<String,String,Long> tuple = Tuple.of("foo","bar", 5L);
Function3<String, String, Long, String> combine = (a,b,c) ->  a + b + c*c;

log.info(tuple.apply(combine));
```
and get `foobar25`, but I can't

```
log.info(combine.apply(tuple));

// i have to use
log.info(combine.apply(tuple._1, tuple._2, tuple._3));
```

would be handy if MultiParam Functions would accept tuples.

**Comment by jangalinski** [comment]
a .... .tupled() does what I want. Sorry for the interruption!

**Comment by danieldietrich** [comment]
Hi @jangalinski, nice to hear from you!
We met at HSH in Hamburg ;)

**Comment by jangalinski** [comment]
Hi Daniel ... I know. Ipressive what you've done since then :+1:

**Comment by danieldietrich** [comment]
Thank you 😊
