### ISSUE TITLE
Add method to check that no item of a collection matches a Predicate?

### ISSUE THREAD

**Issue by PascalSchumacher** [vavr-io/vavr#2035]
I recently migrated code from eclipse-collections to vavr.

One method I'm missing is the inverse of `Value#forAll` like `Value#forNone`.

By the way: Thanks for providing vavr! :+1:

**Comment by danieldietrich** [comment]
Hi Pascal,

all Traversable impls have the static `empty()` factory method. Does it cover your use-case?

Note: Other Value impls (than collections) have different methods that create an 'empty' instance (in the way that instance.isEmpty() returns true):

* Try.failure(...)
* Either.left(...)
* Future.failed(...)
* Option.none()
* ...

**Comment by PascalSchumacher** [comment]
Hi Daniel,

thanks for response.

Sorry for the lacking issue description.

I  am really looking for is a method to check that no item of a collection matches a `Predicate`. The inverse of `Value#exists` method.

**Comment by danieldietrich** [comment]
Hi,
sorry for the late answer.
Please use `value.forAll(negatedPredicate)`.
You could either negate your confition directly or use Predicate.negate().
