### ISSUE TITLE
Don't allow upper bound types in io.vavr.collection.Set#unzip

### ISSUE THREAD

**Issue by Sir4ur0n** [vavr-io/vavr#2046]
Following discussion with @danieldietrich on #1342 

There is a slight difference in return type between `io.vavr.collection.Set#unzip` and `io.vavr.collection.List#unzip`.
The former returns `Tuple2<? extends Set<T1>, ? extends Set<T2>>` while the latter returns `Tuple2<List<T1>, List<T2>>` (i.e. no upper bound (`extends`)), and this is quite disturbing (and I don't see why they have different return types).

Example of weird/problematic code I came accross:
```java
// Does not compile: "Bad return type in lambda expression: Tuple2<String, String> cannot be converted to Tuple2<? extends T1, ? extends T2>"
Set<String> set = HashSet.empty();
Tuple2<Set<String>, Set<String>> unzip = set.unzip(s -> Tuple.of("", ""));

// Compiles
List<String> list = List.empty();
Tuple2<List<String>, List<String>> unzip = list.unzip(s -> Tuple.of("", ""));
```

PS: I know I can work it around by wrapping the `set.unzip(s -> Tuple.of("", ""))` with a `Tuple.narrow(...)`, but it seems like extra work, and I don't see the benefit of such a method signature.

Thanks!

**Comment by danieldietrich** [comment]
I think this is a cross-cutting concern. Other return types may also need to be changed in order to be consistent...

**Comment by danieldietrich** [comment]
We have many method return types that are similar to those of unzip*, i.e. return types that contain a (wrapper) self-type.

I'm searching a formal reason to change unzip* while leaving other methods like tailOption() as-is. But I haven't found an explanation, yet.

I tend to leave the type-signatures as-is (we only fix them for sorted collections).

@Sir4ur0n What do you think? Could you live with that solution (leaving it as-is)? If not, what is your preferred solution (see also [this comment](https://github.com/vavr-io/vavr/issues/1342#issuecomment-335037259))?

---

Btw - I think life will get a bit easier when Java ships local variable type inference (in March 2018?):

```java
// Compiles
var set = HashSet.empty();
var unzip = set.unzip(s -> Tuple.of("", ""));

// Compiles
var list = List.empty();
var unzip = list.unzip(s -> Tuple.of("", ""));
```

**Comment by Sir4ur0n** [comment]
@danieldietrich I most certainly can live with it. My main issue is inconsistency of API between similar concepts (List vs Set) but I also understand the design issues behind are not easy to solve.

At least this issue may be useful in the future if somebody else wonders about this inconsistency ;)

**Comment by danieldietrich** [comment]
@sir4ur0n thank you
