### ISSUE TITLE
PartialFunction.orElse

### ISSUE THREAD

**Issue by skestle** [vavr-io/vavr#2048]
Given a `PartialFunction` I'd like to be able to supply another `PartialFunction` to be used when the first is not defined as in [scala's PartialFunction](http://www.scala-lang.org/api/2.12.0/scala/PartialFunction.html#orElse[A1<:A,B1>:B](that:PartialFunction[A1,B1]):PartialFunction[A1,B1]) (see example in at the top of the class docs)

**Comment by danieldietrich** [comment]
This issue can be solved after #2023 has been solved, because of ambiguities.

For example Map extends PartialFunction. Because Map currently extends Value, it also has get(), getOrElse() and orElse(), ... This currently leads to ambiguities.

**Comment by danieldietrich** [comment]
Closed because of #2176.
PartialFunction will be moved to io.vavr.match and only used for that purpose.
