### ISSUE TITLE
PartialFunction.lift

### ISSUE THREAD

**Issue by skestle** [vavr-io/vavr#2051]
`PartialFunction` should have a lift function that looks something like

```
Function1<T, Option<R>> lift() {
    // return t -> Option.of(t).collect(this); // I don't think reuse makes sense in this case
    return t -> Option.when(isDefinedAt(t), apply(t));
}
```

**Comment by skestle** [comment]
If the second option is chosen, then Option could change `collect` to be `return orElse(partialFunction.lift().apply(get()))`...

Which could be further refactored to 2 methods of `return collect(partialFunction.lift())`
and 
```
Option<R> collect(Function<? super T, Option<? extends R>> function) {
   return orElse(function.apply(get()));
{
```

**Comment by danieldietrich** [comment]
Agreed, that makes sense.

**Comment by miszasty93** [comment]
#2058
