### ISSUE TITLE
Include Capsule in our benchmarks

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2053]
https://github.com/usethesource/capsule

**Comment by CauchyPeano** [comment]
What kind of help needed here?

**Comment by danieldietrich** [comment]
We could start by adding a benchmark that compares certain Vavr collection operations with those of the Capsule collections. Especially it will tell us

1. how good our HAMT and BMT perform
2. if we could improve our collections

We already have benchmarks that compare our collections with those of Scala and Clojure. In a first step we could add Capsule to the party.

**Comment by CauchyPeano** [comment]
@danieldietrich what I see that HAMT from capsule is already included into benchmark `io.vavr.collection.MapBenchmark`
Regarding BMT I couldn't find it in capsule library... Do I miss something?

**Comment by danieldietrich** [comment]
Right - there seems nothing to do for us. Capsule seems to implement HAMT only.
Let's close this ticket, okay?

**Comment by CauchyPeano** [comment]
@danieldietrich yeah, totally fine with me :) I was just puzzled if it's me that maybe don't understand something.

**Comment by danieldietrich** [comment]
@CauchyPeano thanks!
