### ISSUE TITLE
Either.sequence should return Either<Seq<L>, Seq<R>>

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2064]
In the case of Either (as opposed to Try/Option) it makes sense to accumulate also the left values.

We recently added Either.sequence - it was forgotten. Because it is still not released, we are able to change the signature for the upcoming 0.9.1 patch release.

```java
// current signature
static <L,R> Either<L, Seq<R>> sequence(Iterable<? extends Either<? extends L, ? extends R>> values) { ... }

// new signature
static <L,R> Either<Seq<L>, Seq<R>> sequence(Iterable<? extends Either<? extends L, ? extends R>> values) { ... }
```

**Semantics:** `sequence` collects all right values if all given Eithers are Right, else it collects all Left instances (if one or more Eithers are Left).

**Usage example:**

```java
Either<Seq<L>, Seq<R>> result = Either.sequence(either1, either2, ...);

// perform ugly side-effects
result.orElseRun(errors -> ...);
```

**Comment by hamnis** [comment]
Both signatures are useful. I am using the first version quite extensively. I would strongly suggest that both be available.

Maybe the original can be made available through `sequenceU` which most closely matches `scalaz` Traversable type class.

**Comment by danieldietrich** [comment]
@hamnis Thanks for your feedback!

I see no benefit in keeping the first suggestion `Either<L, Seq<R>> sequence(...)` or introduce `Either<Seq<L>, R> sequenceLeft()`.

Having `Either<Seq<L>, Seq<R>> sequence(...)`, we are still able to achieve the same result as above like this:

```java
// if either.isLeft() == true, the Seq<L> is guaranteed to be non-empty
Either<Seq<L>, Seq<R>> either = Either.sequence(...);

// valid when either.isLeft() == true
L example1 = either.getLeft().head();

// valid in each case
either.mapLeft(seq -> {
    L example2 = seq.head();
    ...
});
```

Scalaz works different. Because Either resp. `\/` is right-biased there, no implicit Applicative instance for the left case can be offered in scope. In Java we do not have these problems, so we can do both in one sequence step.

What are your 'main pain points' with that solution?

**Comment by danieldietrich** [comment]
Having a result of type `Either<Seq<L>, Seq<R>>` makes most sense, because we cover all use cases.

If other sequence methods are needed, e.g. that return `Either<L, Seq<R>>` or `Either<Seq<L>, R>`, we should create a new issue.

**Comment by RobWin** [comment]
I love the new sequence :)

**Comment by hamnis** [comment]
I need that implementation to be monadic, so I guess i will have to keep my own version. It is more interesting to have the types align than the collection of all the errors, If i needed that I would use Validation.

**Comment by hamnis** [comment]
Here is a version that is monadic:

````java
public static <L, R> Either<L, List<R>> sequenceM(List<Either<L, R>> eithers) {
        return eithers.foldLeft(Either.<L, List<R>>right(List.empty()), (acc, item) -> acc.flatMap(list -> item.map(list::prepend))).map(List::reverse);
    }
```

**Comment by danieldietrich** [comment]
@hamnis Good point, I see. We should add the monadic version, also. I will create a separate issue.

Do you have an example of types that would not align?

**Comment by hamnis** [comment]
Any either where the next step would be to either work with the sequenced operation with the set Left side.

Here is a slighly adapted example from our codebase

`OptionTEither` is a Option MonadTransformer focused on Either.

```java
OptionTEither.wrap(bankCustomer).flatMap(customer -> OptionTEither.<BankError, AccountInformation>lift(customer.getAccount()).flatMapF(acc -> {
            return sequence(documents.map(tuple -> tuple.apply((name, bundles) -> {
                return sequence(bundles.map(bundle -> createAgreementDocumentBundle(principal, bundle, acc.getNumber(), Option.none()))).map(list -> PDF.merge(name, list.flatMap(Function.identity())));
            })).toList()).map(Option::some);
        })).unwrap().flatMap(opt -> opt.toRight(BankError.internal("Customer or account not found")));
```

The returntype of the above Expression is: `Either<BankError, List<AgreementDocument>>`

**Comment by danieldietrich** [comment]
@hamnis Thanks!
