### ISSUE TITLE
Remove Either projections in favor of swap

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2071]
Currently we support both: projections and the right-biased approach.

I think we can abandon the projections for the 1.0.0 release. Details see [here](http://robsscala.blogspot.de/2012/06/fixing-scalaeither-unbiased-vs-biased.html)

**Comment by CauchyPeano** [comment]
I've checked this one, so far as I understand left and right projections should be removed. As right-biased approach is already there and tested. Can I create PR with just removal of those subclasses and corresponding tests?

**Comment by danieldietrich** [comment]
@CauchyPeano I would greatly appreciate you PR!
