### ISSUE TITLE
Add monadic version of Either.sequence

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2074]
We labeled this issue as 'bug' and not as 'feature' because it is a follow-up of #2064. There we added an _applicative_ `Either<Seq<L>, Seq<R>> sequence(...)`.

But it might come handy to have a _monadic_ **`Either<L, Seq<R>> sequenceM(...)`**, too (see this [issue comment](https://github.com/vavr-io/vavr/issues/2064#issuecomment-327717610)).

**Comment by emmanueltouzery** [comment]
yeah I implemented the `Either<L,Seq<R>>` version because that's what haskell does:

```haskell
λ: sequence [Right 5, Left "bad", Left "so bad"]
Left "bad"
λ: :t sequence @[] @(Either String)
sequence @[] @(Either String)
  :: [Either String a] -> Either String [a]
```

**Comment by danieldietrich** [comment]
@emmanueltouzery Thanks! That makes sense.

In Haskell, the [Data.Traversable](https://hackage.haskell.org/package/base-4.10.0.0/docs/Data-Traversable.html) type has generic sequence* methods that transform sequences of _specific_ structures (like Monads and Applicatives).

<img width="1015" alt="screen shot 2017-09-08 at 12 06 11" src="https://user-images.githubusercontent.com/743833/30207131-befa25ce-948e-11e7-9595-7fed40549155.png">

In Vavr we do not have such abstractions (because of missing higher-order types) (see also [this](https://github.com/vavr-io/vavr/issues/2057#issuecomment-328077343)).

Erlend [showed](https://github.com/vavr-io/vavr/issues/2064#issuecomment-327719322) us a different approach, e.g. naming the monadic version in Either `sequenceM`.

Which method names should Either and Validation have then (sequence, sequenceA, sequenceM, ...)?

/cc @hamnis

**Comment by danieldietrich** [comment]
I took a look at

* Scala's [`sequence`](https://stackoverflow.com/questions/7230999/how-to-reduce-a-seqeithera-b-to-a-eithera-seqb)
* Scalaz's [`sequenceU`](https://github.com/scalaz/scalaz/commit/9894733dc8)
* @hamnis' [`sequenceM`](https://github.com/vavr-io/vavr/issues/2064#issuecomment-327719322)
* Haskell's [`sequence`](https://stackoverflow.com/a/38165029/1110815) and [`sequenceA`](https://github.com/vavr-io/vavr/issues/2074#issuecomment-328165443)

The [`sequenceM`](https://github.com/vavr-io/vavr/issues/2064#issuecomment-327719322) mentioned above isn't really monadic, it is syntactic sugar for

```java
// e.g. Seq<Either<L, R>> eithers = List.of(Right(...), Left(...));
Either<L, Seq<R>> res0 = Either.sequence(eithers.filter(Either::isRight));
```

Therefore I don't think we need to add a `sequenceM`.

We will keep the outcome of #2064 because it is practicable to collect all left values (aka errors):

```java
static <L, R> Either<Seq<L>, Seq<R>> sequence(Iterable<Either<L, R>> eithers) { ... }
```

Additionally we need the version that concentrates on the right values. I think it is intuitive to name it `sequenceRight()`:

```java
static <L, R> Either<L, Seq<R>> sequenceRight() { ... }
```
