### ISSUE TITLE
Internal/Library Development: Remove all Eclipse related comments and workarounds

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2075]
We will support `javac` and `IntelliJ` only in order to keep the code clean.

The reason is that the main contributors work with javac/IntelliJ and we have no automated way to test compatibility with Eclipse / ECJ.

**Comment by nfekete** [comment]
That would most probably break GWT compatibility.

**Comment by danieldietrich** [comment]
Good point. Then we will not do it and leave it as-is.

**Comment by danieldietrich** [comment]
I reopen this ticket for now. It does not seem to work in Eclipse currently. See #2082.
