### ISSUE TITLE
Annotate generated classes with @Generated

### ISSUE THREAD

**Issue by thomasdarimont** [vavr-io/vavr#2081]
Generated classes like [CheckedFunction0](https://github.com/vavr-io/vavr/blob/ec2d9b4337004792e786b42e0ac3eddc6ddf4bc8/vavr/src-gen/main/java/io/vavr/CheckedFunction0.java#L41) could be annotated with `javax.annotation.Generated` to differentiate them from hand written code.

Furthermore the generator class as well as the actual generator method could be referenced via the comment attribute to ease finding the appropriate generator method.

**Comment by danieldietrich** [comment]
Hi Thomas,

thank you for your suggestion! Could you please elaborate on the use-case(s)?

Currently we ensure that PRs will fail when generated code is manually modified. Our CI build does this by...

1. performing a `git clone` (which may contain manually modified generated code)
2. running the build (which overwrites generated code)
3. checking for changes using `git status` (there shouldn't be changes)

By using annotations, we make the 'is generated' property part of the public API. However, users should not bother whether source is generated or not. We need the freedom to change that property without affecting backward-compatibility.

I'm looking forward to learn about your use-case.

**Comment by danieldietrich** [comment]
Maybe this might come handy when we use an 'inline code generator' (see [Seamlessly fuse hand-written and generated code](https://github.com/vavr-io/vavr/issues/1716))

**Comment by danieldietrich** [comment]
I just saw that `@Generated` has the retention policy 'SOURCE' - now I understand that the use-case you meant is documentation. So, let's do it!
