### ISSUE TITLE
Is there any guideline for creating an Eclipse project for vavr?

### ISSUE THREAD

**Issue by smillies** [vavr-io/vavr#2082]
I am struggling with compiling Vavr in Eclipse. I can compile with Maven on the command line, and can also import the existing Maven projects into Eclipse (Oxygen). But compilation gives me ca. 85 errors and hangs somewhere when compiling collections. I guess this has to do with wrong or missing settings for code generation (Scala) and/or annotation processing. Is there a simple way to create a working Eclipse project?

**Comment by danieldietrich** [comment]
I started developing Vavr in Eclipse and tested it once with Mars (and also Neon I think). Eclipse always had false-positive type errors that needed workarounds and a *very* slow type inference that sometimes hung. I created several issues on the Eclipse bug tracker before I completely to IntelliJ IDEA. I do not use Eclipse anymore.

It is perfectly possible to run projects in Eclipse that depend on Vavr. But compiling Vavr itself in Eclipse is a challenge. I hope there is someone else who can provide some useful information...

**Comment by smillies** [comment]
Thank you. I will try IntelliJ then.

**Comment by nfekete** [comment]
@smillies vavr compiles under Eclipse since https://github.com/vavr-io/vavr/pull/2224 and the IDE has a decent performance working with vavr since [Eclipse JDT: Slow compilation in project with many wildcards generics](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521438)

I think this issue can be closed.

**Comment by nfekete** [comment]
Well, actually, vavr-benchmark doesn't compile yet under Eclipse, but I'll provide a fix shortly.

![image](https://user-images.githubusercontent.com/16191714/39424496-501596d8-4c77-11e8-9e04-a6da5e89413c.png)

**Comment by nfekete** [comment]
PR for the fix: https://github.com/vavr-io/vavr/pull/2244

**Comment by danieldietrich** [comment]
Thank you all!
