### ISSUE TITLE
Wrong javadoc, Promise::tryComplete never throws IllegalStateException

### ISSUE THREAD

**Issue by mxj4** [vavr-io/vavr#2095]
https://github.com/vavr-io/vavr/blob/22ac10513caccca8385dd2ca7da3bd53b736db11/vavr/src/main/java/io/vavr/concurrent/Promise.java#L241

**Comment by nfekete** [comment]
It seems it can throw `IllegalStateException`, see https://github.com/vavr-io/vavr/blob/1e6af93c618198aa722714226a682eca13132d64/vavr/src/main/java/io/vavr/concurrent/FutureImpl.java#L250 and https://github.com/vavr-io/vavr/blob/1e6af93c618198aa722714226a682eca13132d64/vavr/src/main/java/io/vavr/concurrent/FutureImpl.java#L229

**Comment by mxj4** [comment]
@nfekete `tryComplete` call `complete` only when `isCompleted()` is false, and the `isCompleted()` check is synchronized so complete from another thread cannot happen concurrently with the check.

**Comment by danieldietrich** [comment]
That's right - it may throw. However, maybe it is an implementation detail and we should fix the API spec for 1.0. I will keep the ticket open.

**Comment by mxj4** [comment]
@danieldietrich can you enlighten me on how would `tryComplete` throw IllegalStateException? And does `fix the API spec` mean you plan to make it not throw in 1.0?

**Comment by danieldietrich** [comment]
@mxj4 it can't throw, otherwise the Future invariant does not hold and a bug is revealed. It never threw so far (nor it will). It should not be part of the public API and wil be removed in 1.0.

**Comment by mxj4** [comment]
@danieldietrich It's still useful in some cases. Currently I use ScheduledExecutorService with it to implement timeout for vavr Future.

**Comment by danieldietrich** [comment]
@mx4j thanks for the feedback

**Comment by danieldietrich** [comment]
Fixed that in #2093 - see also [this description](https://github.com/vavr-io/vavr/issues/1529#issuecomment-332019476)
