### ISSUE TITLE
[0.9.1] SortedSet's last() and tail() are broken for sets with non-natural order

### ISSUE THREAD

**Issue by KTannenberg** [vavr-io/vavr#2100]
Recent update to behavior of `max()` and `min()` in vavr 0.9.1 breaks behavior of some operations (I have found `last()` and `tail()`, haven't checked other).

This is because these operations use `max()` instead of `maxBy(tree.comparator())`

Test to reproduce error:
```
package io.whatever;
import static io.vavr.API.List;
import static io.vavr.API.SortedSet;
import java.util.Comparator;
import org.junit.Assert;
import org.junit.Test;
import io.vavr.collection.SortedSet;

public class VavrTest extends Assert {
  @Test
  public void test_SortedSet_last() {
    SortedSet<Integer> reverse = SortedSet(Comparator.reverseOrder(), 1, 2, 3, 4);

    assertEquals(List(4, 3, 2, 1), reverse.toList());
    assertEquals(4, (int) reverse.head());
    assertEquals(List(3, 2, 1), reverse.tail().toList());

    // works on 0.9.0, fails on 0.9.1
    assertEquals(1, (int) reverse.last());
    assertEquals(List(4, 3, 2), reverse.init().toList());

    // works on 0.9.1, fails on 0.9.0
    assertEquals(1, (int) reverse.min().get());
    assertEquals(4, (int) reverse.max().get());
  }
}
```

**Comment by danieldietrich** [comment]
Thanks! Looks like 0.9.2 will appear soon...

**Comment by KTannenberg** [comment]
As a side effect it results in class-cast exception when elements are not naturally sortable and `init`/`last` is called on SortedSet

**Comment by KTannenberg** [comment]
@danieldietrich, regarding old min/max in TreeSet, these were using RedBlackTreeModule's min/max and thus were very fast. Probably to ensure there would be no performance hit from using `Traversable.maxBy` it would be better to implement `last`/`head` inside TreeSet.

**Comment by danieldietrich** [comment]
@KTannenberg yes, that is important. I will consider that!
