### ISSUE TITLE
Keep an eye on Kotlin's ImmutableArrayList

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2116]
https://youtrack.jetbrains.com/issue/KT-2027

Scala does not implement its own immutable/persistent Array for example.

**Comment by roberterdin** [comment]
How does it differ from Scala's vector?

**Comment by danieldietrich** [comment]
There is no specification, yet.

**Comment by danieldietrich** [comment]
Out-of-scope.
