### ISSUE TITLE
ClassCastException when groupingBy (v0.9.1)

### ISSUE THREAD

**Issue by chb0github** [vavr-io/vavr#2118]
dead simple to reproduce:

code:
```java

import com.fasterxml.jackson.databind.ObjectMapper;
import io.vavr.Tuple;
import io.vavr.Tuple2;
import io.vavr.collection.List;
import io.vavr.collection.Map;
import java.io.IOException;
import java.io.InputStream;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;


@RunWith(JUnit4.class)
public class PatchTest {

  @Test
  public void testUserAddressPatchOperations() throws IOException {
    InputStream inputfile = this.getClass().getResourceAsStream("/comments.json");

    ObjectMapper mapper = new ObjectMapper().findAndRegisterModules();

    List<Map<String, String>> results = mapper.readValue(inputfile, List.class);
    Map<String, List<Tuple2<Tuple2<String, String>, List<Tuple2<String, String>>>>> result = results
        .groupBy(m -> m.get("table_schema").getOrElseThrow(RuntimeException::new))
        .mapValues(l ->
            l.map(m ->
                Tuple.of(
                    Tuple.of(
                        m.get("table_name").getOrElseThrow(RuntimeException::new),
                        m.get("comment").getOrElseThrow(RuntimeException::new)
                    ),
                    l.filter(c -> c.get("column_name").get() == null).
                        map(c ->
                            Tuple.of(
                                c.get("column_name").getOrElseThrow(RuntimeException::new),
                                c.get("comment").getOrElseThrow(RuntimeException::new)
                            )
                        )
                )
            )
        );
    System.out.println(result);
  }
}

```

data file `comments.json`

```json
[
  {
    "table_schema": "AppLog",
    "table_name": "PageActivity",
    "column_name": null,
    "comment": "Activity log for pages"
  },
  {
    "table_schema": "AppLog",
    "table_name": "PageActivity",
    "column_name": "ActivityIdentifier",
    "comment": "Identifier of the activity used for group reports"
  }
]
```
error:

```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to io.vavr.collection.Map

	at io.vavr.collection.Collections.groupBy(Collections.java:196)
	at io.vavr.collection.Collections.groupBy(Collections.java:186)
	at io.vavr.collection.List.groupBy(List.java:904)
```

**Comment by ruslansennov** [comment]
By default all json objects maps to `java.util.LinkedHashMap`. Try this:

```java
List<Map<String, String>> results = mapper.readValue(inputfile, 
    new TypeReference<List<Map<String, String>>>() {});
```

**Comment by chb0github** [comment]
I took a slightly different approach (addressing the issue you bring up).

`Map<String, String>[] results = mapper.readValue(inputfile, Map[].class);`

Using an `[]` is my preferred way to give jackson what it needs without introducing another anonymous type.

That does the trick. 

Previously, when I had this issue, it failed to marshal. I am not familiar with how one makes a jackson plugin but it is possible to have it ask vavr for a `Map`-like thing? Then Vavr's type could be supplied.

**Comment by ruslansennov** [comment]
> Map<String, String>[] results = mapper.readValue(inputfile, Map[].class);

interesting :smile: 

> it is possible to have it ask vavr for a Map-like thing? Then Vavr's type could be supplied.

I'm not sure I understand your question. When a jackson deserializes an object, it must know which class it should use to return. If the class is not specified, it uses a `java.util.LinkedHashMap`. As I know, you can specify a custom class in three ways: through a `.class` object in `readValue` method, through a `TypeReference` (for generics specify) or if it is a field of another outer class (bean). This scenario has nothing to do with the vavr-jackson module. Simply if you specify a vavr collection as a object of deserialization and do not register a module, you will get an error.

However, Jackson is a huge library, maybe I do not know something

**Comment by chb0github** [comment]
Glad you like that syntactic trick. If you just need a _collection_ of elements then an array does the trick without all the extra non-sense of a TypeReference to get around Java's generics mess. 

As for the rest of it: I know jackson has callback methodology support for basically saying: "I found this `JSON_ARRAY`, what type should I instantiate for it? 

But, I am not that knowledgable on the Jackson internals either
