### ISSUE TITLE
Method for build Tree from flat source

### ISSUE THREAD

**Issue by valery1707** [vavr-io/vavr#2122]
Building tree from flat source is common task, as I think: items from database query and so on.
But currently building tree from this type of source is complicated.
I suppose to create something like `Tree#ofAll(Iterable<T> source, Function<T, ID> idMapper, Function<T, ID> parentMapper)` (`super`/`extends` hidden for simplicity now).
I already has implementation based on #2121 and can add PR.

**Comment by danieldietrich** [comment]
I like that idea! Could you please provide an example (input, application, output)?
I think we need a new name for the method, maybe also `recurse` or `build` or ??? (see #2125)

**Comment by valery1707** [comment]
Some example:
```java
public class MenuItem {
  Long id;
  Long parentId;
  Long organizationId;
  String name;

  //todo getters and setters a hidden

  public toString() {
    return getName();
  }
}

public class MenuLoader {
  private final EntityManager em;
  public Tree<MenuItem> loadMenu(Long organizationId) {
    TypedQuery<MenuItem> query = em
      .createQuery("SELECT T FROM MenuItem WHERE (T.organizationId = :organization)");
    query.setParameter("organization", organizationId);
    java.util.List<MenuItem> items = query.getResultList();
    return Tree.build(items, MenuItem::getId, MenuItem::getParentId);
  }
}

public class MenuLoaderTest() {
  @Mock
  private EntityManager em;

  @Mock
  private MenuLoader menuLoader;

  @Before
  public prepareDatabase() {
    em.createQuery(
      "INSERT INTO menu_item(id, parent_id, organization_id, name) VALUES"
      + "\n  (1, NULL, 1, 'I')"
      + "\n, (2, 1, 1, 'II')"
      + "\n, (3, 1, 1, 'III')"
      + "\n, (4, 2, 1, 'IV')"
      + "\n, (5, 2, 1, 'V')"
    ).executeUpdate();
  }

  @Test
  private void testLoad() {
    Tree<MenuItem> tree = menuLoader.loadMenu(1);
    assertThat(tree.toLispString).isEqualTo("(I (II IV V) III)");
  }  
}
```

**Comment by danieldietrich** [comment]
@valery1707 Great, thank you!

The menu items may be iterated in arbitrary order when building the tree. What is the overall complexity of build such a tree when n is the number of menu items?

Naively I would say it is O(n * log n), because we iterate n MenuItems, search the parent in O(log n) and insert the new node in O(1) and rebuild the tree in O(log n) (or eff. O(1)? - which would be the same in O notion).

Or does your implementation require O(n) because it uses the recursion? But then I think the flat items need to have a specific order, right?

**Comment by valery1707** [comment]
My current implementation internally use `List#groupBy` function for build `Map<ID, List<T>>` and then use `Tree#recurse` for build children for founded roots.
Complexity of the `List#groupBy` is `O(n)` as I think.
Complexity of the `Tree#recurse` is about `O(log n)` if I correct analyze function.
Result complexity of the `Tree#build` is `O(n * log n)`.

I create PR with implementation in #2129
