### ISSUE TITLE
Remove META_INF.services from the main jar file

### ISSUE THREAD

**Issue by tmtron** [vavr-io/vavr#2124]
The `vavr.jar` file (of version `0.9.1`) includes a `META-INF/services/javax.annotation.processing.Processor` file, which mentions `io.vavr.match.PatternsProcessor`.

![vavr jar file contents](https://user-images.githubusercontent.com/20422904/31307578-76a488c4-ab67-11e7-923f-568a5bf47b18.png)

I think this is wrong and unnecessary: so please remove it.
Note: This file is only needed in the `vavr-match.jar` file, where it does already exist.

The problem may not be visible in java projects, but the Android Gradle plugin (Version 3) fails when it detects an annotation processor on the compile classpath:  
> If the plugin detects annotation processors on the compile classpath, your build fails and you get an error message that lists each annotation processor on the compile classpath.

_Quote from [Use the annotation processor dependency configuration](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html?utm_source=android-studio#annotationProcessor_config)_

To workaround the issue we can [Disable the error check](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html?utm_source=android-studio#disable_the_error_check)

Note: to make a really clean configuration possible it would also be good to separate the annotations and the annotation processor in different jars - e.g. like [Dagger](https://github.com/google/dagger/blob/master/README.md#android-gradle), but maybe this should be a separate issue?

**Comment by ruslansennov** [comment]
Thanks.
Already done, see #2102

**Comment by alshain** [comment]
For future reference, this is probably the cause of the following error:

> Error:java: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider io.vavr.match.PatternsProcessor not found

**Comment by danieldietrich** [comment]
Thx!

**Comment by grnadav** [comment]
This also affects 0.10.0
Was the fix merged to that release as well?

**Comment by danieldietrich** [comment]
@grnadav it should be fine, here are the contents of the 0.10.0 jar:
<img width="336" alt="Screenshot 2019-03-20 at 09 47 46" src="https://user-images.githubusercontent.com/743833/54671028-4bc2a080-4af5-11e9-8583-0600f2a2416e.png">

**Comment by grnadav** [comment]
welp, I got here after receiving this error on the 0.10.0 version

**Comment by danieldietrich** [comment]
@grnada Interesting. Do you have old versions of VAVR (e.g. in form of transitive dependencies)?

Please try to include the vavr-match depenency: https://search.maven.org/search?q=a:vavr-match

(However, it looks a bit odd, I do not get such error messages)
