### ISSUE TITLE
Add PartialFunction factory for Value arguments

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2127]
We should create a PartialFunction factory that can be used in the presence of Value types, like Option, Try, (right-biased) Either, ...

```java
interface PartialFunction<T, R> extends Function<T, R> {

    static <T, V extends Value<T>> PartialFunction<V, T> getIfDefined() {
        return new PartialFunction<V, T>() {

            private static final long serialVersionUID = 1L;

            @Override
            public T apply(V value) {
                return value.get();
            }

            @Override
            public boolean isDefinedAt(V value) {
                return !value.isEmpty();
            }
        };
    }
}
```

I thought about the name, it could be

* get
* getIfDefined
* getIfNotEmpty
* apply                   &lt;--- I came up first with this - create a PartialFunction that applies a Value

Use case:

```java
Seq<Option<T>> maybeValues = ...
Seq<T> values = maybeValues.collect(PartialFunction::getIfDefined)
```

**Comment by florian-stefan** [comment]
I think that `getIfDefined` describes pretty good what the partial function actually does.

**Comment by danieldietrich** [comment]
@florian-stefan Great, than let's take that. Are you volunteering to solve this issue? 😜

**Comment by florian-stefan** [comment]
I am happy to do that :) Should be possible to solve this issue during this week.

**Comment by danieldietrich** [comment]
Awesome :) Take your time!

**Comment by florian-stefan** [comment]
I created a pull request (#2144). But the Travis job for the Java 9 build is failing (https://travis-ci.org/vavr-io/vavr/jobs/291081390#L2163). This seems to be a flickering test. Is there a way to restart the affected build job without using a dummy commit?

**Comment by danieldietrich** [comment]
> This seems to be a flickering test. Is there a way to restart the affected build job without using a dummy commit?

We will fix that Java 9 build soon - it does not matter for now.
