### ISSUE TITLE
Automated release process

### ISSUE THREAD

**Issue by chb0github** [vavr-io/vavr#2135]
There is currently no automated release process. This issue is meant to be a discussion forum on how to get there.

In a previous life I tried to get travis to auto-release artifacts to sonatype, here is what I can say:

1. You absolutely can automate the release to sonatype. Version 9+ of their POM handles this
2. You can generate a self-signed key and this will work for release purposes.
3. You have to be able to inject at build time credentials to create a tag in github (problem.. kinda)
4. You need a private key so you can sign your artifacts. You could check that in and password harden it with a strong password and then inject the password at build time. This I could never get to work because...
5. Maven doesn't seem to want to do env injections
6. Travis frequently ran out of memory

The only way I could see to do this is to simply rent a dedicate virt from a cloud provider for like, $5/month and move the entire build process there so secrets can be safely kept and memory issues can be extinguished

**Comment by danieldietrich** [comment]
I think this might work for major releases, but not for minor or patch releases.
It might also work for them but we need to change the branching model.
I'm open for discussion here. Please keep in mind that Vavr 1.0.0 will be based on Gradle builds, not on Maven builds.

**Comment by danieldietrich** [comment]
Out-of-scope for us. We have a relatively low release frequency. Semantic versioning/checking backward source/binary compatibility has to be done manually.
