### ISSUE TITLE
is 0.9.1 java9 compatible?

### ISSUE THREAD

**Issue by emmanueltouzery** [vavr-io/vavr#2139]
I see https://github.com/vavr-io/vavr/commit/44a23e7a341e7560b32306ae756f6746b0f8a153 which is not in 0.9.1, but I'm not 100% sure, I think maybe that's about building vavr with java9 and maybe it's safe to use a vavr 0.9.1 which was built on java8 (like the one we get from maven) on java9?

Sorry to open a bug for that, I've asked on gitter but there was no answer so far.

**Comment by danieldietrich** [comment]
I think 0.9.1 does not work well with Java 9, see #2102 for example.
We did not test 0.9.1 with Java 9, JDK9 wasn't released to that time - but 0.9.2 will be Java 9 compatible (both as dependency and build from source with JDK9).

**Comment by danieldietrich** [comment]
Emmanuel, I will close this as duplicate to #2097 - thanks for reporting!
