### ISSUE TITLE
Travis job for Java 9 build is flickering

### ISSUE THREAD

**Issue by florian-stefan** [vavr-io/vavr#2145]
The Travis job for the Java 9 build sometimes fails (see e.g. https://travis-ci.org/vavr-io/vavr/jobs/291085294#L2163).

**Comment by florian-stefan** [comment]
I think this issue is related: https://github.com/elastic/elasticsearch/issues/10145

> Traditionally, javac has performed some unspecified "simplifications" that led to T being inferred as 'Number' rather than 'CAP#1'. These unspecified behaviors break programs that should compile, but also allow programs like these to be compiled when the spec disallows them (see JDK-8039214).

**Comment by danieldietrich** [comment]
Fixed with #2172
