### ISSUE TITLE
[modules] The actual annotations and annotation processors should be in separate jar files

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2146]
Then we can add `vavr-match.jar` (which includes only the annotations) to the classpath and the `vavr-match-processor` to the processor-classpath.

See also https://github.com/vavr-io/vavr/issues/985#issuecomment-335446401

**Comment by CauchyPeano** [comment]
Hi @danieldietrich, I think I have done it. 
Could it be merged?

**Comment by danieldietrich** [comment]
Hi @CauchyPeano, thank you!
I will take a look this evening and comment the PR!
