### ISSUE TITLE
API changes review for Javaslang

### ISSUE THREAD

**Issue by lvc** [vavr-io/vavr#2150]
The review of API changes for the Javaslang library since version 2.0.0: https://abi-laboratory.pro/java/tracker/timeline/javaslang/

The report is generated by the https://github.com/lvc/japi-tracker tool for jars at http://central.maven.org/maven2/io/javaslang/javaslang/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library.

Please let me know if you'd like to see reports for any other modules in the tracker.

Thank you.

![javaslang-2](https://user-images.githubusercontent.com/1517837/31984526-8b6137d8-b96a-11e7-9009-bafe2df34106.png)

![javaslang-1](https://user-images.githubusercontent.com/1517837/31984527-8b7df800-b96a-11e7-8cda-d13e306f3fd3.png)

**Comment by danieldietrich** [comment]
Great, thank you! We could embed this overview in the docs.
Javaslang was renamed to Vavr - it would be great to also add it because Javaslang isn't updated anymore.

**Comment by lvc** [comment]
> Javaslang was renamed to Vavr - it would be great to also add it because Javaslang isn't updated anymore

https://abi-laboratory.pro/java/tracker/timeline/vavr/

![vavr-1](https://user-images.githubusercontent.com/1517837/33304581-d2586312-d41a-11e7-9d2e-4722a322119a.png)
![vavr-2](https://user-images.githubusercontent.com/1517837/33304580-d23b2da6-d41a-11e7-9ea2-c82245cb128d.png)
