### ISSUE TITLE
JDK9 does not (directly) support @Generated anymore, we should remove it again.

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2154]
See also #1716 and [this PR comment](https://github.com/vavr-io/vavr/pull/2151#issuecomment-342012670)

**Comment by valery1707** [comment]
@talios please comment this issue rather than that PR

**Comment by danieldietrich** [comment]
JDK9 has [javax.annotation.processing.Generated](https://docs.oracle.com/javase/9/docs/api/javax/annotation/processing/Generated.html),
JDK8 has [javax.annotation.Generated].

We cannot have both at the same time.
