### ISSUE TITLE
SortedMap interface does not define 'put' with value merger

### ISSUE THREAD

**Issue by mathiaskok** [vavr-io/vavr#2155]
The 'SortedMap' interface does not define 'put(K key, U value, BiFunction<? super V, ? super U, ? extends V> merge)'. If one attempts to use it, the 'Map' implementation is used, meaning the return type becomes 'Map'. The 'TreeMap' implementation does define this version of 'Put' with the correct return type.

**Comment by danieldietrich** [comment]
Thanks for reporting it! It shows that we need to ensure (at build time) that some specific API is correctly overridden.

**Comment by ruslansennov** [comment]
also 
* `put(Tuple2<? extends K, U> entry, BiFunction<? super V, ? super U, ? extends V> merge)`
* `replace(K key, V oldValue, V newValue)`
* `replaceAll(BiFunction<? super K, ? super V, ? extends V> function)`
* `replaceValue(K key, V value)`
