### ISSUE TITLE
Add reject(), the inverse of filter

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2156]
```java
interface Traversable<T> {
    // semantically equivalent to filter(f.negate())
    Traversable<T> reject(Predicate<? super T> predicate);
}
```

**Comment by valery1707** [comment]
Maybe use name `drop`?

**Comment by danieldietrich** [comment]
'reject' is a standard name, see [Martin Fowler's Collection Pipeline](https://martinfowler.com/articles/collection-pipeline/):

<img width="966" alt="screen shot 2017-11-08 at 15 17 58" src="https://user-images.githubusercontent.com/743833/32553807-27dd4ee8-c498-11e7-8df5-40de964405d1.png">
