### ISSUE TITLE
Return type of Seq.update

### ISSUE THREAD

**Issue by szarnekow** [vavr-io/vavr#2163]
It would be nice to get hold on the previous value when you use `Seq.update`. Maybe an alternative method that returns a `Tuple<T, Seq<T>>` could help here.

**Comment by danieldietrich** [comment]
I thought about it, this one has too many implications on other APIs. Using a simple `get(int)` instead (if the prev value is needed) solves the issue.

Thx for reporting! I hope you don't mind if I close the issue - I need to catch up with the issues of the last months...
