### ISSUE TITLE
Documentation: `String join(String... words)` simplification has much worse time complexity

### ISSUE THREAD

**Issue by bruno-medeiros** [vavr-io/vavr#2168]
In section 1.5.1 (http://www.vavr.io/vavr-docs/#_seq) there is an example of a standard Java 'join':
```java
String join(String... words) {
    StringBuilder builder = new StringBuilder();
    for(String s : words) {
        if (builder.length() > 0) {
            builder.append(", ");
        }
        builder.append(s);
    }
    return builder.toString();
}
```
and then a more concise alternative using Vavr:
```java
String join(String... words) {
    return List.of(words)
               .intersperse(", ")
               .fold("", String::concat);
}
```
Although more concise, it is not a fair comparison since `String::concat` will create a new String on each invocation, which happens on every iteration! Therefore this function has a time complexity of O(N^2), as opposed to amortized O(N*log(N)) of the original function. I propose this alternative instead, which has same time complexity as the original standard Java example:

```java
  String join(String... words) {
    return List.of(words)
            .intersperse(", ")
            .foldLeft(new StringBuilder(), StringBuilder::append).toString();
  }
```

**Comment by danieldietrich** [comment]
Thx, great suggestion. PR welcome 😄

**Comment by danieldietrich** [comment]
Fixed with https://github.com/vavr-io/vavr-docs/commit/ac5b4d8bcbd07bab0da136c7bf5d12b52f2da55e
