### ISSUE TITLE
For comprehensions on monadic types

### ISSUE THREAD

**Issue by imode69** [vavr-io/vavr#2171]
New to vavr and have recently started looking a for comprehensions to replace `a.flatMap(x => b.map(y => {...})` patterns with `for ( x <- a, y <- b) yield {...}`.

So I have this:

```java
    Option<Integer> a = Option.some(1);
    Option<Integer> b = Option.some(2);

    Option<Integer> s1 = a.flatMap(x -> b.map(y -> x + y));
    Option<Integer> s2 = For(a, b).yield((x, y) -> x + y).toOption();

    assertTrue(s1.eq(s2));
```
the toOption (same for Try) is necessary since For/Yield is defined only for Iterable<T>. Will this change in future versions of vavr?

**Comment by danieldietrich** [comment]
Yes, we will add For methods for our monadic types, see #1629.
