### ISSUE TITLE
Add static fill(int, T) methods

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2182]
Currently we have `fill(int, Supplier)`. It would be nice also to have `fill(int, T)` methods, similar to `Iterator.continually(...)`

**Comment by valery1707** [comment]
But what with `Supplier` variant?
I think in some cases `(int, Supplier)` can be useful.
Of course we can use `Stream.continually(Supplier).take(int).toSortedSet(Comparator)`

**Comment by danieldietrich** [comment]
@valery1707, mmhh, you might be right. The supplier is able to return different values on each call. I will update the issue title.

**Comment by valery1707** [comment]
Can be methods `fill(int, T)` and `fill(int, Supplier<T>)` ambiguous?
May be use different names like `fill() + fillWith()`?

**Comment by danieldietrich** [comment]
Stream and Iterator continually are not ambiguous I think. Then it should be also ok for fill. But we have to test it.
