### ISSUE TITLE
Unify bi-operators throughout the library and add missing methods

### ISSUE THREAD

**Issue by jlorenzen** [vavr-io/vavr#2190]
Be nice if vavr's `Either` class had a `bipeek` method like AOL's cyclops [Either](https://static.javadoc.io/com.aol.cyclops/cyclops-reactor/9.0.0-MI7/cyclops/control/lazy/Either.html#bipeek-java.util.function.Consumer-java.util.function.Consumer-) class. This would replace having to chain a `peek` and `peekLeft`.

**Comment by nfekete** [comment]
If this gets added, you might consider overloading `peek` instead of introducing `bipeek`. I don't see a reason to name it differently.

**Comment by danieldietrich** [comment]
Currently we have to disjoint union types: Either and Validation.

* both types are biased, Either operates on Right, Validation operates on Valid
* both currently have **map**, **mapLeft** and **bimap**
* other **bixxx** methods are not present
* the non-biased / alternate methods are named differently, e.g. Validation.getErrors() and Either.getLeft(). This makes it currently impossible to have a unified interface for both

We should unify the names and have a hidden common interface, maybe similar to Value?

For the Map collection we use similar methods. E.g. Map.bimap that takes a Key and a Value mapper.

I like the idea to provide similar-named overloads throughout the library, like @nfekete suggested.

**Comment by danieldietrich** [comment]
On help let's discuss it first.

**Comment by thadumi** [comment]
Should we introduce a BiTransformable<T1,T2>  (or Transformable2<T1,T2>) with the following methods?
```java
peek(Consumer<? super T1> c1, Consumer<? super T2> c2)
map(Function<? super T1,? extends X> mapper1, Function<? super T2,? extends Y> mapper2)
```
The name Trasformable2 would be more aligned with the names of the other Vavr's interfaces, as Function1, Function2,...

Should this interface be implemented also by Try? 

> We should unify the names and have a hidden common interface, maybe similar to Value?
I think that we could introduce a common interface, not just for Either and Validation, but also for Try and Option. This interface could be a Value2<L, R>. Or what about ForkValue<L, R> which represents the fact that a class is projected in two difference subclasses?

**Comment by danieldietrich** [comment]
For now I would not add additional interfaces. If a 3rd party app needs a common interface, it could define a functional interface on its own and just use method references to the Vavr methods.

I would just start adding overloads `peek` and `map` for the types you mentioned: Try, Option, Either and Validation.
