### ISSUE TITLE
Quadratic behavior in LinkedHashSet.union() and LinkedHashSet.addAll()

### ISSUE THREAD

**Issue by grievejia** [vavr-io/vavr#2191]
According to the [user guide](http://www.vavr.io/vavr-docs/#_performance_characteristics), `LinkedHashSet.add()` has an effective constant complexity, which implies that LinkedHashSet.addAll() and `LinkedHashSet.union()` should behave no worse than O(N). However, I run into a particular data sequence that would cause the aforementioned methods to have O(N^2) performance in vavr-0.9.2. I am not too familiar with the vavr codebase myself and I don't have too much time to look into this. Maybe it's just a really weird edge case. Still I'd like to share the data anyway if any dev is interested. 

Attached is the source code I used to generate the data sequence and the corresponding JMH codes for performance measurement. The `Test.compute()` method constructs two sequences `s0` and `s1`, which then get transformed into two `LinkedHashSet` and unioned together. Benchmarking the `LinkedHashSet.union()` or `LinkedHashSet.addAll()` method call alone for a couple of `INPUT_SIZE`s would reveal that the running time scales quadratically with the size. On the other hand, the quadratic behavior doesn't exist if I manually write a loop to add all elements from one set to another, or if I switch to `HashSet` instead.

[src.zip](https://github.com/vavr-io/vavr/files/1564031/src.zip)

**Comment by nfekete** [comment]
`LinkedHashSet.add()` and it's backing `LinkedHashMap.put()` _can_ be linear in the worst case, when you're adding the same element over and over again, since, when the element is already contained in the set/map it's doing a replace on the existing element with the new instance in both the set/map and the queue used for keeping insertion order of the elements, and the cost of the latter is linear (see `Queue.replace`).

You can easily avoid this by checking if the set/map already contains the element to be inserted, and skip insertion if you don't actually need to replace the existing instance in the set/map. While this would effectively double the set/map lookup cost part of the insertion cost for new elements, it will be mostly a cache hit for the lookup so the cost would be negligible.

**Comment by grievejia** [comment]
> when the element is already contained in the set/map it's doing a replace on the existing element with the new instance in both the set/map and the queue used for keeping insertion order of the elements

I see. Is this mentioned anywhere in the doc? The replacement behavior is quite surprising to me. Why not just refuse to add the new element if it's already contained?

Also, if what you said is the root case, then `set1.addAll(set2)` or `set1.union(set2)` should take the same time to run as `for (int i: set2) set1 = set1.add(i)`. But this doesn't seem to be the case.

**Comment by nfekete** [comment]
[JDK's `HashMap.put()`](https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#put-K-V-) is replacing as well, though [`HashSet.add()`](https://docs.oracle.com/javase/8/docs/api/java/util/HashSet.html#add-E-) doesn't, as it's using a different representation for the set over the map (JDK's map is using `(E, constant)` entries whereas vavr uses `(E, E)` hence the difference in `HashSet` behavior).

As for the runtime properties of these operations, those are what I saw without just by looking at the code, without actually measuring anything, so I might be wrong.

**Comment by grievejia** [comment]
Thanks for the response. Closing this as the quadratic behavior is expected.

**Comment by nfekete** [comment]
This might be a property worth mentioning in the documentation. Would you like to submit a pull request?

**Comment by grievejia** [comment]
I'd be glad to. Just be a few lines of additional JavaDoc on those methods, right?

**Comment by nfekete** [comment]
I'm not sure about javadoc rules for vavr, but this behavior of `LinkedHashSet.add`(`LinkedHashMap.put`) on replacing the existing instance when inserting an element that's already a member of the set (associating a new value with a key that already exists) affects both the behavior of the set(map) and it's algorithmic complexity, and it's probably worth documenting. Also, the fact than `union()` and `addAll()` are using `add()`, in case of `LinkedHashSet` may affect their algorithmic complexity, so it's probably worth at least a sentence for interested users to check the algo complexity of `add()`. What do you think @danieldietrich ?

**Comment by danieldietrich** [comment]
> What do you think @danieldietrich ?

Clarifying a specific behavior in the Javadoc is always a good idea! Please go ahead @grievejia 

I think regarding union() and addAll() we should not expose implementation details in the sense that specific methods are called under the hood. Instead we should write some notes about the effect, i.e. that the cost of replacing a single element could be linear in the worst case.

> Why not just refuse to add the new element if it's already contained?

The main reason is that object equality does not imply that the object's state is equal. For example you could define that two persons are equal, if their name is equal but if you added a person to a Map you rely on the fact that the instance **you provided** is part of the Map. That's important if there are other attributes, like a Persons age, that differ but are not considered in the equals implementation.

**Comment by grievejia** [comment]
Thanks for the reply @danieldietrich! Just a minor comment.

> The main reason is that object equality does not imply that the object's state is equal. For example you could define that two persons are equal, if their name is equal but if you added a person to a Map you rely on the fact that the instance you provided is part of the Map. That's important if there are other attributes, like a Persons age, that differ but are not considered in the equals implementation.

Then in this case I would consider that the `equals` implementation flawed: the `equals` method the container relies on should always reflect all important states of the containing object. 

But I think this philosophical question of what is considered a good `equals` implementation is not the main point here. The key problem is the inconsistency: the same problem exists in both `HashSet`(resp. `HashMap`) and `LinkedHashSet`(resp. `LinkedHashMap`), yet in one case replacement is favored over non-replacement and in other case the reverse is true.

**Comment by grievejia** [comment]
Thanks for the reply, @danieldietrich!

In addition to the Javadoc modification, I think the [user guide]() needs to be updated as well, as it specifies that `add`/`put` in `LinkedHashSet`/`LinkedHashMap` is effectively constant, which is not. I can't seem to find the user guide page in this repo, so I guess its source must be stored somewhere else.
