### ISSUE TITLE
Source artifact missing source files generated by the annotation processor

### ISSUE THREAD

**Issue by nfekete** [vavr-io/vavr#2209]
The `target/generated-sources/annotations` source folder is not added to the build source folders currently through the `build-helper-maven-plugin`.

Also, adding the above folder is not enough, because the source artifact generation is attached to the wrong lifecycle so it happens before the compilation process could actually generate those source files. See https://github.com/vavr-io/vavr/blob/master/pom.xml#L149-L150

**Comment by nfekete** [comment]
See also https://stackoverflow.com/q/48655313/2699901

**Comment by ruslansennov** [comment]
I checked the new artifacts, it seems all is OK
