### ISSUE TITLE
vavr 0.9.2: .forEach that takes a CheckedConsumer

### ISSUE THREAD

**Issue by imode69** [vavr-io/vavr#2213]
Would be convenient if the forEach method was overloaded for a CheckedConsumer or that CheckedConsumer has a default unchecked() method (both would be ideal).

Currently I'm doing

```Java
private static <T> Consumer<T> unchecked(CheckedConsumer<T> f) {
    return arg -> {
        try {
            f.accept(arg);
	} catch (Throwable e) {
            e.printStackTrace();
	}
    };
}

@Override	
public void write(ObjectDataOutput out, Stream<?> stream) throws IOException {
    stream.forEach(unchecked(o -> out.writeObject(o)));		
}
```

**Comment by danieldietrich** [comment]
Hi @imode69,
thanks for the suggestion!
All `Checked*` interfaces should have am `unchecked` method, including `CheckedConsumer`.
I'm afraid, an overload is not possible because of ambiguities on the call-site. However, the adding the `unchecked` method should be fine!
