### ISSUE TITLE
reduceLeft can throw: return option?

### ISSUE THREAD

**Issue by emmanueltouzery** [vavr-io/vavr#2225]
```
jshell> List.<String>empty().reduceLeft((x,y)->x+y)
|  java.util.NoSuchElementException thrown: reduceLeft on Nil
|        at Traversable.reduceLeft (Traversable.java:1069)
|        at (#1:1)
```

`foldLeft` is safer, since you give a default value. In an ideal world to me, vavr's reduceLeft would return an Option and never throw. But it's a relatively big api breakage. We could also add a new method reduceLeftOption, like we have headOption and so on.

**Comment by emmanueltouzery** [comment]
sorry I see reduceLeftOption already exists. too bad the option variants aren't the default though :(

**Comment by danieldietrich** [comment]
It would be even nicer to prevent impossible calls on the type level but unfortunately it is not possible (in Java).

Such as

```java
interface EmptyTraversable<T> extends Traversable<T> {

    T head();
    EmptyTraversable<T> tail();

    T avg();
    T max();
    T min();

    // ...
    
}
```

But we needed to to that for the whole collection type hierarchy:

```java
interface EmptySeq<T> extends Seq<T>, EmptyTraversable<T> {
    // ...
}
```

etc.

Vavr's take is that Java is not the right language for this kind of safety. In many cases Java itself is unsafe. We still offer API that performs well in the sense that no wrapper classes like Option are created.

**Comment by emmanueltouzery** [comment]
Maybe it's proper that both versions are present but if it was me, I would change naming to emphasize that one version is safe the other fast. Like head/headNoOption or headPresent, reduce/reduceNoOption or reducePresent...

Safe by default, fast if you need it and are aware of the caveats. But you may disagree or consider it's too late of course.

**Comment by danieldietrich** [comment]
I fully understand it. Maybe it is not the right approach for the next version of Vavr to blindly follow Scala. Maybe it would be better to eliminate unsafety whenever possible.

One of the most basic methods is Value.get(). It should return an Option instead of throwing if no value is present. This would have several implications, e.g. that Option should not have a get() method anymore.

This would have an impact on how we program. It is like in ECMAScript 6, we can't escape a Promise.

```typescript
getValueAsync() // = Promise<T>
    .then(value => ...) // = Promise<U>
    .catch(err => ...); // = Promise<V>
```

Similarly, we can't escape an Option (without providing a default value):

```java
Option.of(...)
    .map(...) // transforms value
    .forEach(...); // possibly sends a 'message' to another function
```

Sending messages would be impure. But on the other hand this is exactly what a program does at some point - performing side effects, like writing to the database, console, etc.

Yet we would be able to pull out values out of their 'context' by providing default values or 'intentionally' throwing.

Giving up unsafe methods might sound scary the first moment but it would be much more straight forward without really loosing anything.

**Comment by emmanueltouzery** [comment]
As you know i wrote the [prelude.ts](https://github.com/emmanueltouzery/prelude.ts) typescript library where I had to make these choices again. In my case I don't have an Option.get method, or, well I have it, but I called it getOrThrow (i also have Some.get and you can call it using TS type guards but it's another story).

So all I'm saying is, keep the throwing methods, but make sure it's obvious to the user that they can throw. Seq.max returning an int doesn't worry me as much: it's pretty obvious from the type that if you give it a list of Strings it can do nothing but throw (in prelude I made max take a lambda T->number always but I'm less concerned about performance). That said, a safe and fast variant for max could be List.of(1,2).transform(List::max) which would be static and accept Seq<Number> (with overloads). But it's less discoverable.

Anyway we've had a crash in prod due to an experienced developer using reduce on an empty list. We can blame the developer or java. I think choosing an explicit naming is a pragmatic solution but maybe it's too late for vavr. In any case vavr remains an awesome library!

**Comment by emmanueltouzery** [comment]
If you decide these ideas are worth a shot I'd be delighted to prepare a PR! But i'm most concerned about back compatibility.

**Comment by danieldietrich** [comment]
@emmanueltouzery I will take these ideas into account. I really appreciate that you are volunteering to bring these changes to Vavr. But I will start to ✨bootstrap✨ Vavr 1.0.0 this weekend on a branch by starting from scratch with an empty repository. This gives me the opportunity to add and document aspects of the library step-by-step and also to revisit the type level and think critically about the one or the other thing. Maybe prelude.ts can help here, too.

> we've had a crash in prod due to an experienced developer using reduce on an empty list

My goal will be to provide a solution that we are able to reason about. Thank you for your faith in Vavr!

> a safe and fast variant for max could be List.of(1,2).transform(List::max) which would be static and accept Seq<Number> (with overloads)

Yes, safety over conciseness will be the guiding principle.
