### ISSUE TITLE
Streams are not lazy enough

### ISSUE THREAD

**Issue by Raffinate** [vavr-io/vavr#2232]
Recently I've faced with an issue with Vavr Streams design. Streams are implemented in a such way that head of the stream is eager and not lazy. Most of the time it's not a big deal, but there are some cases when this behavior can produce a lot of useless calculations. 

The example I've faced with is the following:

Suppose there is a large map that maps some keys to streams of data. There is a function that accepts the map and filter it's values in a lazy manner (since the values are Streams). Since Steams are eager to the head, the filtering will be eager until first element that satisfies the predicate will be found. And that is going to be done for every element in the map. In my case it's quite common case that all values in streams can be filtered out completely, so, basically that means that this operation will not be lazy, but completely eager.

The user guide states that 

> Stream implementation is a lazy linked list. Values are computed only when needed

so it may be understood that Stream head will be computed only on read and not on steam creation. Even if the documentation explicitly states

> A Stream is composed of a head element and a lazy evaluated tail Stream

it's still not obvious why to make this collection half lazy - half eager, to make users to always keep this behavior in mind.
 
So the main question is: Is such behavior designed and fixed or it is possible to change it in the future to make streams lazy? 

P. S. If latter I could try to improve that to make Streams fully lazy and in case of success I could prepare PR.

P. P. S. Also it's just strange to have a lazy collection that calculates it's first element in eager way. I've also faced with the situation where I have to deal with errors when stream is created (in case of exception happens during head calculations) and in the place where the Stream is actually used (where other elements are calculated). This was also unexpected to have.

**Comment by valery1707** [comment]
> Suppose there is a large map that maps some keys to streams of data. There is a function that accepts the map and filter it's values in a lazy manner (since the values are Streams). Since Steams are eager to the head, the filtering will be eager until first element that satisfies the predicate will be found.

How do you plan to filter the map by value without calculating the values?
Can you give some demo code?

**Comment by danieldietrich** [comment]
@Raffinate a completely lazy structure would be nice. Before doing a full-blown PR, I would be interested in sketching the main ideas.

For a spike we could consider the following methods (without inheritance, signatures may change later):

```java
interface Stream<T> {

    // + factory methods empty(), of(T), continually(T)

    boolean isEmpty();
    T head();
    Stream<T> tail();

    <U> Stream<U> map(Function<T, U> mapper);
    <U> Stream<U> flatMap(Function<T, Stream<U>> mapper);
    Stream<T> filter(Predicate<T> predicate);

    Stream<T> take(int n);

    void forEach(Consumer<T> action);
}
```

Good tests for laziness would be:

```java
// should be true
Stream.continually(1).filter(i -> false).take(0).isEmpty();

// should be true
Stream.continually(1).flatMap(i -> Stream.empty()).take(0).isEmpty();
```

**Comment by danieldietrich** [comment]
We align to Scala instead of inventing something new. If our behavior differs from that of Scala, it probably might be a bug (and needs to be fixed in another issue). Therefore I will close this ticket.

I think there might be alternatives that are completely lazy (RxJava?), however these libs probably serve a different purpose than providing 'plain' collections.
