### ISSUE TITLE
vavr-test: logging AssertionErrors of Predicate parameters

### ISSUE THREAD

**Issue by splitcells** [vavr-io/vavr#2235]
If the Predicate Parameter of  Property.ForAll.suchThat throws an AssertionError than the following message is create:

"testSimpleOrthogonalKeysRandom: Errored after 0 passed tests in 31 ms with message: Applying predicate: null"

This message does not convey the problem and instead hides it.

**Comment by splitcells** [comment]
Only the message of a thrown exception is printed and the stack trace is omitted.

**Comment by danieldietrich** [comment]
Thank you. I think the best solution would be to re-throw exceptions that have nothing to do with the test. I consider this as a bug.

**Comment by splitcells** [comment]
From my point of view, it would be best (if possible) to even print the input variables of the Predicate
that cause the error as it might not be clear which input caused the faulty behaviour.

**Comment by danieldietrich** [comment]
@splitcells of course you are right, (unexpected) exceptions need to lead to an [Erroneous CheckResult](https://static.javadoc.io/io.vavr/vavr-test/0.9.2/io/vavr/test/CheckResult.html).

**Comment by danieldietrich** [comment]
For now I will not further invest in vavr-test and keep it as-is because JUnit 5 is the 'defacto standard' and it offers property testing.
