### ISSUE TITLE
Validation peekInvalid

### ISSUE THREAD

**Issue by Sir4ur0n** [vavr-io/vavr#2237]
Hi guys,

Is there any reason why `Validation` doesn't have a `peekInvalid` method? Just like `Either#peekLeft` or `Try#onFailure`.

This is typically useful to log when a validation fails.

Example: 
```java
    default Validation<E, T> peekInvalid(Consumer<? super E> action) {
        if (isInvalid()) {
            action.accept(getError());
        }
        return this;
    }
```

**Comment by danieldietrich** [comment]
Yes, it would make sense to add it - PR welcome!
