### ISSUE TITLE
Allow composing checked function with pure functions to create checked functions

### ISSUE THREAD

**Issue by alshain** [vavr-io/vavr#2238]
From what I understand, this should be a safe operation:

```checkedFunction.andThen(pureTransformer)```

Why not add something like this to the checked functions?

```
default <V> CheckedFunction1<T1, V> andThen(Function1<? super R, ? extends V> after) 
```

**Comment by danieldietrich** [comment]
Thank you for your suggestion. I'm afraid, that is not possible because it would raise ambiguities:

<img width="674" alt="screen shot 2018-04-07 at 22 44 51" src="https://user-images.githubusercontent.com/743833/38460196-68dda698-3ab5-11e8-9555-e4417aca41d6.png">

I suggest to use a method reference instead:

```java
<T, R, V> void test() {

    CheckedFunction1<T, R> cf = TODO();
    Function1<R, V> f = TODO();

    cf.andThen(f::apply);

}
```

I hope you don't mind if I close this issue.

**Comment by alshain** [comment]
I'm aware that I can use `::apply`.  Having to use `::apply` just because of a Java limitation makes the code more inconsistent.  I can see that for lambdas the andThen syntax is problematic, I didn't use that in my case.

Why not add a different method instead such that I'm not forced to use `::apply` just because of Java? I'm not opposed to using `String::toString` method references or whatever, but `apply` just makes it clear that functions still close to being second class citizens.

**Comment by danieldietrich** [comment]
I don't want to expand the vocabulary of Vavr, i.e. by adding `checkedFunction.andThenPure(pureTransformer)`. In fact I strive for a much simpler Vavr for the next major version. It should be aligned more to native Java, currently we build a parallel world to Java by aligning strictly to Scala.

To tell the truth, I think we do not need Function* and Tuple* at all. There are only a few use-cases within Vavr where we internally apply Function3+ or Tuple3+. Function0, Function1 and Function2 are already part of the JDK. Tuple0 is nothing. Tuple1&lt;T> is T and Tuple2 is used as Map.Entry in our lib (beside zippers). Given that, we effectively only need a pair.

The pattern matching API is neat but somehow experimental. Java will ship its own native pattern matching. Given that, we do not need Function* and Tuple*.

Take a look at the implementation - it is trivial. Almost all methods are one-liners:

<img width="762" alt="screen shot 2018-04-07 at 23 51 25" src="https://user-images.githubusercontent.com/743833/38460689-4da1ffdc-3abf-11e8-87de-da1d057a0d19.png">

**Simplicity means not doing all the things. Vavr 1.0 will be simple.**
