### ISSUE TITLE
*Function1 -> Function0 without lambda expressions

### ISSUE THREAD

**Issue by alshain** [vavr-io/vavr#2239]
It would be nice if I could convert *Function* to Function0 with partial application.

I can go from FunctionN to Function[N-1] with currying/applying.

However, there doesn't seem to be a (discoverable) option to go to Function0.

**Comment by danieldietrich** [comment]
Hi Chris,

thank you for your suggestion. May I ask what your use-case is?

**Technically it would mean applying a function to an argument without applying it :)**

More specifically, it would mean to fixate the arguments and defer the function call:

```java
Function1<T, R> f1 = TODO();
Function0<R> f0_1 = () -> f1.apply(t);
Function0<R> f0_2 = f1.deferred(t);

Function3<T1, T2, T3, R> f3 = TODO();
Function0<R> f0_3 = () -> f3.apply(t1, t2, t3);
Function0<R> f0_4 = f1.deferred(t1, t2, t3);
```

I don't think there is a real benefit of introducing a new _keyword_ (let's say `deferred`) to our _internal DSL_. The users need to take the hurdle to discover it. FP means using lambdas, which is pretty straight forward. Keep it simple!

I hope you don't mind if I close this issue.
Thanks again.

**Comment by alshain** [comment]
Hi Daniel, thanks a lot for the reply.

It's not like users wouldn't be able to use lambdas in the future. As for my use case: I use vavr in conjunction with a project on older Tomcats where I can't use lambdas inside JSPs.

Personally, I would like to see `deferred`. It allows me to transform functions more easily by applying operations on them, much in the vein of .compose, .andThen etc, it seems to be more consistent rather than having to make a lambda being the only way to do this. Also, this leads to better discoverablility and autocompletion.

On another note, curry() on Function1() being the identity seems a bit strange. Is that intentional or an artifact of the code generation?

**Comment by nfekete** [comment]
@alshain @danieldietrich Do you think `deferred()` would still be needed in case #2240 would be fixed?

**Comment by danieldietrich** [comment]
@nfekete thanks for creating the issue!
good question. now we have two alternate options:

```java
Function0<R> pf1 = f.curried().apply(t1);
Function0<R> pf2 = () -> f.apply(t1);
Function0<R> pf3 = f.deferred(t1);
```

Personally I would use the lambda. For me it is a reflex/good habit to start a Supplier (resp. Function0) with `() ->`. That is easy to remember.

**Comment by nfekete** [comment]
I would also use the lambda, but since we already have `curried()`, by making it consistent with the other `Function[2-8].curried()` methods through #2240, it could also be done without using lambdas or introducing a new API element. I believe `deferred()` is thus unnecessary.

**Comment by danieldietrich** [comment]
Yes, with #2240 we will have a consistent solution. Thank you for thinking about it!
