### ISSUE TITLE
ConsImpl and Lazy Accumulate During Stream Processing

### ISSUE THREAD

**Issue by Bill** [vavr-io/vavr#2245]
The simplest stream processing expression, involving only `iterate()`, `drop()` and `head()` seems to result in an accumulation of `Lazy` and `ConsImpl` objects even though the client code doesn't seem to be holding onto head(s).

Looking at code like this (test project is here: https://github.com/Bill/vavr-stream-test):

```java
    private static final int SIZE = (int)1E1; // twiddle this to make it arbitrarily large

    @Test
    public void simplestTest() {
        assertThat(SIZE+1, is(process(naturals(), SIZE))); // test passes but seems to accumulate objects
    }

    private static int process(final Traversable<Integer> traversable, final int size) {
        return traversable.drop(size).head();
    }

    private static Stream<Integer> naturals() {
        return Stream
                .iterate(1, i->i+1);
    }
```

If I set a breakpoint down in `Stream.drop()` it appears (from the IntelliJ memory debugger) that we accumulate a `ConsImpl` and a `Lazy` per step through the loop. I don't _think_ they are eligible for GC until `head()` is called (after `drop()` returns.)

Alas my proof-fu is weak. Do you know if this is really a problem, or am I barking up the wrong tree?

The idea for this test arose from some production code that was definitely holding onto a lot of objects. In that code we weren't `drop()`ing—we were processing every element. The problem was that our app was holding on to all the intermediate objects until the end.

**Comment by nfekete** [comment]
I'm not sure what is the expected behavior from your point of view in this case, but it might be worth pointing out, that vavr's `Stream` is not really analogous to Java's `Stream` as the former is traversable multiple time, while the latter can only be used once. Vavr's `Stream` is evaluated lazily but is cached afterwards, it's similar to a lazily constructed linked list. If you want a vavr data structure similar to JDK's `Stream` you're looking for `Iterator`.

**Comment by Bill** [comment]
Thank you @nfekete! That was exactly my problem. Redefining my "stream" functions in terms of vavr `Iterator` let me process arbitrarily long sequences without memory growth. This runs fine with `java -Xmx10m` whereas using vavr `Streams` it blows up with 10x the memory:

```java
    private static final int SIZE = (int)1E8;

    @Test
    public void simplestIteratorTest() {
        assertThat(SIZE+1, is(process(naturalsIterator(), SIZE)));
    }

    private static Iterator<Integer> naturalsIterator() {
        return Iterator.iterate(1, i-> i + 1);
    }

    private static int process(final Traversable<Integer> traversable, final int size) {
        return traversable.drop(size).head();
    }
```

Q.E.D.

That being said, I don't know what I'd want a vavr `Stream` for 🤔

**Comment by nfekete** [comment]
You'd want it to lazily calculate only once (just like a vavr `Iterator`) but then transparently store the results in a linked list that can be reused. Note that vavr's `Iterator` cannot be reused, just like normal java iterators or java Streams.

**Comment by Bill** [comment]
Inasmuch as vavr is a functional programming library, I expected vavr's `Stream` to be like a [SICP](https://mitpress.mit.edu/sites/default/files/sicp/index.html) stream or a Clojure sequence.

I am very surprised that a thing called `Iterator`, in any Java library,  is filling the role of SICP-style stream especially given the dichotomy between iterators (stateful) and SICP-style streams (immutable).

Are vavr's name choices, `Stream`/`Iterator`, coming from Scala tradition?

**Comment by nfekete** [comment]
Yes, vavr is close to Scala.

**Comment by Bill** [comment]
I have learned so much. But I still don't understand why this holds onto all the `Stream` data for so long:

```java
   final int SIZE = (int)1E8;
   assertThat(SIZE+1, is(Stream.iterate(1, i -> i + 1).drop(SIZE).head()));
```

Looking at the pertinent `Stream` methods:

```java
    static <T> Stream<T> iterate(T seed, Function<? super T, ? extends T> f) {
        Objects.requireNonNull(f, "f is null");
        return Stream.ofAll(Iterator.iterate(seed, f));
    }

    static <T> Stream<T> ofAll(Iterable<? extends T> elements) {
        Objects.requireNonNull(elements, "elements is null");
        if (elements instanceof Stream) {
            return (Stream<T>) elements;
        } else {
            return StreamFactory.create(elements.iterator());
        }
    }

```

And looking at `Stream.drop()`:

```java
    @Override
    default Stream<T> drop(int n) {
        Stream<T> stream = this;
        while (n-- > 0 && !stream.isEmpty()) {
            stream = stream.tail();
        }
        return stream;
    }
```

It seems like the `Stream` will be lazily materialized by the `tail()` calls in the `drop()` loop ✓ But what I don't see is why the old head doesn't become garbage after each iteration completes.

**Comment by nfekete** [comment]
This is just first glance:
1. you create a Stream instance with 
    ```Stream.iterate(1, i -> i + 1)```
2. you invoke `drop(SIZE)` on the previously created instance - while drop is running, the instance is still kept alive because that's the object drop was called on.
3. when 2. finishes, the original stream can be thrown away, since a new `Stream` instance is returned to call `tail()` on.

So that means while `drop()` is running, the original `Stream` instance is still alive with all the lazily evaluated values cached in the linked list.

I don't see how this could be "solved". It seems unsolvable at this moment in Java. Maybe if there was tail call elimination for tail recursive function calls and the GC would notice those instances are not needed anymore. But without that, the original `Stream` instance is on the stack until `drop()` returns and cannot be reclaimed.

**Comment by Bill** [comment]
And once again, I am surprised. `Iterator` does _not_ appear to be immutable like a SICP-style stream. Instead it is mutable, more like a Java iterator:

```java
    @Test
    public void iteratorImmutabilityTest() {
        final Iterator<Integer> sixPlus = naturalsIterator().drop(5);
        assertThat(11, is(sixPlus.drop(5).head()));
        assertThat(11, is(sixPlus.drop(5).head())); // assertion fails
    }
java.lang.AssertionError: 
Expected: is <17>
     but: was <11>
```

Somehow that first `drop(5)` mutated the object reference by `sixPlus`.

**Comment by nfekete** [comment]
I don't know about SICP-style streams, but both Java iterators and streams are mutable. Java Streams are "consumed" once you invoke a terminal operation on them and cannot be reused. Vavr Iterators are still Java iterators, only on steroids 😄

**Comment by Bill** [comment]
Thanks @danieldietrich. As I've dug deeper into this issue I have come to believe that there is no good solution to the problem of **scalable, lazy, immutable, sequence processing**, for a Java _library_…

Vavr's `Lazy` is actually the very close to the SICP-style stream/Clojure sequence I seek. But there are deeper problems beyond the fact that e.g. `drop()` is an instance method on `Stream` (as @nfekete pointed out).

You can rewrite `drop()` as a static method so it doesn't [hold onto its head](https://clojure.org/reference/lazy#_don_t_hang_onto_your_head) (`this`, in this case). That'll get you a little further, but then you'll run into the next set of problems—problems that can't be fixed without severe contortion of all your library code, and a lot of client code too…

In the Clojure community, those contortions fall under the heading "closed-over locals clearing".  Failing to aggressively clear closed-over locals will prevent the garbage collector from seeing what is properly garbage, in run-of-the-mill stream processing scenarios.

It turns out that a pillar of functional programming, recursion, is pretty easy to do without most of the time, in Java—by replacing recursion with looping. It's a little annoying, but you can start with recursive code, and the transformation to looping code is fairly straightforward. And when you're done, the result is still pretty readable. You can bundle that ugly code up into some higher-order fns that will take you very far.

What's surprising, to me at least, is that it is the garbage collection implications of laziness that present the more significant challenge. The Clojure compiler, for instance, goes to great lengths to clear closed-over locals. I've tried doing this by hand for a tiny Java test program and I haven't been able to get it right (yet). Even after I eventually figure it out, the difficulty of getting it right (for the toy case) does not bode well for it's application more generally (in a Java library).

So meh. I suppose I'm late to the party. But I was really hoping we could have scalable, lazy, immutable, sequence processing in our Java library.  It seems that you can have any two but not all three:

- scalable, lazy (not immutable): use `Iterator` and loops ✓
- scalable, immutable (not lazy): loop over `ConsImpl` ✓
- lazy, immutable (not scalable): use `Lazy`. Looping (instead of recurring) lets you be scalable with respect to stack growth, but there's nothing you can do about heap growth ✓

note: by "scalable" here I mean that neither stack nor heap growth is related to the length of the stream you're processing. Also, when I say "loop" I mean write your own loops or call higher-order fns implemented in terms of loops.

historic note: I think Rich Hickey and friends implemented aggressive closed-over local clearing before Clojure 1.0 which was released in 2009. As recently as [2013](https://dev.clojure.org/jira/browse/CLJ-1250?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#issue-tabs)-[2016](https://dev.clojure.org/jira/browse/CLJ-1744?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#issue-tabs) bugs were still being discovered and refinements were still being made to that functionality.

**Comment by nfekete** [comment]
Could you elaborate a little bit on the problem you're trying to solve as all the above is a little bit too generic for me to see what you're trying to do that it's not supported by our current libraries? I'm not sure what the correct form would be for such a discussion as it's not strictly related to the present issue, so maybe the gitter channel would be a better fit, but then, that might be cluttered by other discussions too. But it's up to you...

**Comment by Bill** [comment]
@nfekete This is idiomatic Clojure processing of lazy, long (in this case, infinite) sequences:

```
Bills-MacBook-Air:java-garbage-test Bill$ clojure -J-Xmx10m
Clojure 1.9.0
user=> (defn naturals [] (iterate inc 1))
#'user/naturals
user=> (for [n [1e3 1e4 1e5 1e6 1e7]]
  (time (first (drop n (naturals)))))
("Elapsed time: 29.09182 msecs"
"Elapsed time: 34.94448 msecs"
"Elapsed time: 113.86844 msecs"
"Elapsed time: 444.99815 msecs"
"Elapsed time: 3619.999604 msecs"
1001 10001 100001 1000001 10000001)
```

We defined a function that returns the lazy, infinite, sequence of natural numbers. Then we timed dropping the first N of them and getting the N+1th one, for various values of N from N=one thousand to N=ten million. In a Java VM with 10MB of heap, it reaches the ten-million-and-first natural number in under four seconds.

The important part is not necessarily that the sequence is infinite. It's that it is lazy and it is large, relative to the size of stack and the heap. It's important that we're able to process the sequence without overflowing either the stack or the heap.

Here is the smallest possible Maven/Java/JUnit project I was able to craft to try and attempt the same idea in Java:

https://github.com/Bill/java-garbage-test

Please see the README over there for what it is, how it behaves, how I tried to understand its behavior, and why I'm still puzzled.

**Comment by nfekete** [comment]
Maybe I understand what you want. How about this code? Is this good for your purpose?
```java
static interface VavrIterable<T> extends Iterable<T> {
    @Override
    io.vavr.collection.Iterator<T> iterator();
}

static VavrIterable<Integer> naturalsWithIterable() {
    return () -> Iterator.iterate(1, n -> n + 1);
}

@Test
public void nthTest2() {
    assertThat(naturalsWithIterable().iterator().drop(N).head(), is(N + 1));
    assertThat(naturalsWithIterable().iterator().drop(N).head(), is(N + 1));
}
```

**Comment by Bill** [comment]
If I understand that code, `drop(N)` mutates the `Iterator` resulting from `naturalsWithIterable().iterator()`.

It is perfectly possible to write lots of good software with mutable objects, and in particular (mutable) iterators. The existence proofs are numerous. But what I'm after is a sequence abstraction that is immutable, like Clojure's sequence and like Abelson & Sussman's Scheme streams.

Notice how the [tail()](https://github.com/Bill/java-garbage-test/blob/master/src/test/java/GarbageTest.java#L26) method on the `LazySeq` class I defined, is idempotent (from the caller's perspective). Contrast this with the `drop(N)` method on `Iterable`.

In this toy example, perhaps the value of immutability is not apparent. In Clojure and Scheme (immutable) sequences or streams take the place of (mutable) iterators or enumerators (like you have in Java or C++ STL or Ruby). In my opinion, the resulting code is easier to write and easier to understand with the immutable abstractions than with the mutable ones.

**Comment by Bill** [comment]
Here's a Scala worksheet implementing something very similar to what I tried in plain old Java and Java with vavr. Notice I reimplemented some of the `Stream` methods as functions so as not to hang on to the head of the stream (`this` in that case): 

```scala
import scala.collection.immutable.Stream.cons

def iterate[A](start: A, f: A => A): Stream[A] =
  cons(start, iterate(f(start), f))

def inc(n:Int) = n + 1

def naturals() =
iterate(1, inc)

def drop[T](n : Int, s : Stream[T]) : Stream[T] =
  if (n <= 0 || s.isEmpty) s
  else drop(n-1, s.tail)

def nth[T](n : Int, s : Stream[T]) =
  drop(n,s).head

def N = 1e1.toInt

drop(N,naturals()).head
nth(N, naturals())
```

By implementing `iterate()`, `drop()`, and `nth()` as functions, I see no reason why they would cause objects to be retained in memory as they iterated.

I set `N` large e.g. `1e7`, and observed significant memory growth in the JVM. That, coupled with googling about Scala and finding no mention of clearing of closed-over locals, leads me to believe that Scala does not clear closed-over locals and therefore suffers the same memory growth I see with my Java code.

I poked around a little bit but it wasn't obvious how to get at the class file the Scala compiler generated. That would be interesting.

This is pretty surprising. My impression was that Scala came from the Haskell tradition. Scala has actual syntax for call-by-name (which is used in the library definition of `cons()`) ✓ Given how important laziness is for our ability to apply "equational reasoning" it just doesn't make sense that the garbage issue hasn't been addressed.

I must be missing something.

**Comment by nfekete** [comment]
Fun fact: in your java project example `dropTest()` runs fine when run normally, but fails with `OutOfMemoryError`: _GC overhead limit exceeded_ when run in debug mode.

I'm not sure what causes the difference, probably there are some optimizations that are run in normal mode but are suppressed in debug mode.

It makes sense in the sense that with debug mode the JVM needs to keep unreferenced stack local variables alive, because a debugger might inspect them, but they are otherwise unneeded. The question, is whether there is a contractual obligation for the JVM to mark those otherwise unused stack local variables eligible for GC or not. I'm not _that_ familiar with the JVM to be able to answer this question. If there's no contractual obligation from the JVM to mark unused stack local variables eligible for GC then any kind of solution based on this behavior would be risky territory, as it would depend on unspecified JVM optimization.
