### ISSUE TITLE
vavr "with"ers instead of "update"?

### ISSUE THREAD

**Issue by cal101** [vavr-io/vavr#2250]
Hi!

I want to congratulate you to a very consistent and orthogonal library.
Great work!
One point I found a disturbing was the use of "update" for changing a bit of the data and returning
the changed object.
We are using the Immutable.org library for some time now and I found the notion of "withers"
being accepted well and finding it on a growing number of other libraries too.
The use of "update" has a mutable smell and "with" is even shorter.

Just my €0.02.

**Comment by alwins0n** [comment]
thanks for mentioning this. I recently noticed some issues like this which essentially capture one big question for the vavr future - that is: should vavr be "scala for java devs" or "a fp library for java (with lessons learned from scala)"

`update` stems from the scala world and dependent on this very fundamental question (which is possible to decide once and for all with 1.0.0) it can be changed or not - in my opinion.

I will open another issue one of these days where I will collect issues that relate to this question to bring some movement/decision for vavr 1.0.0 as I am also very interested on where the journey will go

**Comment by danieldietrich** [comment]
I’ve also thought much about changes. Where to start (and where to stop?). Why not throw collections away and use eclipse collections instead. Etc...

This leads to my decision to keep most of Vavr as-is, including naming and the general contract of aligning to Scala. Otherwise it would be another library.

I like to do it straight forward and stick to the existing philosophy. There is no true and no false. Only opinions. Changing the philosophy will confuse the users which rely on it.

**Comment by alwins0n** [comment]
exactly. if this decision is already made - it should be communicated in all the issues to avoid these discussions and I will refrain from creating an issue on this.

**Comment by danieldietrich** [comment]
In this particular case the decision is already made. And with that, aligning to Scala. We mentioned it in the contribution readme and several issues.

A discussion is good, it helps us understanding the user-needs. However, it is hard to ensure, if the user who comment issues represent the majority of users... 🤔

**Comment by alwins0n** [comment]
Is it mentioned though? There is no hint to scala on the vavr readme oder contributing.md. It says "object functional library" everywhere. Issues like this will pop up every now and then, which is good on principle, I agree, but pointless if there is some undocumented fundamental decision that prevents changes like this.

**Comment by danieldietrich** [comment]
Agreed, we should document basic design principles. Thought, it was already mentioned there...
