### ISSUE TITLE
Predicates should have composition functions

### ISSUE THREAD

**Issue by skestle** [vavr-io/vavr#2259]
The `Predicates` classes should have:

- `Predicate<R> compose(Predicate<T>, Function<R,T>)`
- `Predicate<T> of(Function<T, Boolean>)` (I'd have thought that Set would implement `Predicate<T>` myself)

Both of these work better if there were a vavr Predicate, and possibly if `Predicate<T> extends Function1<T, Boolean>` (`compose` would return `Predicate`; `andThen`, `Function1`).

I expect extending Function would quite probably mess up other usages with java typing as per #2249, but it seems there's a solution for those.

**Comment by skestle** [comment]
Rough code example:
`
Value<T> value;
Set<R> filterValues;

value.filter(filterValues.compose(T::getR));
`

**Comment by danieldietrich** [comment]
It isn't practicable to create type hierarchies of functional interfaces. In fact, it leads to ambiguities.

Inheritance does not scale very well, it is better to compose things (as you already stated). An example is #2249. Currently I work on removing Function1 and PartialFunction from the type hierarchy of Seq, Set, Map and MultiMap. They will get methods like `asFunction`, `asPartialFunction` or `asPredicate`.

**Comment by danieldietrich** [comment]
I will close this issue because we already addressed this topic and work on it in #2249.

**Comment by skestle** [comment]
I've (quickly) looked over #2249 and can't see how this ticket's primary proposition has been discussed (I could have missed it)

Set as a Predicate was an example on the second point, not really at all what this was about.

I'd just want to clarify that the `compose` function has little merit.

**Comment by skestle** [comment]
On a similar question of merit - but a bit off topic; `Function1` has `constant(R)`, but not `suppliedWith(Function0)` - should it? (I would have found it useful today)
i.e. Is it worth creating a ticket for, or is it (perhaps similarly) not useful enough.

**Comment by danieldietrich** [comment]
Hi @skestle, instead of widening the API I strive for simplifying it.
We should remove the constant function in favor of using the existing

```java
interface Function1<T1, R> {
    static <T1, R> Function1<T1, R> of(Function1<T1, R> methodReference) {
        return methodReference;
    }
}
```

Then the use-cases can be implemented like this:

```java
// = Function1.constant(1)
Function1.of(ignored -> 1);

// = Function1.suppliedWith(() -> 1)
Function1.of(ignored -> 1);
```

I will create an issue.
