### ISSUE TITLE
Add @CheckReturnValue annotations to all collection mutator methods

### ISSUE THREAD

**Issue by kennymacleod** [vavr-io/vavr#2261]
If all of the "mutator" methods in vavr's collection types were annotated with `@CheckReturnValue` from JSR305, then tools such as [ErrorProne](http://errorprone.info/bugpattern/CheckReturnValue) could detect occasions where these methods are being used incorrectly.

For example, code such as
    
    Array a = Array.empty();
    a.append("foo")

would result in a compilation error from ErrorProne because the result of `append` was not being "used". This is a great way of catching a certain class of bugs at build time, particularly when migrating code from mutable collections to vavr types.

**Comment by talios** [comment]
ErrorProne++ - oh yes!

**Comment by nfekete** [comment]
@kennymacleod this was already discussed in https://github.com/vavr-io/vavr/issues/2117

**Comment by danieldietrich** [comment]
Thanks for the suggestion.
CheckReturnValue isn't part of native Java. We do not add any 3rd party dependencies to our library (even if they are seen as some kind of pseudo-standard).
So I have to close this issue.

**Comment by kennymacleod** [comment]
CheckReturnValue doesn't need to be brought in from another library.
ErrorProne and IntelliJ will recognise the annotation name irrespective of
which package it's in, so you can define it in your own project without
adding any dependencies.

Take, for example, the one in the rxjava2 codebase.

**Comment by talios** [comment]
`CheckReturnValue` is not a run-time dependency - it's purely compile time. So I don't see an issue here really - so whilst it'll be required/downloaded/used when users of Vavr build their projects, it's doesn't incur any additionally runtime dependencies.

**Comment by danieldietrich** [comment]
We [already discussed](https://github.com/vavr-io/vavr/issues/1701#issuecomment-262732071) the use of annotations in Vavr.

**Comment by talios** [comment]
@danieldietrich Fair enough - altho, that thread seems to be purely about nullness checking, which is quite different to what this ticket was about.

**Comment by danieldietrich** [comment]
@talios this is a general Java problem I do not want to solve. Especially not using annotations.
This reminds me of removing the @GuardedBy annotation I introduced in Vavr for internal documentation of concurrency.
