### ISSUE TITLE
add a filterOrElse operation to Either

### ISSUE THREAD

**Issue by enolive** [vavr-io/vavr#2262]
as far as I see, there is no implementation of the operation mentioned above in vavr.io that either returns the right side or the specified argument as Either.left in case the predicate does not match.

The current filter implementation makes it really awkward to handle multiple filter operations as it returns an Option<Either<Left, Right>> instead of a new either.

here is a code example where I try to filter invalid output (I am aware that I could use pattern matching or the validation API instead of the filter chain :wink:). Especially the type parameters gave me some serious headaches.

```java
    static Either<String, String> calculate(int input) {
        return validate(input).right()
                              .map(FizzBuzz::calculateRight)
                              .toEither();
    }

    private static Either<String, Integer> validate(int input) {
        return Either.<String, Integer>right(input)
                .filter(i -> i > 0)
                .getOrElse(Either.left("Input should be positive"))
                .filter(i -> i <= 10000)
                .getOrElse(Either.left("Input must be less or equal 10000"));
    }
```

see also the API Docs from Scala for the definition of filterOrElse: https://www.scala-lang.org/api/current/scala/util/Either.html#filterOrElse[A1%3E:A](p:B=%3EBoolean,zero:=%3EA1):scala.util.Either[A1,B]

**Comment by danieldietrich** [comment]
Thank you, I missed that, too :)
