### ISSUE TITLE
Integer overflow: Stream.rangeClosedBy returns empty stream for big numbers and negative step

### ISSUE THREAD

**Issue by enolive** [vavr-io/vavr#2263]
due to an integer overflow effect, the operation listed above (and Stream.rangeBy as well as it reuses rangeCloseBy internally) produces an integer overflow in the iterator implementation that makes the end of the range zero. Thus the range will produce wrong values.

test cases that go wrong:

```java
assertThat(Stream.rangeBy(Integer.MAX_VALUE, 1, -1)).isNotEmpty();
assertThat(Stream.rangeClosedBy(Integer.MAX_VALUE, 1, -1)).isNotEmpty();
 ```

the problem occurs in vavr's Iterator.rangeCloseBy in line 754:

```java                    
int i = from - step;
```

as from is MAX_VALUE, i will be MIN_VALUE after adding 1

**Comment by ruslansennov** [comment]
Also there is well-known error in `Integer.signum(from - toInclusive)` which produces a wrong result in case of `from=Integer.MAX_VALUE` and `toInclusive=-666`
```java
assertThat(Stream.rangeBy(Integer.MAX_VALUE - 5, 100, -1)).isNotEmpty(); // pass
assertThat(Stream.rangeBy(Integer.MAX_VALUE - 5, -100, -1)).isNotEmpty(); // fails
```

**Comment by danieldietrich** [comment]
Thanks for reporting!

---

Of course, Scala behaves correct:

```scala
scala> (Integer.MAX_VALUE to 1 by -1).take(3).mkString(", ")
res0: String = 2147483647, 2147483646, 2147483645

scala> (Integer.MAX_VALUE until 1 by -1).take(3).mkString(", ")
res1: String = 2147483647, 2147483646, 2147483645
```

**Comment by mincong-h** [comment]
Hi all, I'm interested in this ticket and I'd like to give it a try. Would it be ok for you? My idea is to use the same overflow detection logic used by JDK 8 in [`java.lang.Math#addExact(int, int)`](https://github.com/openjdk/jdk/blob/jdk8-b120/jdk/src/share/classes/java/lang/Math.java#L776-L793) and apply it to integer, long, char and other related types.

```java
    /**
     * Returns the sum of its arguments,
     * throwing an exception if the result overflows an {@code int}.
     *
     * @param x the first value
     * @param y the second value
     * @return the result
     * @throws ArithmeticException if the result overflows an int
     * @since 1.8
     */
    public static int addExact(int x, int y) {
        int r = x + y;
        // HD 2-12 Overflow iff both arguments have the opposite sign of the result
        if (((x ^ r) & (y ^ r)) < 0) {
            throw new ArithmeticException("integer overflow");
        }
        return r;
    }
```

**Comment by danieldietrich** [comment]
Hi @mincong-h,

I'm really appreciating that you'll give it a try!

The overflow detection you mentioned is throwing an exception. Throwing is not an option for us. We think functional, the result should always be defined.

The following should yield the same results. Scala returns the right result. Vavr returns the wrong result:

```
// correct
scala> (Integer.MAX_VALUE to 1 by -1).take(3).mkString(", ")
res0: String = 2147483647, 2147483646, 2147483645

// wrong
jshell> Iterator.rangeBy(Integer.MAX_VALUE, 1, -1).take(3).mkString(", ")
$1 ==> ""
```

I think, Scala does convert the int values to long and performs some checks then. See https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/immutable/Range.scala#L84-L87

This trick allows to calculate ranges at the boundaries of Integer.

When exceeding these boundaries, even Scala does throw: https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/immutable/Range.scala#L33-L36

Can we do something equivalent?

* First we will do it for int
* After that we decide how to do it for long, char and other related types

**Comment by mincong-h** [comment]
Hi Daniel, thanks for your quick reply.

> The overflow detection you mentioned is throwing an exception. Throwing is not an option for us. We think functional, the result should always be defined.

Yes, agree with you. I didn't explain well, I only want to use the existing overflow-detection from JDK, but not the exception throwing part.

> I think, Scala does convert the int values to long and performs some checks then. See https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/immutable/Range.scala#L84-L87

I don't want to do that, because this can be a solution for integer, but what about long and big integer? It doesn't sound right for me. It must be a better solution using mathematics instead of changing type.

> Can we do something equivalent?
>
> - First we will do it for int
> - After that we decide how to do it for long, char and other related types

I feel like there will be some discussions going on... So agree with you, let me handle it for int now, then we decide how to do it for long, char and other related types. I will send a draft PR, so that we can discuss there.

By the way, I need to address what Ruslan described as well:

> Also there is well-known error in `Integer.signum(from - toInclusive)` which produces a wrong result in case of `from=Integer.MAX_VALUE` and `toInclusive=-666`
> 
> ```java
> assertThat(Stream.rangeBy(Integer.MAX_VALUE - 5, 100, -1)).isNotEmpty(); // pass
> assertThat(Stream.rangeBy(Integer.MAX_VALUE - 5, -100, -1)).isNotEmpty(); // fails
> ```
