### ISSUE TITLE
Implement Future and Promise on top of CompletableFuture

### ISSUE THREAD

**Issue by hepin1989** [vavr-io/vavr#2273]
I think implement Future and Promise on top of the native CompletableFuture will be better.

**Comment by danieldietrich** [comment]
I think it will be worse.

Please elaborate a bit on your thoughts.

**Comment by danieldietrich** [comment]
The core implementation is &lt; 400 LOC (including javadoc). All other functionality is built on top of that in a purely functional way, using composition. Given that, the surface for implementation errors is kept really narrow.

Compared to that, the CompletableFuture implementation looks like a big mess. See https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/util/concurrent/CompletableFuture.java

However, these are only internals. The main reason for implementing our own future is that we strive for being better than Java. When using a wrapper, we would be worse by definition.

I will close this issue. If we decided that our Future is should be exchanged (for any reason), I would think about removing it completely.
