### ISSUE TITLE
pattern matching: how to match multi params

### ISSUE THREAD

**Issue by TiSongWen** [vavr-io/vavr#2277]
for example by Haskell
addVectors :: (Num a) => (a, a) -> (a, a) -> (a, a)
addVectors (x1, y1) (x2, y2) = (x1 + x2, y1 + y2)

(a, a) is a tuple, and the param type is Integer.

**Comment by danieldietrich** [comment]
addVector is a function, we pattern match values. Could you please give a concrete example, using Vavr?

For examples, take a look at [our documentation](
http://www.vavr.io/vavr-docs/#_pattern_matching) or our [unit tests](
https://github.com/vavr-io/vavr/blob/42ff0a22e68c42541d50c26272b8334cfcaa3b69/vavr/src/test/java/io/vavr/MatchTest.java).

Additionally, it is possible to create Match Patterns using the compile-time annotations of the library vavr-match, utilizing an annotation processor. We do that [here](
https://github.com/vavr-io/vavr/blob/42ff0a22e68c42541d50c26272b8334cfcaa3b69/vavr/src/main/java/io/vavr/%24.java) for example.

**Comment by danieldietrich** [comment]
Please go to [our chat](http://gitter.im/vavr-io/vavr) on questions. Our Vavr community will be happy to answer quickly.
