### ISSUE TITLE
add `indexed` operation to Traversable?

### ISSUE THREAD

**Issue by hepin1989** [vavr-io/vavr#2289]
like zipWithIndex but return `Traversable<Tuple2<Integer,Object>>`

**Comment by danieldietrich** [comment]
I see no difference to zipWithIndex() other than swapped tuple elements.

We want to keep the API surface of Vavr narrow (but ‘deep’). Please use existing functionality, e.g.

```java
zipWithIndex().map(Tuple2::swap)
```

(maybe in conjunction with iterator())

or

```java
zipWithIndex((elem, idx) -> Tuple.of(idx, elem))
```

or

```java
zipWith(Iterator.from(0), (elem, idx) -> Tuple.of(elem, idx))
```

Adding another method for the same purpose does not scale well in this case. I will close the issue.

Thx for your thoughts!
