### ISSUE TITLE
java.util.stream.Collector instrances for Either#sequence Either#sequenceLeft and Try#sequence

### ISSUE THREAD

**Issue by SimY4** [vavr-io/vavr#2295]
Whenever you deal with `java.util.stream.Stream` API containing the boxed values, in order to collect results into a single boxed value with aggregated list of results you need to break the operation chain and use the static method of Either, Try, Option, etc. In example:
```
  Either<Object, Seq<String>> result = Either.sequenceRight(Stream.of(1, 2, 3)
      .map(i -> Either.right("Some result"))
      .collect(io.vavr.collection.List.collector()));
```
It would be great if Either, Try, Option, etc. exposed their collector based traversal apis like:
```
  <L, R> Collector<Either<L, R>, ?, Either<L, Seq<R>> collectorRight();

  <A> Collector<Try<A>, ?, Try<Seq<A>> collectorSuccess();
```
so the above example can be rewritten as:
```
  Either<Object, Seq<String>> result = Stream.of(1, 2, 3)
      .map(i -> Either.right("Some result"))
      .collect(Either.collectorRight());
```
Or something similar. We can even parameterize these collector factories with nester collector to specify which collection type we want to see as a result for max flexibility.
```
  <L, R, B, C> Collector<Either<L, R>, B, Either<L, C> collectorRight(Collector<R, B, C>> nested);

  <A, B, C> Collector<Try<A>, B, Try<C>> collectorSuccess(Collector<A, B, C> nested);
```
What do you think?

**Comment by danieldietrich** [comment]
Hi, thanks for the suggestion.
I think in your first example, the collect call is unnecessary:

```java
Either<Object, Seq<String>> result = Either.sequenceRight(Stream.of(1, 2, 3)
      .map(i -> Either.right("Some result"))
      .collect(io.vavr.collection.List.collector()));
```

Stream is already a Seq, so we do not need to convert it to a List.
The following is the same, am I right?

```java
Either<Object, Seq<String>> result = Either.sequenceRight(Stream.of(1, 2, 3)
      .map(i -> Either.right("Some result")));
```

Also, Either is right biased. An `Either.collect` would be sufficient. If left values need to be collected, a `map(Either::swap)` could be made.

However, currently I'm modularizing Vavr 1.0. The `vavr-control` module will have no dependency on `vavr-collection`, especially Either will not know about Seq anymore. This implies that I have to remove the sequence methods _from the vavr-control module_.

I plan to move the sequence methods to the `vavr-api` module. Namely we will have something similar to this:

```java
import static io.vavr.api.API.*;

// of type Either<Object, Seq<String>>
sequenceEither(
    Stream.of(1, 2, 3).map(i -> Either.right("Some result"))
);
```

where

```java
class API {
    static <L, R> Either<L, Seq<R>> sequenceEither(Iterable<? extends Either<? extends L, ? extends R> xs) { ... }
    static <T> Try<Seq<T>> sequenceTry(Iterable<? extends Try<? extends T>> xs) { ... }
    // ...
}
```

This is already on my radar, so I will close this issue.

**Comment by SimY4** [comment]
@danieldietrich Thanks for looking into this issue.

By `Stream` I was actually thinking of `java.util.stream.Stream` and not the vavr stream. But still, it has the same thing that you have to break out of the stream transformation chain to sequence `Either` types.

You've suggested
```
sequenceEither(
    Stream.of(1, 2, 3).map(i -> Either.right("Some result"))
);
```
Which I found very inconvenient to write. Once you realize that you're dealing with a stream of eithers you have to wrap the whole thing in a static method for conversion. 
If you have a look at how you express something similar in scala (with additional help from Scalaz or cats syntax extensions):
```
scala> import cats.implicits._
import cats.implicits._

scala> val a = List(1, 2, 3).map(Either.right(_)).sequence
a: Either[Nothing,List[Int]] = Right(List(1, 2, 3))
```
You can see that I'm appending sequence at the end of my transformation chain. And we can do exactly that in java APIs by using java util stream collectors. The API may start to look like:
```
Either<Object, Seq<String>> result = Stream.of(1, 2, 3).map(i -> Either.right("Some result")).collect(Either.sequenceRight());
```

**Comment by danieldietrich** [comment]
Yes, this is a limitation of Java‘s type system. I tried to model it the same ad in Scala, but simply spoken: it is not possible in Java.

Please take a look at these signatures:

```java
abstract class Eithet<L, R> {
    <T extends Either<L, U> & R, U> Either<L, U> sequence() { ... }
}
```

But Java can‘t express such intersection types. (Note to myself: I will try to do that in TypeScript 😅)

Other examples are flatten() on collections and so on. The only possibility to bring the types into the correct context is using static methods. Unfortunately.

**Comment by SimY4** [comment]
@danieldietrich I experimented with java.util.stream.Collector a little and I think it's quite possible.

Here's an example of Collector for Option.flatten:
```
        java.util.stream.Stream<Option<Integer>> stream = java.util.stream.Stream.of(
                Option.of(1),
                Option.none(),
                Option.of(2),
                Option.none(),
                Option.of(3)
        );

        java.util.stream.Collector<Integer, ArrayList<Integer>, List<Integer>> vavrCollector = List.collector();
        java.util.stream.Collector<Option<Integer>, ?, List<Integer>> flattenCollector = java.util.stream.Collector.of(
                vavrCollector.supplier(),
                (acc, option) -> option.forEach(a -> vavrCollector.accumulator().accept(acc, a)),
                vavrCollector.combiner(),
                vavrCollector.finisher()
        );
        
        List<Integer> flatten = stream.collect(flattenCollector);
        // List(1, 2, 3)
```
For either case it's a little bit more complex but still doable:
```
        java.util.stream.Stream<Either<Object, Integer>> stream = java.util.stream.Stream.of(
                Either.right(1),
                Either.right(2),
                Either.right(3)
        );

        java.util.stream.Collector<Integer, ArrayList<Integer>, List<Integer>> vavrCollector = List.collector();

        // unfortunately collector accumulator is an effectful action.
        // In order to mutate either we need a mutable variable.
        class Ref<A> {
            A ref;

            Ref(A ref) { this.ref = ref; }
        }


        java.util.stream.Collector<Either<Object, Integer>, ?, Either<Object, List<Integer>>> sequenceCollector = java.util.stream.Collector.of(
                () -> new Ref<>(Either.right(vavrCollector.supplier().get())),
                (ref, either) -> ref.ref = ref.ref.flatMap(arr -> either.map(ev -> {
                    vavrCollector.accumulator().accept(arr, ev);
                    return arr;
                })),
                (refL, refR) -> new Ref<>(refL.ref.flatMap(rv -> refR.ref.map(lv -> {
                    rv.addAll(lv);
                    return rv;
                }))),
                ref -> ref.ref.map(List::ofAll)
        );

        Either<Object, List<Integer>> sequence = stream.collect(sequenceCollector);
```

**Comment by danieldietrich** [comment]
Thanks!

In Vavr 1.0 we will add a `collect(Collector)` method to our collections. But we will not add specific collector implementations. `collect` is only an interoperability point towards native Java.

The Vavr way of flattening would be to add static methods to the collections:

```java
// = List(1, 2, 3)
List.flatten(List(List(1, 2), List(3)));
```
