### ISSUE TITLE
Align Vavr 1.0.0 with Scala 3.0 (?)

### ISSUE THREAD

**Issue by alwins0n** [vavr-io/vavr#2298]
Since I saw comparisons to scala 2.13 on the vavr 1.0.0 branch I was wondering if it would already make sense to commit the next release of vavr to target scala 3.

currently the progress in dotty/scala3 revolves around advanced langauge features (implicit function types etc.) so the control and collection parts probably won't move that much in API. maybe we can get ppl working on that to weigh in.

afaik developer previews for scala 3.0 should be available in 2019 - not sure what the schedule for vavr is but if it makes any sense to use dotty/scala3 as reference it could be done now.

**Comment by danieldietrich** [comment]
Yes, this makes sense. I think the scala3 collections hierarchy will be simplified. Ours will be simplified, too. I will have an eye on it.
I will close this issue because it is more a guideline than having formal acceptance criteria.
