### ISSUE TITLE
How can I use Try with a right way?

### ISSUE THREAD

**Issue by superbmilkyway** [vavr-io/vavr#2301]
I am poor about FP and I have read the docs all but I am still not sure how to use Try.

Currently my app use the RocksDb and I want to express the result of `db.put(key, value);`method.
In the service layer, I want to compose with the other Try of Result with the below the result of put method. For example, I want to call another method, only if the below put method run successfully. However, I have no idea how to return Try<Void>. Could you explain how can I do it?
If I am going wrong way, what is the proper way to handle this?

```
public Try<Void> put(byte[] key, byte[] value) {
    ...
    try {
        if (isDbOpen) {
            db.put(key, value);
            return Try.success(Void); // ??? How can I return Void?
        } else {
            return Try.failure(new IOException("RocksDB is closed."));
        }
    } catch (RocksDBException e) {
        return Try.failure(e);
    } finally {
        stateChangeLock.readLock().unlock();
    }
}
```

**Comment by danieldietrich** [comment]
The idiomatic way would be s.th. like (I've not tested it):

```java
public Try<Void> put(byte[] key, byte[] value) {
    ...
    return Try.run(() -> {
        try {
            if (!isDbOpen) throw new IOException("RocksDB is closed.");
            db.put(key, value);
        } finally {
            stateChangeLock.readLock().unlock();
        }
    });
}
```

Note: the `try {}` block is only needed because of `finally`...

**Comment by superbmilkyway** [comment]
@SimY4 @danieldietrich Thank you so much ;)
