### ISSUE TITLE
Add `isNonEmpty` to Traversable?

### ISSUE THREAD

**Issue by hepin1989** [vavr-io/vavr#2302]

**Comment by danieldietrich** [comment]
Vavr has already [Traversable.nonEmpty()](https://static.javadoc.io/io.vavr/vavr/0.9.2/io/vavr/collection/Traversable.html#nonEmpty--) which is aligned to Scala's [Traversable.nonEmpty](https://www.scala-lang.org/api/current/scala/collection/immutable/Traversable.html#nonEmpty:Boolean).
