### ISSUE TITLE
Deprecate Value.toJavaArray(Class<T>) in favor of toJavaArray(IntFunction<T[]>)

### ISSUE THREAD

**Issue by nfekete** [vavr-io/vavr#2311]
Besides `Value.toJavaArray(Class<T>)` using reflection to create the array with the correct component type, it's very clumsy when you need to create arrays of generic type. For example, given:
```java
List<Class<? extends Number>> list = List.of(1, 2f).map(Number::getClass);
```
one cannot specify the component type to satisfy the compiler type checker. So the following statement will result in a syntax error:
```java
Class<? extends Number>[] classes = list.toJavaArray(Class<? extends Number>.class);
```
And direct casting `Class.class` to the needed component type (`Class<Class<? extends Number>>` in this case) isn't possible either, so one needs to do a double cast like this:
```java
Class<? extends Number>[] classes = list.toJavaArray(
                                  (Class<Class<? extends Number>>) (Object) Class.class);
```
The proposed signature would allow for
```
Class<? extends Number>[] classes = list.toJavaArray(Class[]::new);
```
which is much more elegant and that's what the JDK Stream API is also using.

**Comment by hepin1989** [comment]
No overloaded methods for there function? like DoubleFunction?

**Comment by danieldietrich** [comment]
@hepin1989 does not make sense because `int` targets the array index. There is no use-case for other types regarding toArray conversion...

**Comment by hepin1989** [comment]
I see, I thought it does another kind of function.

**Comment by danieldietrich** [comment]
Already fixed
