### ISSUE TITLE
Add orElse method to Either that provides Left value

### ISSUE THREAD

**Issue by jlorenzen** [vavr-io/vavr#2313]
I just came across this need today and thought it would be a worthwhile suggestion.
Basically I have an `Either<Throwable, Object>` but would like to "recover" and try something else if it's a specific exception. But I need the `orElse` to provide the exception. So something like this is what I'd like:
```java
Either<Throwable, Object> obj = .....
Either<Throwable, Object> job2 = obj.orElse(this::trySomethingElse)

private Either<Throwable, Object> trySomethingElse(Throwable t) {
    if (t instance of SomeException) {
        return actuallyDoSomethingElse();
    } else {
        return Either.left(t);
    }
}
```

It's a lot like Try's `recover` methods.

What do you think?

**Comment by danieldietrich** [comment]
In Vavr 1.0 you would use a transform() for that purpose:

```java
obj.transform(this::trySthElse, r -> obj);
```

I know that the `r -> obj` part could be seen as noise but we want to reduce the API surface area. It is not worth the effort to provide syntactic sugar for a special case.

**Comment by danieldietrich** [comment]
Btw, thank you for your suggestion :))

**Comment by jlorenzen** [comment]
@danieldietrich Thanks Daniel. I'm not sure our projects are going to be able to upgrade to 1.x given how much is changing. Are you stilling planning on the major changes in 1.x and if so are there any chances some of these changes can make it back into the 0.x release?

**Comment by danieldietrich** [comment]
@jlorenzen yes, 1.0 will include many backw.incompat. changes. It is more tightly aligned to the upcoming Scala 2.13.

Currently I see no reason not to backport some of the changes - selectively. We should keep 0.x backw. compatible.
