### ISSUE TITLE
how to contribute?

### ISSUE THREAD

**Issue by 1304julian97** [vavr-io/vavr#2317]
I want to contribute in this library, how can I do?

**Comment by pivovarit** [comment]
https://github.com/vavr-io/vavr/blob/master/CONTRIBUTING.md

**Comment by 1304julian** [comment]
I have a problem, I clone the project, and I import like a gradle project, and dont compile, I use intellij and Mac OS
Thanks

**Comment by pivovarit** [comment]
Could you provide more details? what's the error message?

**Comment by danieldietrich** [comment]
Hi gents,
I think I need to switch branches again in order to make contribution possible.
The current v0.9.x needs to be master, the current master needs to be master.
Sorry for the inconvenience, will fix that until this evening.

**Comment by danieldietrich** [comment]
Done, please try it again, @1304julian
