### ISSUE TITLE
Add a convenience method to create a Stream of Characters from a String

### ISSUE THREAD

**Issue by smoyer64** [vavr-io/vavr#2326]
Useful signature:

``
Stream<Character> of(String value);
``

I have a working method for this as well as tests in a utility class at the moment.  If it's decided that this is worthwhile, assign this to me and I'll submit a PR.

**Comment by nfekete** [comment]
That, at the first iteration, would lazily create an immutable linked list wrapping `Character` objects, as `Stream` is essentially a lazily created linked list. What you're looking for is rather something like an `Iterable<Character>`. Indeed, there is something similar in vavr: `CharSeq.of(String)`

**Comment by smoyer64** [comment]
I wish I'd noticed that before! ... It works perfectly for the ``String`` processing I'm trying to do.  I'm really just getting started with Vavr so I guess I should expect a bit of that.
