### ISSUE TITLE
Update POM files to allow new tests to be written in JUnit 5 ...

### ISSUE THREAD

**Issue by smoyer64** [vavr-io/vavr#2327]
and existing tests to be gradually migrated.

Tasks:

- [ ] Change ``dependencyManagement`` to use ``junit-bom`` artifact.
- [ ] Change ``dependencies`` sections to use both ``junit-jupiter-engine`` and ``junit-vintage-engine``.
- [ ] Add ``pluginManagement`` section to configure the use of a newer ``maven-surefire-plugin``.

Related to #2326 (the tests I mention as already existing in that issue are written in JUnit 5)

**Comment by danieldietrich** [comment]
Hi, thanks for your suggestion.
Doing it for Vavr 0.9 (resp. 0.x) is out of scope.
On the Vavr 1.0 branch we [are already](https://github.com/vavr-io/vavr/blob/722ca786b620cd5be02a802d90eb87a8ae647748/build.gradle#L33-L40) on JUnit 5.
Therefore I will close this issue.
