### ISSUE TITLE
Please release vavr 1.0.0-alpha built with Java 8 targetCompatibility

### ISSUE THREAD

**Issue by yvolk** [vavr-io/vavr#2330]
@danieldietrich I'm very excited that I can introduce Vavr 1.0.0 (alpha) library to my colleagues starting at least with Try only - as a first step of "step-by-step" Functional programming education :-)
Unfortunately, existing "1.0.0-alpha-1" artifact is built at Java 11 compatibility level, which prevents the artifact's usage in our Java 8 project. Although _current_ source code in "v1.0.0" branch _is_ already fixed to be Java 8 compatible.

Please, publish next alpha release based on current source code, so we could start using it! (Inserting source code of Vavr 1.0.0 directly in our custom project looks ugly and I'm afraid that my attempt to introduce FP may be rejected based on this only...)

**Comment by danieldietrich** [comment]
Thx! I will prepare an alpha-2 release this day.

**Comment by danieldietrich** [comment]
Hi, just wanted to give you an update.

I polished the alpha-2 a bit and wanted to release it. However, I'm stuck with the net.researchgate.release plugin for Gradle. Version 2.7.0 does not allow me to perform a release based on a non-master git branch. It seems to be solved in 2.8.0, but it isn't released, yet.

**Comment by yvolk** [comment]
@danieldietrich Thank you for update. Very strange restriction...
As a workaround, you could try this: fork your own repository and make vavr 1.0 be in a master branch of _that_ repository. And release from _that_ repository?!

**Comment by danieldietrich** [comment]
Finally done.

It was already released on Bintray JCenter but I had several issues syncing the release to Maven Central. So I changed the Gradle build and release now directly to Sonatype.

For the users, this is transparent, because Maven Central is automatically synced to JCenter.

**Comment by yvolk** [comment]
Thank you, @danieldietrich 
I was able to use the new artifact, but it appeared that its artifactId changed since alpha-1
The new artifactId is "vavr", not "vavr-control" as previously. Please correct README.md
