### ISSUE TITLE
Not able to run clean test phase in master branch

### ISSUE THREAD

**Issue by alonsoir** [vavr-io/vavr#2331]
`[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Vavr Parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Vavr Parent ........................................ SUCCESS [  0.494 s]
[INFO] Vavr Match ......................................... SUCCESS [  4.814 s]
[INFO] Vavr Match Annotation Processor .................... SUCCESS [  0.683 s]
[INFO] Vavr ............................................... FAILURE [ 29.305 s]
[INFO] Vavr Benchmark ..................................... SKIPPED
[INFO] Vavr Test .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.495 s
[INFO] Finished at: 2019-01-02T12:24:51+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.4.4:script (default) on project vavr: wrap: java.lang.Exception: A NoSuchMethodError exception was thrown: scala.Predef$.refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object; -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :vavr
`

**Comment by danieldietrich** [comment]
Please try to use a different/newer Maven Version. Please see #2269
