### ISSUE TITLE
Jigsaw: Change (automatic) module names

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2341]
**Problem:**

In Vavr 0.9.3 the module names `io.vavr` and `io.vavr.match` overlap with other module names.

_Please, can someone confirm that this is an issue?_

**Suggested change:**

| Maven module | Automatic module name (0.9.3 / current) | Automatic module name (1.0.0 / next) |
| --- | --- | --- |
| vavr | io.vavr | io.vavr.core |
| vavr-match | io.vavr.match | io.vavr.match.annotation |
| vavr-match-processor | io.vavr.match | io.vavr.match.processor |
| vavr-test | io.vavr.test | io.vavr.test |

I'm not sure if we can change this from 0.9.3 to 0.10.0 or if we should postpone it to 1.0.0.

**Comment by nfekete** [comment]
Would it make sense to reflect the java module names in the maven module names as well? It might help avoid confusion. I.e.:

Maven module | Automatic module name (1.0.0 / next)
-- | --
vavr<b>-core</b> | io.vavr.core
vavr-match<b>-annotation</b> | io.vavr.match.annotation
vavr-match-processor | io.vavr.match.processor
vavr-test | io.vavr.test

**Comment by danieldietrich** [comment]
Yes, that would make sense!

**Comment by nbentoneves** [comment]
Is it possible to pick this issue? I would like to help :)

**Comment by danieldietrich** [comment]
@nbentoneves please hold your horses. It is too early, the Vavr 1.0 branch does not contain any modules, yet. Additionally, maybe vavr-test will be discontinued because there are good mainstream alternatives for property testing.

**Comment by danieldietrich** [comment]
Vavr will be one module io.vavr.

I will deprecate pattern matching (including the annotation and processor modules) in favor of the upcoming native Java pattern matching feature.

Vavr's property testing module will be discontinued in favor of popular alternatives, like junit 5 property testing.

**Comment by talios** [comment]
> Vavr's property testing module will be discontinued in favor of popular alternatives, like junit 5 property testing

That's one change I don't like - I've much preferred Vavr's property testing over any of the others on Java I've found, and not everyone uses Junit 5.

One good thing of Vavr-test was that was independent.  I see Jetbrains have their own ( https://github.com/JetBrains/jetCheck ) now as well, interesting.

**Comment by rkraneis** [comment]
Getting property testing right is hard, especially automatic shrinking. After switching from Scala to Java we needed a replacement for ScalaTest and finally settled on jqwik for ease of use, activity and especially automatic shrinking. We are still running some junit4 tests with the vintage engine, so depending on how extensively you use it, that might be an option.

**Comment by danieldietrich** [comment]
@rkraneis interesting, I hadn't the opportunity to get my hands on jqwik, yet

@talios during the last years, more and more alternatives emerged. They have a stronger focus on testing and evolve faster than we do. So I think it isn't the worst idea to take a look at what exists.

It is a strategic move to abandon property testing and focusing on the core concepts. Still, the property testing framework could be moved to a different namespace and maintained independently, if needed. But regarding property testing, there hasn't been much noise (questions) on the issue tracker. I'm in doubt it is broadly used.
