### ISSUE TITLE
Break Gradle release if Java version used for build > 8

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2358]
We can easily do this with Gradle now 💪🏼

### Question: do we need to do this at all? We already set source and target compiler flags to 1.8.

**Comment by CauchyPeano** [comment]
Good question... I was also not sure about it, so asked on StackOverflow 
https://stackoverflow.com/questions/54496735/is-there-practical-reasoning-to-enforce-jdk-version-for-build

**Comment by danieldietrich** [comment]
Out of scope. 1.0 will stay on Maven. We may move to Gradle later (I did it on the 2.0 branch).
