### ISSUE TITLE
Future reduce with executor, but this executor is never used

### ISSUE THREAD

**Issue by DungBe** [vavr-io/vavr#2375]
Future reduce with given executor! But this executor is never used. 
For example: given executor is SimpleAsyncTaskExecutor, and the returned Future instance of this method contains DEFAULT_EXECUTOR

**Comment by danieldietrich** [comment]
Well spotted, thank you! We will need to patch Future#reduce like that:

```diff
static <T> Future<T> reduce(Executor executor, Iterable<? extends Future<? extends T>> futures, BiFunction<? super T, ? super T, ? extends T> f) {
    Objects.requireNonNull(executor, "executor is null");
    Objects.requireNonNull(futures, "futures is null");
    Objects.requireNonNull(f, "f is null");
    if (!futures.iterator().hasNext()) {
        throw new NoSuchElementException("Future.reduce on empty futures");
    } else {
-       return Future.<T> sequence(futures).map(seq -> seq.reduceLeft(f));
+       return Future.<T> sequence(executor, futures).map(seq -> seq.reduceLeft(f));
    }
}
```

**Comment by DungBe** [comment]
You are welcome, I am using this libary for my project, it is very easy to use  and reduces a lot of the complexity of my code. Thank you! 
My next question now is, is there a way to give my taskExcecutor into zipWith() method?
