### ISSUE TITLE
Accept Function<Input, Output> for Try.onSuccess or Try.onFailure

### ISSUE THREAD

**Issue by artus** [vavr-io/vavr#2377]
Right now we have to do this (due to onSuccess and onFailure only accepting Consumers):

```java
Try<Boolean> resultTry = Try.success(true);

if (resultTry.isSuccess) return this.someTransformation(resultTry.get());
return someOtherTransormation(resultTry.getCause());
```

It would be nice if we could do this instead:

```java
return Try.success(true)
    .onSuccess(this::someTransformation)
    .onFailure(cause -> someOtherValue(cause));
```

What is the reason that `onSuccess` and `onFailure` only accept Consumers?

**Comment by danieldietrich** [comment]
Please use `map` / `mapTry` instead of `onSuccess`.

**Comment by artus** [comment]
Of course, the answer is so obvious and I did not think my question it through. Thank you!

**Comment by danieldietrich** [comment]
Thank you for asking!
