### ISSUE TITLE
Interest in FutureEither

### ISSUE THREAD

**Issue by castillobgr** [vavr-io/vavr#2378]
Hi Daniel! First of all, I wanna say thanks for the awesome work on Vavr. It made the development of my latest projects so much better in so many ways.

During the early days of said projects, about a year ago, I wrote a `FutureEither<L, R>` class, mimicking the Future-specific instance of Cat's `EitherT`. It has made our code much more succint, helped junior team members reason more easily about the code, and I think it has proven to be a good implementation.

I am aware of #1868, but I believe this is a fairly common pattern among Scala programmers, much more so than using `Try<Option<T>>`. Since Java has no support for something like `EitherT` (or any other transformer, for that matter), I think it would be a useful addition to Vavr. I would also like to know whether you know of other Vavr users using - or wanting to use something like - `Future<Either<L, R>>`.

Its benefits can be seen in a code snippet as short as this:

**Without FutureEither**
```java
 Future<Either<Integer, String>> fe1 = Future.successful(Either.right("hello "));
 Future<Either<Integer, String>> fe2 = Future.successful(Either.right("world!"));
 
 Future<Either<Integer, String>> result = fe1.flatMap(e1 -> fe2.map(e2 -> e1.flatMap(s1 -> e2.map(s2 -> s1 + s2))));
```

**With FutureEither**
```java
 FutureEither<Integer, String> fe1 = FutureEither.right("hello ");
 FutureEither<Integer, String> fe2 = FutureEither.right("world!");
         
 FutureEither<Integer, String> result = fe1.flatMap(s1 -> fe2.map(s2 -> s1 + s2));
```

Using `io.vavr.API.For` would make it even better, but I haven't looked into implementing `Iterable` for it yet.

I'd love to hear your thoughts on this and open a PR should you deem it useful!

**Comment by danieldietrich** [comment]
Hi @castillobgr,

thank you for using Vavr! And thank you for your suggestion.

On my journey developing Vavr 1.0 I'm focusing on reducing the API surface are. We achieve this by putting a strong focus on the Scala 2.13 API. Native Scala does not have FutureEither.

I think there are a lot of interesting topics that fit not well into the core library but could be defined on their own, in a separate library. Namely, lifting monads, monad transformers, ... all the abstractions that can be found in Scalaz, Cats, etc.

It is a strategic decision not to add these to the Vavr core library.

Beside that, I asked myself how do you plan to transform runtime errors to Left values? For example

```java
// HTTP.GET returns Either<Integer, T>, where the Integer is the HTTP return code in the error case
FutureEither.of(() -> HTTP.GET("/resource"));
```

In the example above, HTTP.GET could throw a TimeoutException or SocketException for example.

```java
var fe1 = Future.successful(Either.right("hello "));
var fe2 = Future.successful(Either.right("world!"));
var result = For(fe1, fe2).yield((e1, e2) ->
        For(e1, e2).yield((s1, s2) -> s1 + s2)
);
```

---

Implementing a new type _FutureEither&lt;...>_ is costly. I think what you _really_ want is syntactic sugar for transforming the state of _Future&lt;Either&lt;<...>>_.

It could be achieved like this:

```java
// API
<L, R1, R2> Function<BiFunction<R1, R1, R2>, Future<Either<L, R2>>> ForT(Future<Either<L, R1>> fe1, Future<Either<L, R1>> fe2) {
    return f -> For(fe1, fe2).yield((e1, e2) -> For(e1, e2).yield(f));
}

// call site
var result = ForT(fe1, fe2).apply((s1, s2) -> s1 + s2);
```

**Notes:**

* currently Vavr is missing _For(Either...)_, it will be added and _Either_ will be treated as right-biased
* above I spoilered the upcoming Vavr 1.0 syntax of For. It will return a function. The 'yield'  method will be an 'apply'  then.
* Vavr has a generic _API.For(Future&lt;T>...)_. Adding an _API.For(Future&lt;Either&lt;...>...)_ would lead to ambiguities.

I do not plan to add _ForT_ methods to the core library, it would be hard to argue against other syntactic sugar methods then. Instead it would make more sense to add an additional library on top of the core library, that adds syntactic sugar for more advanced use-cases...

I hope you understand it. It is important to keep the library as small as possible. If the feature isn't part of native Scala, it will most probably not be included in Vavr. Long term, it is the basis for Vavr's health.

**Comment by castillobgr** [comment]
Hi @danieldietrich ! Thanks for your kind response and explanation.
I totally understand and support making Vavr as light as possible (hence my curiosity about whether you'd seen other people use something similar).

Regarding your question, this wouldn't compile with my implementation of `FutureEither`
```java
FutureEither.of(() -> HTTP.GET("/resource"));
```
That's because like Cat's `EitherT[Future, L, R]`, `FutureEither` is internally a `Future<Either<L, R>>`.
So to construct it you'd need a `Future<Either<L, R>>`, or, via "convenience" functions, just an `Either`:
```java
FutureEither<String, Potato> a = FutureEither.of(Future.successful(Either.left("Whoops")));
// or
FutureEither<String, Potato> b = FutureEither.fromEither(Either.right(new Potato()));
// or, like in my examples above
FutureEither<String, Potato> c = FutureEither.left("Hello")
```
FutureEither's purpose, in our case, is to make it easier to model async domain functions, moving away from exceptions in favor of domain errors.

I hope that explains it well!

Btw, if you can point me in the right direction (docs, bugs, etc), I'd love to contribute and keep Vavr going strong!
