### ISSUE TITLE
Add API.For(Either)

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2383]
For already supports Try, Option, Future.
We also need to support Either.

**Comment by thiyagu-7** [comment]
Hi.. I would like to take a stab at this.

**Comment by danieldietrich** [comment]
Hi @thiyagu-7, sorry, I somehow missed your message.
If you are still interested in solving this issue, please go ahead :)
I will assist you on any questions!

**Comment by alexandrustana** [comment]
Hello, sorry I didn't say anything in advance, but since there was no response from @thiyagu-7  I figured I could give this a try.

**Comment by alexandrustana** [comment]
@danieldietrich, I believe this can be closed now :)

**Comment by danieldietrich** [comment]
@alexandrustana yes, thank you!

**Comment by danieldietrich** [comment]
@alexandrustana yes, thank you!
