### ISSUE TITLE
Option should not accept null

### ISSUE THREAD

**Issue by Abnaxos** [vavr-io/vavr#2397]
`Some(null)` just seems terribly wrong, "some nothing" is an oxymoron. I also don't want to wrap `Objects.requireNonNull(option.get())`. This more or less defies the reason to exist for the Option type. `Option::get()` should be guaranteed to either throw or  return something non-null.

Related to #2396. This may have been introduced for #71. Even then, `Option<Void>` should always be none.

**Comment by danieldietrich** [comment]
This question comes again from time to time. Please see also [this answer](
https://github.com/vavr-io/vavr/issues/2392#issuecomment-475939435).

I understand that it feels wrong from the intuitive view point, but it is mathematically correct regarding the monad laws and in fact also required in order to make features like for-comprehensions work on the language level.

Scala also does it:

<img width="778" alt="Screenshot 2019-03-24 at 09 44 10" src="https://user-images.githubusercontent.com/743833/54877033-ad4a7e00-4e19-11e9-82d4-ce741b12dfa2.png">

**Comment by Abnaxos** [comment]
Well, I'll stick with `java.util.Optional` then.

It's simply not worth the trouble if `Option.get()` can return null, it just makes things worse. This way, `Option` just introduces another level of tedious checks, because now, I have to check for both None/Some *and* null (and, if you're nitpicky, there's even a third level, because the option itself could be null). Not to mention the tons of false positives this causes in the IDE.

**Comment by nfekete** [comment]
@Abnaxos you can always use
```
option.flatMap(Option::of)
```
or
```
option.filter(Objects::nonNull)
```
to convert a `Some(null)` to a `None`.

**Comment by danieldietrich** [comment]
Or just convert it to Optional before pulling out the value.

![optional](https://user-images.githubusercontent.com/743833/54886734-a0667280-4e8b-11e9-928b-aa51829ed72d.gif)

**Comment by danieldietrich** [comment]
I will provide a link here to a blog post that explains [How Optional Breaks the Monad Laws and Why It Matters](https://www.sitepoint.com/how-optional-breaks-the-monad-laws-and-why-it-matters/) (by Marcello La Rocca):

<img width="767" alt="Screenshot 2019-03-24 at 23 41 22" src="https://user-images.githubusercontent.com/743833/54887039-cc372780-4e8e-11e9-81a4-2b8879546ee8.png">

Another great reading is [Why java.util.Optional is broken](https://developer.atlassian.com/blog/2015/08/optional-broken/) (by Jed Wesley-Smith).

**Comment by Abnaxos** [comment]
Sorry, I have to get back to this. The article raises some important points and some severe misbehaviours and for some time the argumentation almost convinced me.

However, both you and the author of that article assume the (in my view) wrong premise that `myOption.map(o -> null)` is legal code. Such a thing must obviously throw an NPE, I implied that. I was shocked when I read that this returns the empty Optional instead of throwing an NPE. If you want turn a Some into a None, there's flatMap(). That's so natural to me that I couldn't imagine how anyone could ever think otherwise. ;) From that POV, all the arguments against my proposal are obsolete.

So yes, there's a severe misbehaviour in Optional, that's true. But to trigger that, it's required that the programmer misbehaves first by returning null from a function. We should of course fix that in Vavr's Option: `myOption.map(o -> null)` and similar constructs must throw an NPE, obviously.

A possible compromise: Some(null) throws. An additional factory method schroedinger() provides a way to create a Some(null). Functions may map Some to Schroedinger by returning null. But Option::get() will return some nonnull or throw. There's a nullable getSchroedinger() for the Schrödinger cases.

Problem here: If you get null at some point, the stack trace will be worthless because it won't show you where the error happened. That's the whole problem about null: where the error happens and where the code fails are never the same, they can be in completely different places and times. That's why NPEs are often effectively undebuggable. And that's exactly why we want to completely eradicate null. Is it really worth to dismiss the whole point of Option, just to support some paradox use cases? And yes, "some nothing" is paradox.

**Comment by danieldietrich** [comment]
@abnaxos We align to Scala (I will add that to the contribution guidelines by time). That is the easiest way to shorten discussions and choose between different opinions. If you can show examples where VAVR does not behave like Scala, we can talk about it.
