### ISSUE TITLE
Interoperability between Vavr types and Scala types

### ISSUE THREAD

**Issue by galegofer** [vavr-io/vavr#2398]
Hello there,

This is more a rhetoric /  exploratory question that an issue or an improvement.

I was wondering if it will make sense for example to have a conversion from Vavr types to Scala ones.

Like for Example: 

vavr.Try -> scala.Try
vavr.Either -> scala.Either
vavr.Future -> scala.Future (or create vavr Future from scala ones)

I mean adding a toScalaType (or similar to the one that we have for the java ones in the case of collections.) method for example.

Does it makes sense?.

Thanks

**Comment by thadumi** [comment]
Hi, what will be the use case for a toScala() method? Vavr is already a functional library for Java which tries to follow the Scala monads. The asJava methods make sense for collections compatibility with older Java code which, for example, uses the java.util.List instead of io.vavr.collection.List.

**Comment by galegofer** [comment]
Hi,

For example, If you have a framework or if you are operating with Scala Futures in Java (which API is richer than CompletableFuture), it will be nice to be able to wrap them inside a Vavr Future, so you can operate it like usual with Vavr, same for example to convert from Vavr Future to a Scala Future, or convert from Vavr Try monad, to a Scala Try, so if you are using a project where you have a mix of Scala and Java code, it will be easier to deal with their interaction.

Also, Scala monads look ugly at Java due to the lack of Java syntax sugar, so my question is why not to allow Vavr to act as a bridge?.

**Comment by Abnaxos** [comment]
One thing is certainly important: it must still be possible to use Vavr without Scala. I'm not sure, but I think you'll get a NoClassDefFoundError if any method signatures refer to Scala classes when the Scala runtime isn't in the classpath.

Therefore, such features should be put into a separate class to keep the Scala runtime dependency optional.

**Comment by Asamsig** [comment]
This probably something that belongs in a sublibrary to bridge the gap between Vavr and Scala.

**Comment by danieldietrich** [comment]
Thank you @galegofer for the question! @Abnaxos is right, we would pull in the Scala dependency when we allow conversion to Scala types as part of the core functionality.

The right way would be to create a `vavr-scala` project that offers the required functionality **on top of VAVR**. For example, we already have something similar for Kotlin: [vavr-kotlin](https://github.com/vavr-io/vavr-kotlin)

**Comment by galegofer** [comment]
Yeah, Indeed I was thinking the same than @Asamsig , that we are going to need a different project with the Scala dependencies on it.
@danieldietrich Thanks to you for the amazing library that you did!. To be able to have Vavr like a bridge with Scala and Java will be amazing.

**Comment by domdorn** [comment]
I'm currently using this in my project, maybe it is of some help for someone.. 
https://gist.github.com/domdorn/5f4da958ed7b9ee3b12b1e2cd41aebd2

**Comment by sullis** [comment]
I am building a Scala library that maps:
- VAVR types to Scala types 
- Scala types to VAVR types

See  https://github.com/gfc-collective/gfc-vavr 
and https://github.com/gfc-collective/gfc-vavr/pull/1
