### ISSUE TITLE
ClassCastException during pattern matching

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2401]
Thx @goerge for reporting this bug on Gitter!

<img width="1218" alt="Screenshot 2019-03-31 at 19 10 00" src="https://user-images.githubusercontent.com/743833/55292269-c68a9600-53e8-11e9-8950-4ff11a4a7ae8.png">

<img width="1249" alt="Screenshot 2019-03-31 at 19 10 10" src="https://user-images.githubusercontent.com/743833/55292271-ca1e1d00-53e8-11e9-807c-2d461797082e.png">

**Comment by danieldietrich** [comment]
**Luckily the Match generics are correct.**

The pattern matcher `$(List.empty())` compares the _prototype_ instance (here: List.empty()) which the actual object that is matched ($() is of type Pattern0):

<img width="676" alt="Screenshot 2019-03-31 at 19 22 42" src="https://user-images.githubusercontent.com/743833/55292409-da36fc00-53ea-11e9-8cfc-0e9efea5e15a.png">

The error is located in the implementation of `List.Nil.equal()`

<img width="646" alt="Screenshot 2019-03-31 at 19 26 52" src="https://user-images.githubusercontent.com/743833/55292414-f5097080-53ea-11e9-8f6f-59f949cea651.png">

It uses the internal `Collections.equals()` method:

<img width="568" alt="Screenshot 2019-03-31 at 19 22 28" src="https://user-images.githubusercontent.com/743833/55292381-7dd3dc80-53ea-11e9-9fbd-687f924a4b17.png">

Which does a check _by contents_.

Therefore Match matches (because Pattern0.isDefinedAt returns equals == true), then the case is performed, then -----> 💥

**I will fix that and check all other locations which could be affected by Collections.equals!**

Many thanks! 😊

**Comment by danieldietrich** [comment]
A fix could look like this:

```diff
    static <V> boolean equals(Seq<V> source, Object object) {
        if (object == source) {
            return true;
-       } else if (source != null && object instanceof Seq) {
+       } else if (source != null && object != null && source.getClass() == object.getClass()) {
            final Seq<V> seq = (Seq<V>) object;
            return seq.size() == source.size() && areEqual(source, seq);
        } else {
            return false;
        }
    }
```

Other `Collections.equals()` overloads are also affected...

**Comment by danieldietrich** [comment]
Looks like changing the Collections.equals() implementatiosn has a bigger impact on the code-base than I thought 😅.

**Comment by goerge** [comment]
@danieldietrich I’m really impressed how fast you react on this issue. Thanks for the good work on vavr.

**Comment by danieldietrich** [comment]
Our notion of _collection_ equality is aligned to that of Scala. All collections that share the same parent type (Seq / Set / Map) are equal (by definition), if they contain the same elements (modulo order).

<img width="652" alt="Screenshot 2019-03-31 at 21 35 25" src="https://user-images.githubusercontent.com/743833/55294001-0196c480-53fd-11e9-9c8d-d4703f71819e.png">

However, I'm aware of the fact that might be unexpected to Java developers.

Changing `List.empty() == Stream.empty()` to `List.empty() != Stream.empty()` might have a big impact to users of VAVR. We can do that in VAVR 1.0.0.

But fixing pattern matching is a _must_. In order to fix this bug, I will change the implementation of Pattern0 the way, that `isDefinedAt` also checks _assignability_ in addition to _equality_.

**Comment by goerge** [comment]
I think your / vavrs / scalas notion of collection equality is right.
To be honest I found this issue by accident when using the `List.empty` to check for emptiness where `Seq::isEmpty` would have been appropriate. 
So with your mentioned fix in `isDefinedAt` already being available my naive approach would have been right.

**Comment by goerge** [comment]
@danieldietrich Wow. Thanks for the fast fix!

**Comment by goerge** [comment]
I'm not sure if the result of this fix was intended. 

The following documents the difference between "match" and "equality check":
```
  @Test
  public void no_match() {
    final Seq empty = Stream.empty();
    final Option<String> result = API.Match(empty).option(
      API.Case(API.$(List.empty()), x -> "Stream.empty() matches List.empty()")
    );

    assertThat(result).isEqualTo(none());
  }

  @Test
  public void eq() {
    final Option<String> result = Option.when(Stream.empty().equals(List.empty()), () -> "Stream.empty() equals List.empty()");

    assertThat(result).isEqualTo(some("Stream.empty() equals List.empty()"));
  }
```
I'm aware of the fact that this is not a breaking change due to the raised `ClassCastException`.
Though I doubt that this intuitive.
Is this the same behaviour in Scala?

**Comment by danieldietrich** [comment]
In fact Scala behaves the same... however, I think we should implement collection equality like it is expected by Java developers. I will think about it for VAVR 1.0

<img width="1208" alt="Screenshot 2019-04-15 at 14 21 54" src="https://user-images.githubusercontent.com/743833/56132338-02496200-5f8a-11e9-8aa9-a4cc7a1884be.png">

**Comment by chrylis** [comment]
Thanks for your work, Daniel! This bug (I think) is blocking me in 0.10.0 because it causes `$(not(instanceOf()))` to blow up every time; do you have an estimate for 0.10.1 availability?

**Comment by danieldietrich** [comment]
@chrylis I will release a backward compatible 1.0 within this or the next week.
