### ISSUE TITLE
Try#mapFailure triggering varargs warnings

### ISSUE THREAD

**Issue by chrylis** [vavr-io/vavr#2411]
I'm trying to map a potential `IOException` in my call to a business exception:

```
Try.withResources(() -> openStream(key))
    .of(is -> mapper.readValue(is, TemplateSchema.class))
    .mapFailure(
        Case($(instanceOf(IOException.class)), io -> new BadTemplateSchemaException(key, io))
    )
```

This produces a warning in ecj and Oracle javac 9.0.4 about unsafe varargs. In Eclipse: "A generic array of `API.Match.Case<? extends Throwable,? extends Throwable>` is created for a varargs parameter". The documentation here is a bit sparse, but I _think_ this is how `mapFailure` is supposed to be used, so I'm not sure whether I need to do something differently or whether there's a type gap in the Vavr declaration; does `mapFailure` need `@SafeVarargs`?

**Comment by danieldietrich** [comment]
Interesting. I will take a look later.

**Comment by chrylis** [comment]
Any update on this one? I'm trying to improve error reporting, and `mapFailure` is alarming various tooling; from what I understand, `@SafeVarargs` may be enough to fix the problem. (I notice that the method contains `@SuppressWarnings("varargs")`, which isn't actually a real suppression class, and suggests that something like `@SafeVarargs` was intended.)

**Comment by danieldietrich** [comment]
`@SafeVarargs` is not allowed on non-final instance methods, so that is not possible.

IntelliJ IDEA does not create a warning on a similar test:

<img width="800" alt="Screenshot 2019-07-05 at 00 02 02" src="https://user-images.githubusercontent.com/743833/60688864-36149380-9eb8-11e9-8958-b13e71f68bcc.png">

The java compiler is configured with `-Werror -Xlint:all`, so the build would fail (e.g. on CI), if there would be a warning.

---

Given that, and my experience with Eclipse in the past, I'm sure that **ECJ is buggy**.

**Comment by leaumar** [comment]
Would just like to add that Intellij actually does trigger the warning on uses of `mapFailure`:
![image](https://user-images.githubusercontent.com/3950300/64701532-3b3e2200-d4a9-11e9-9aea-d26f79085bfd.png)
![image](https://user-images.githubusercontent.com/3950300/64701842-d0d9b180-d4a9-11e9-8dd3-1528ee1d9e5b.png)

**Comment by bgulowaty** [comment]
I'm also experiencing this issue with intellij/JDK11 using 0.10.2.
Shouldn't this issue be considered as something that requires improvement, and therefore reported as a bug?

**Comment by danieldietrich** [comment]
It can't be improved by Vavr. IntelliJ IDEA behaves differently than javac (which does not emit a warning). So the right place would be to create a bug on the IntelliJ IDEA bug tracker.

Btw - the pattern matching API will be deprecated in favour of Java's native pattern matching.
