### ISSUE TITLE
How am I supposed to test my composed / partially applied functions

### ISSUE THREAD

**Issue by helpermethod** [vavr-io/vavr#2415]
Hi, 

new to Vavr, looks really nice so far 👍.

One thing I'm struggeling with:

How am I supposed to test my composed / partially applied functions?

Thank you,
Oliver

**Comment by danieldietrich** [comment]
Hi Oliver,

I'm not sure if I understand your question right. There is no notion for function equality. Two functions

_f: X -> Y_ and _g: X -> Y_ are equal, if _f(x) = g(x)_ for all _x &isin; X_

Partially applied functions are roughly the same as curried functions.

_f: X -> Y -> Z_ can be seen as _f: (X x Y) -> Z_

If you want to test _f_, you need to apply it to all arguments, i.e.

_f(x)(y) = z_ can be seen as _f(x, y) = z_

Currying is only some kind of syntactic sugar for binding values / deferring a computation.

**Comment by helpermethod** [comment]
Sorry, I should have made the question more clear. So with Vavr, I'm building my application by composing small functions into bigger functions. But how am I supposed to test this? In a language with top level functions I could test the small / composed functions independently. But with Java? Maybe I should extract them into static methods?

**Comment by danieldietrich** [comment]
I'm still not sure, what you mean. Could you give a code example, like

```java
// given
YourFunctionType<...> f = ...;
YourPartialAppliedFunctionType f2 = f....;

// want / expected
void test() {
    SomeType actual = <apply f2 to some parameters>; // <==== is this your question?
    SomeType expected = <fixed value>;
    someAssertionLib.assertEqual(expected, actual);
}
```

**Comment by danieldietrich** [comment]
I will close this question because it is not related to the library. It is a general question.

I suggest to prepare a concrete example / a Gist and post that question in our [Gitter channel](https://gitter.im/vavr-io/vavr).
