### ISSUE TITLE
How to migrate Try.andFinally?

### ISSUE THREAD

**Issue by daggerok** [vavr-io/vavr#2416]
Hey,

Can you pointing me where I can look what is going to be changed in 1.x release? I have get stuck with 1.0.0-alpha-2 version...

For instance seems like Try.andFinally was removed and I cannot find in Try sources how I can migrate that 0.x code:

```java
Try.run(this::inBatch)
   .andFinally(this::shutdown)
```

I don't wanna check if it was success or not, I just need to make sure everything is tear down in the end..

Thanks

---
Regards,
Maksim

**Comment by danieldietrich** [comment]
Hi Maksim,

thanks for your question. The alpha you use is incomplete and not intended to be released as 1.0. I will lift the current v0.10.0 as v1.0.0 within the next days. So you can expect a very smooth migration.

See also my Twitter [post](https://twitter.com/danieldietrich/status/1135953036034093061) regarding v1.0.0.

I hope this helps.
