### ISSUE TITLE
Why does toTry on LinearSeqs insert the head element into the Try rather than the whole collection?

### ISSUE THREAD

**Issue by chriskiehl** [vavr-io/vavr#2420]
Hey there! 

version: `vavr 0.9.0` 

Quick question about the behavior of `toTry` when called on things like `Array` and `List` in vavr. Why does it put the `head` element into the Try rather than the entire collection? 

I assumed the behavior would be the latter to satisfy cases where empty list means something bad. For instance, a filtering condition wasn't met. 

```
Try<List<Integer>> gottaBeAtLeastTen() {
    return List.of(1, 2, 3).filter(this::isGreaterThanTen).toTry(TooSmallException::new)
}
```

However, it actually grabs the head element when you call `toTry()`. So in the above example, it actually returns a `Try<Integer>` 

```
assert List.of(1,2,3).toTry() == Try.success(1)
```

Am I using it outside of what's intended? 

Thanks!

**Comment by danieldietrich** [comment]
Hey!

Because the empty collection is interpreted as Try.Failure resp. Option.None resp. Either.Left.

Conversion needs to be _somehow_ symmetric (at least for the empty case).

**Current state:**

```java
✅ List().toOption().toList() // = List()
✅ List(1).toOption().toList() // = List(1)
🤷‍♂️ List(1, 2).toOption().toList() // = List(1)
```

**What you suggest would look like:**

```java
🤷‍♂️ List().toOption().toList() // = List(List()) or List(), depending on how we define it
🤷‍♂️ List(1).toOption().toList() // = List(List(1))
🤷‍♂️ List(1, 2).toOption().toList() // = List(List(1, 2))
```
