### ISSUE TITLE
Add putTry to Map?

### ISSUE THREAD

**Issue by jarrvis** [vavr-io/vavr#2421]
Can I add 'putTry' to Map?
```java
Try<Map<K, V>> putTry(K key, CheckedFunction0<? extends V> supplier);
``` 
Just for:
(1) convenience: I can do a return in the same line as I do `putTry`
(2) more declarative: sometimes I just want to put to map if possible. Not first calculate value and then put it:
```java
myMap.putTry("key", () -> myService.getSth().getSthElse())
```
instead of:
```java
Try.of(() -> myService.getSth().getSthElse()).onSuccess(value -> myMap.put("key", value));
```

**Comment by danieldietrich** [comment]
Our strategy is to keep the API surface area small. We try to avoid adding aliases, convenience methods etc.
