### ISSUE TITLE
Fold doubt 

### ISSUE THREAD

**Issue by jabrena** [vavr-io/vavr#2422]
Hi, 

I am reviewing the fold concept and I have some doubt about the usage.

``` java
import org.junit.jupiter.api.Test;

import static io.vavr.API.List;
import static org.assertj.core.api.Assertions.assertThat;

public class FoldExamplesTest {

    @Test
    public void given_foldOperator_when_simpleCombination_then_expectedBehavioursTest() {

        //((a + b) + c)
        assertThat(List("a", "b", "c").foldLeft("", (a, b) -> a + b))
                .isEqualTo("abc");

        //a + (b + c)
        assertThat(List("a", "b", "c").foldRight("", (a, b) -> a + b))
                .isEqualTo("abc");

        //(a ^ b) ^ c
        assertThat(List(1, 2, 3).foldLeft(0d, (a, b) -> Math.pow(a, b)))
                .isEqualTo(1.0);

        //a ^ (b ^ c)
        assertThat(List(1, 2, 3).foldRight(0d, (a, b) -> Math.pow(a, b)))
                .isEqualTo("8.0");

    }

}
```` 

In the execution of this tests, I used to understand the idea about fold the following image:

![](https://pbs.twimg.com/media/D-DAIyQW4AUzh2P?format=png&name=small)

Why this execution doesn't return 1.0:

``` java
        //(1 ^ 2) ^ 3
        assertThat(List(1, 2, 3).foldLeft(0d, (a, b) -> Math.pow(a, b)))
                .isEqualTo(1.0);
```

Why this execution return 8.0:

``` java
        //1 ^ (2 ^ 3)
        assertThat(List(1, 2, 3).foldRight(0d, (a, b) -> Math.pow(a, b)))
                .isEqualTo("8.0");
``` 

Many thanks in advance

Juan Antonio

**Comment by danieldietrich** [comment]
Hi Juan Antonio,

it has been extensively tested. VAVR works exactly like Scala (which borrowed concepts from Haskell, OCaml, etc).

<img width="802" alt="Screenshot 2019-07-01 at 13 58 24" src="https://user-images.githubusercontent.com/743833/60435158-1d328680-9c09-11e9-883b-981b7505eba8.png">

<img width="802" alt="Screenshot 2019-07-01 at 14 00 16" src="https://user-images.githubusercontent.com/743833/60435180-258ac180-9c09-11e9-8e13-6c05bfa32f0a.png">

Maybe it is a numeric problem (with floating point numbers)?

However, I'm sure that the given operator  is applied in  the right order for foldLeft and foldRight. Therefore I will close the question. Of course it is still open for discussion!

**Comment by rkraneis** [comment]
0 is not a neutral element for powers (so a _problem_ with arithmetic _per se_ :trollface:): pow(0, _x_) == 0 and pow(_x_, 0) == 1`.

**Comment by jabrena** [comment]
Hi @danieldietrich, I didn't put in doubt the method execution, I wanted the know the execution logic, this is the reason of the issue. :)

```
        //a ^ (b ^ (c ^ 0))
        assertThat(List(3, 2, 1).foldRight(0d, (a, b) -> Math.pow(a, b))).isEqualTo(9.0);

        //a ^ (b ^ (c ^ 1))
        assertThat(List(1, 2, 3).foldRight(0d, (a, b) -> Math.pow(a, b))).isEqualTo(1.0);

        //a ^ (b ^ (c ^ 1))
        assertThat(List(1, 2, 3).foldRight(1d, (a, b) -> Math.pow(a, b))).isEqualTo(1.0);

        //((1 ^ a) ^ b) ^ c
        assertThat(List(1, 2, 3).foldLeft(1d, (a, b) -> Math.pow(a, b))).isEqualTo(1.0);

        //((1 ^ a) ^ b) ^ c
        assertThat(List(1, 2, 3).foldLeft(0d, (a, b) -> Math.pow(a, b))).isEqualTo(0.0);
````

@rkraneis Thanks for the comments to understand the execution.

**Comment by jabrena** [comment]
``` java
//a ^ (b ^ c))
assertThat(List(1, 2, 3).map(x -> Double.valueOf(x)).reduce((a, b)-> Math.pow(a, b))).isEqualTo(1.0);

//a ^ (b ^ c))
assertThat(List(2, 2, 3).map(x -> Double.valueOf(x)).reduce((a, b)-> Math.pow(a, b))).isEqualTo(64.0);

//a ^ (b ^ c))
assertThat(List(3, 2, 1).map(x -> Double.valueOf(x)).reduce((a, b)-> Math.pow(a, b))).isEqualTo(9.0);
```

> `Fold` takes an explicit initial value for the accumulator while `reduce` uses the first element of the input list as the initial accumulator value. This means the accumulator and therefore result type must match the list element type, whereas they can differ in fold as the accumulator is provided separately.

Now, I understood the operators. 

@danieldietrich Do you think that it is a good idea to upload a Test File with some unit tests to understand the concept. For newbie users it could be interesting in my humble opinion.

Cheers

Juan Antonio

**Comment by danieldietrich** [comment]
@jabrena Unit tests should ensure the correctness. For documentation purposes, I think it would be better to provide good Javadoc. It is more accessible to our users.

Short- to midterm we should create better documentation in general. I will set up a new web page for VAVR.
