### ISSUE TITLE
DistinctIterator eats null values

### ISSUE THREAD

**Issue by Chamedo** [vavr-io/vavr#2425]
I ran across a problem with the .distinct()-implementation on Iterator. In addition to removing duplicate elements, it also removes all null values from the input. Other distinct()-implementations (e.g. on List) do not show this behaviour.

Code:
`System.out.println(io.vavr.collection.Iterator.of((String)null).toList().distinct())`
`System.out.println(io.vavr.collection.Iterator.of((String)null).distinct().toList())`
Result:
`List(null)`
`List()`

The problem appears to be located in the implementation of DistinctIterator.hasNext() (see https://github.com/vavr-io/vavr/blob/master/vavr/src/main/java/io/vavr/collection/Iterator.java#L2146). The loop uses `next == null` to indicate that a new distinct element has not yet been found, while it may also occur when the input is actually a null element.

**Comment by danieldietrich** [comment]
Thank you for your analysis! The fix is on its way :)
