### ISSUE TITLE
Prepare Iterator for 1.0

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2431]
An Iterator isn't a collection in terms of being part of the Traversable hierarchy. In particular, an Iterator should not be Iterable.

We will change Iterator in 1.0 as follows:

* [x] fix [type hierarchy](https://github.com/vavr-io/vavr/issues/2308#issuecomment-430043877)
* [x] Deprecate AbstractIterator and remove all internal usages. next() should throw NoSuchElementException without message.

**Comment by nfekete** [comment]
> deprecate non-lazy methods that evaluate the whole Iterator, like foldRight.

I'm not familiar with Scala, but can you provide a reason why you consider providing methods consuming the remaining elements from an `Iterator` problematic and worth deprecating?

For me, `Iterator` is a better alternative to JDK's `Stream` and I would be very disappointed to see it lose useful functionality.

**Comment by danieldietrich** [comment]
Basically, an Iterator is a lazy sequence of a possibly infinite amount of elements.

If you dropRight(n) for example, you first need to navigate to the end of the Iterator. It isn't possible to do it in a lazy manner because you don't know when that last n elements are reached.

**Comment by nfekete** [comment]
I agree with `Iterator` not implementing `Traversable`.

But I'm not sure about the _lazyness_ argument. Pretty much all methods that don't return another `Iterator` are not lazy. Among those are very useful ones, that return the `headOption`, `lastOption`, `find`, `findLast`, `fold`, `reduce`, `collect`, `partition`, `span`, etc. None of them are returning a `Lazy<T>`.

Or are you talking about just those methods that return another `Iterator` _and_ cannot be implemented without consuming (possibly) the whole stream? What about `filter`, `reject`, `sliding`, `slideBy`, `grouping`, etc? They are very similar in _lazyness_ to `dropRight`, but they don't necessarily consume the whole stream. Do they need to go as well? Their memory requirement in terms of O(n) would be better (or the same in the worst case) as any other collection, but possibly much better in some cases, where the amount of original data wouldn't even fit into memory, but the amount of memory needed to cache some part of the stream would. Some of these methods would run with much much lighter memory pressure than if you'd have to use a non-lazy or lazy but memoizing collection type.

**Comment by danieldietrich** [comment]
Okay, let's keep all for now!

My vision was to align more and more to Scala because it is well thought through by a great community. However, I see that it is not a good idea to remove existing things from VAVR. I will leave that decision open for post 1.0.
