### ISSUE TITLE
Replace some lambdas to method references

### ISSUE THREAD

**Issue by strkkk** [vavr-io/vavr#2445]
Hello, 

I created a new check in checkstyle project to detect lambdas, that can be replaced with method references and run the check over vavr source code.
It reported 49 violations (replaceable lambdas) in your repo, you can see them all here https://strkkk.github.io/120/Vavr/index.html#A1

Can you take a look and provide some feedback - what cases should not be replaced and reason/thoughts for it?

I would appreciate your feedback about it.

**Comment by danieldietrich** [comment]
Hi & thanks for your interest in VAVR!

Analyzing of unit test & benchmark files isn't necessary. If I filter these out, the following remain:

* vavr-test/src/main/java/io/vavr/test/Gen.java (will be abandoned)
* vavr/src-gen/main/java/io/vavr/CheckedFunction0.java & vavr/src-gen/main/java/io/vavr/Function0.java (roughly the same, produced by the same code generator)
* vavr/src/main/java/io/vavr/collection/Tree.java

4 of 5 of the lines mentioned in your report (regarding the remaining classes above) are **false positive** findings. Only Tree.java contains a toLispString() method that can be optimized.

**Comment by danieldietrich** [comment]
**Update:** I will close this issue. After trying to replace the one and only finding it turns out that it was correct because the method takes a super-class, the lambda uses a sub-class. The compiler can't figure out a method reference:

<img width="731" alt="Screenshot 2019-07-12 at 01 22 35" src="https://user-images.githubusercontent.com/743833/61091771-b94b6180-a443-11e9-9190-fc85f2754bb2.png">

**Comment by danieldietrich** [comment]
One more note: I'm pretty satisfied with IntelliJ IDEA. It already shows me warnings, suggestions and optimizations. Additionally it offers automatic code refactorings.

`<unpopular-opinion>`
My experience in the past was that checkstyle was mostly a big PITA. It eats up developer time and leads to meta discussions, like the correct line length, how to format code etc.

The next 'logical' step, automatic code formatting, is hell on earth. Someone has a great idea and changes the code formatter. Next commit: the diff shows so many changes across the whole code base that no one is able to review the code anymore.

The code is sprinkled with checkstyle:off comments etc. Oh my gosh. I love to concentrate on business logic instead.
`</unpopular-opinion>`

**Comment by strkkk** [comment]
@danieldietrich 
Main point of the issue is a feedback for question "in what cases from ones in report we should not replace lambda with method ref and why?"
There are no false positives in report, see below.

1.
> The compiler can't figure out a method reference

Because this is method of Tree interface, it compiles
![image](https://user-images.githubusercontent.com/8901354/61111008-3a7d1580-a491-11e9-8954-cdb72a548971.png)

2. https://strkkk.github.io/120/Vavr/xref/checkstyle/contribution/checkstyle-tester/repositories/Vavr/vavr-test/src/main/java/io/vavr/test/Gen.java.html#L298
```
         return random -> iter.get().apply(random);
```
Replaced with
```
return iter.get()::apply;
```

3 and 4, they are same. https://strkkk.github.io/120/Vavr/xref/checkstyle/contribution/checkstyle-tester/repositories/Vavr/vavr/src-gen/main/java/io/vavr/Function0.java.html#L82
![image](https://user-images.githubusercontent.com/8901354/61111294-ef173700-a491-11e9-9c8a-f0acc8c6b033.png)

5. https://strkkk.github.io/120/Vavr/xref/checkstyle/contribution/checkstyle-tester/repositories/Vavr/vavr/src-gen/main/java/io/vavr/CheckedFunction0.java.html#L155
```
return (CheckedFunction0<R> & Memoized) Lazy.of(() -> Try.of(this::apply).get())::get;
```
Replaced with
```
return (CheckedFunction0<R> & Memoized) Lazy.of(Try.of(this::apply)::get)::get;
```

**Comment by danieldietrich** [comment]
Yes, in 1. the compiler can be satisfied that way.

Nonetheless, you might change semantics when replacing

```java
() -> createObject().get()
```

with

```java
createObject()::get
```

The former preserves laziness. The latter evaluates createObject() immediately because ::get is a method reference on an existing _instance_ in that case.

**Comment by strkkk** [comment]
Yes, you are correct.
Thank you.

**Comment by danieldietrich** [comment]
Your effort is a good thing. I hope you get all right - you will reach your goal!
