### ISSUE TITLE
Look into mutation testing

### ISSUE THREAD

**Issue by roookeee** [vavr-io/vavr#2453]
I see that VAVR has some pretty high test coverage (>90%) but I stumbled upon [this](https://github.com/vavr-io/vavr/commit/6a3788d8604046ad1a54c86eb6e2952237d9a8c5) commit which has [this test](https://github.com/vavr-io/vavr/blob/6a3788d8604046ad1a54c86eb6e2952237d9a8c5/vavr/src/test/java/io/vavr/collection/AbstractSeqTest.java#L1595):
```java
@Test
    public void shouldShuffleHaveSameElementsDeterministic() {
        final Seq<Integer> shuffled = of(1, 2, 3).shuffle(new Random(514662720L));
        assertThat(shuffled.indexOf(1)).isNotEqualTo(-1);
        assertThat(shuffled.indexOf(2)).isNotEqualTo(-1);
        assertThat(shuffled.indexOf(3)).isNotEqualTo(-1);
        assertThat(shuffled.indexOf(4)).isEqualTo(-1);
    }
```
Combined with the other tests of said commit there is no test that actually tests whether the shuffle is deterministic (just checking length, checking all elements are contained). Have a look at [mutation testing](https://github.com/hcoles/pitest) to fix these kind of bad tests in VAVR so that your high test coverage is more reliable

**Comment by danieldietrich** [comment]
Thanks for your suggestion. This project is a community effort. Help is welcome!

**Comment by mincong-h** [comment]
Hi @roookeee and @danieldietrich , if you don't mind, I can give it a try.

**Comment by roookeee** [comment]
Go ahead I don't mind at all :)

**Comment by mincong-h** [comment]
Done in https://github.com/vavr-io/vavr/commit/7544480410fe235c3314d6eff897a6584c340ebb

**Comment by danieldietrich** [comment]
Thx!
