### ISSUE TITLE
vavr 0.9.3 workshops

### ISSUE THREAD

**Issue by mtumilowicz** [vavr-io/vavr#2466]
Hi, I've created vavr 0.9.3 workshops: https://github.com/mtumilowicz/java11-vavr093-workshops:
* option-workshop
* try-workshop
* partial-function-lifting-workshop
* either-workshop
* pattern-matching-workshop
* validation-workshop

Popularity is quite high as many people message me about it, so maybe it would be reasonable to pin it here somewhere?

**Comment by danieldietrich** [comment]
Thx, that's awesome!
We will find some place...

**Comment by danieldietrich** [comment]
Part of the web site, therefore closing it here...
