### ISSUE TITLE
Update license file with copyright details and update POM/gradle.build with link to LICENSE file in repo

### ISSUE THREAD

**Issue by danielpmichalski** [vavr-io/vavr#2510]
Could you kindly please fill in the "Copyright [yyyy] [name of copyright owner]" section in the LICENSE file to make it an actual license, instead of a license template?

When and if done, could you also please update POM/gradle.build license's URL to point to the file on GitHub? (the URL should be something like "https://github.com/vavr-io/vavr/blob/master/LICENSE"; although, a URL to LICENSE for specific release version would be ideal).

(sorry, I have a strict legal department at the current employer)

**Comment by danieldietrich** [comment]
I think you misread it. It is the Appendix, not the actual license.

**Comment by danielpmichalski** [comment]
Oops; thanks!
