### ISSUE TITLE
Doubt about Lifting with Either

### ISSUE THREAD

**Issue by jabrena** [vavr-io/vavr#2512]
Hi,

I am reviewing the lifting options included in the functors `Function0-8` and I have the following doubt:

**Example 1:**

``` java
        Function2<Integer, Integer, Integer> sum = (first, second) -> {
            if (first < 0 || second < 0) {
                throw new IllegalArgumentException("Only positive integers are allowed");
            }
            return first + second;
        };
        Function2<Integer, Integer, Optional<Integer>> sumSafe = (i1, i2) ->
                Function2.lift(sum).apply(i1, i2).toJavaOptional();
```

In this example, I throw and exception if the parameters are not passed in the right way and
the lifting behaviour goes fine.

**Example 2:**

```  java
        Function2<Integer, Integer, Either<String, Integer>> sum = (first, second) -> {
            if (first < 0 || second < 0) {
                Either.left("Only positive integers are allowed");
            }
            return Either.right(first + second);
        };
        Function2<Integer, Integer, Optional<Integer>> sumSafe = (i1, i2) ->
                Function2.lift(sum).apply(i1, i2).toJavaOptional();
```

In the second example, I model the first Functor returning a Either.
How to lift if I have an Either returned in the first Functor?

Many thanks in advance

Juan Antonio

**Comment by nfekete** [comment]
`Either` has both `toOption` and `toOptional`, they both return `empty`/`none` when the `Either` is `Left`, or the wrapped value if the `Either` is `Right`. Isn't that what you're looking for?

**Comment by jabrena** [comment]
Hi @nfekete,

No, I would like to `not` but not throwing an Exception.

I would like to use this idea:

```java
Function2<Integer, Integer, Either<String, Integer>> sum = (first, second) -> {
            if (first < 0 || second < 0) {
                Either.left("Only positive integers are allowed");
            }
            return Either.right(first + second);
        };
        Function2<Integer, Integer, Optional<Integer>> sumSafe = (i1, i2) ->
                Function2.lift(sum).apply(i1, i2).toJavaOptional();
``` 

In the examples that I found about `lifting`, only the lifting is generated by an Exception but using `Either<T,R>` should run, because Either.left model a failure like an Exception.

Currently, the example showed previously doesn´t compile, so my question is, how to lift, if I use a Either object?

**Comment by nfekete** [comment]
`Function.lift` is for lifting a partial function into a total function (assuming it doesn't throw any exceptions). Your second example is already a total function, so there is no need to lift it. If you would `lift` it, you would end up with a `Function2` returning `Optional<Either<String,Integer>>` which is probably not what you want. Since your function is already a total function, but you seem to prefer to want to work with JDK `Optional` instead of vavr's `Either`, you just have to do the conversion. This composed `Function2` would do just that:
```java
Function2<Integer, Integer, Optional<Integer>> sumSafe = sum.andThen(Either::toJavaOptional);
```

**Comment by jabrena** [comment]
Many thanks for the explanation.
The issue was conceptual in my side.

Cheers

Juan Antonio
