### ISSUE TITLE
Is Value.forAll working properly for empty values?

### ISSUE THREAD

**Issue by kefasb** [vavr-io/vavr#2513]
```java
if (Option.none().forAll("aaa"::equals)) {
    System.out.println("YES");
} else {
    System.out.println("NO");
}

if (List.empty().forAll("aaa"::equals)) {
    System.out.println("YES");
} else {
    System.out.println("NO");
}
```
prints:
```
YES
YES
```
I expected:
```
NO
NO
```

Which is correct?

**Comment by nfekete** [comment]
Vavr is correct, as the conjunctive identity is `true`, and `forAll` is essentially a conjunction. See also [Universal quantification for the empty set](https://en.wikipedia.org/wiki/Universal_quantification#The_empty_set)
