### ISSUE TITLE
Add a reverse method to SortedMap, SortedSet, LinkedHashMap and LinkedHashSet

### ISSUE THREAD

**Issue by DanielGronau** [vavr-io/vavr#2514]
Reversing the order of entries in `SortedMap` and `SortedSet` implementations, as well as in `LinkedHashMap` and `LinkedHashSet,` is a useful operation, and is kind of awkward to do manually, especially for the maps (please correct me if there is an easy way I overlooked).

Therefore, I suggest to add a reverse() method to these classes.

**Comment by FuncGuy** [comment]
@danieldietrich if this feature is approved then i will work on this.

**Comment by danieldietrich** [comment]
@DanielGronau yes, that makes absolutely sense!

@FuncGuy thanks for volunteering! Please go ahead!

**Comment by danieldietrich** [comment]
Closed, see [this comment](https://github.com/vavr-io/vavr/pull/2548#issuecomment-570800126).
