### ISSUE TITLE
Vector.ofAll(someListView) shouldn't preform a linear copy.

### ISSUE THREAD

**Issue by tconnard** [vavr-io/vavr#2516]
Vector.ofAll at the moment performs a linear copy when given a ListView of a Vector.
It should be able to retrive the delegate and return that.

**Comment by danieldietrich** [comment]
You mean `ofAll(Iterable)` needs to perform a check, if the given `Iterable` is already of type `Vector` and return that?

```java
// modulo generics
static <T> Vector<T> ofAll(Iterable<T> iterable) {
    if (iterable instanceof Vector) {
        return (Vector<T>) iterable; // O(1)
    } else {
        return ...; // O(n)
    }
}
```

That's already the case. Please give a code example.

<img width="588" alt="Screenshot 2019-11-22 at 08 33 03" src="https://user-images.githubusercontent.com/743833/69406671-df8ee100-0d02-11ea-99ad-0ead70d98a2c.png">

**Hint:** we will not augment our implementation with an additional delegate logic. The implementation should be always the same. The construction logic is encapsulated in static factory methods.

**Comment by tconnard** [comment]
I would like to be able to receive a Vector from a JavaConverters.ListView<T, Vector<T>> after a round trip though code that expects a java.util.List without a linear copy.

**Comment by danieldietrich** [comment]
Thanks for clarifying it!

That should be possible

* `io.vavr.collection.JavaConverters.ListView` and
* `ListView#getDelegate()`

are package private.

We can use additional `instanceof` checks, casts to `ListView` and return `getDelegate()` **if** the delegate is of the current collection type.

We should do that for all types that implement `Seq`, namely:

* [ ] `Array`
* [ ] `CharSeq`
* [ ] `List`
* [ ] `Queue`
* [ ] `Stream`
* [ ] `Vector`

**Comment by mincong-h** [comment]
Hi @danieldietrich , I would like to work on this issue. Is it OK for you?

**Comment by danieldietrich** [comment]
@mincong-h sorry for the late answer, I currently suffer the 'too-many-unread-emails' syndrome. I will consolidate the remaining issues targeted to 1.0.0. The release will happen before end of this year. I will see if there are issues that can be marked with 'help wanted' :)

Many thanks for your helping hand!
