### ISSUE TITLE
Add removeX methods on Tuple

### ISSUE THREAD

**Issue by lpraud** [vavr-io/vavr#2553]
It would be interesting to have remove methods on tuple to drop a value and convert the tuple to the inferior type, ie :

Tuple2<String, Integer> tuple2 = Tuple.of("1", 2);
Tuple1<Integer> tuple1 = tuple2.drop1();

It would allow chaining of drop and concat.

Thank you for your amazing work.

**Comment by danieldietrich** [comment]
Thank you for the kind words :)

I like the idea!

Regarding the naming, the collections use `drop(n)` to remove the first `n` head elements. The `Seq` interface (which is similar to `Tuple`) has `remove(Object)` and `removeAt(int)`. However, we used `removeAt` in order to avoid ambiguities with `remove`.

Because the is no risk of having these kind of ambiguities, I would use the shorted `remove1` instead of `removeAt1` in the case of Tuples.

**Comment by lpraud** [comment]
@danieldietrich I can submit a Pull request about this feature, if you allow me

**Comment by agrison** [comment]
I saw your tweet this morning and thought it was a good shot to contribute to this library I'm using daily.
I've got it covered here this morning: https://github.com/agrison/vavr/commit/4e888fcdc27b68abe1a48f0e54c9a6a2e1a03961

**Comment by danieldietrich** [comment]
I guess starting a racing duel [on Twitter]() wasn't a good idea, now we have a race condition...

I will review the @lpraud's [PR]() now. It already has tests implemented.......

Thank you so much @agrison for getting your hands on this issue!

Thank you @lpraud for creating the PR.

\- Daniel

**Comment by agrison** [comment]
Tests were also implemented in my commit ;)

I thought no one wanted to do it since the issue was open 7 days ago

**Comment by danieldietrich** [comment]
Oh nooo, blame on me. Sorry!

I'm currently solving one of the last issues and then I will release Vavr 1.0 !! It will be a release that polishes 0.10.x and prepares post 1.0 efforts. There's much more to come after that!

**Comment by danieldietrich** [comment]
Solved with #2555

**Comment by agrison** [comment]
No big deal, no big deal, @lpraud wanted the feature in the first place, it's fair he can provide the solution if he's able to do it and has done it already ;-)

Cheers

**Comment by lpraud** [comment]
> No big deal, no big deal, @lpraud wanted the feature in the first place, it's fair he can provide the solution if he's able to do it and has done it already ;-)
> 
> Cheers

Thanks, didn't wanted to  pre-empt your work. I also wanted to try working with the code generator.
