### ISSUE TITLE
Allow pattern matching as replacement for if-else chain

### ISSUE THREAD

**Issue by johanhaleby** [vavr-io/vavr#2554]
First of all I'm sorry if this has been discussed before but I haven't found anything similar when searching through the issues.

In Kotlin it's possible to the `when` expression in a way that closely relates to the `Match` API in Vavr:

```kotlin
val myInstance = ...
val something = when(myInstance) {
     is X -> "is X"
     is Y -> "is Y"
}
```

But you can also do this:

```kotlin
val text = when {
    x.isOdd() -> "x is odd"
    x.isEven() -> "x is even"
    else -> "x is funny"
}
```

I'd like something similar to the second `when` example in Vavr. I.e.:

```java
String text = Match(
    Case(x::isOdd, () -> "x is odd"),
    Case(x::isEven, () -> "x is even"),
    Case(Something::isSomething, () -> "Something"),
    Case($(), () -> "x is funny")
);
```

Does this makes sense? Does it already work somehow?

**Comment by goerge** [comment]
Not sure, if I got you right, but given
```
jshell> class Int {
   ...> boolean even() { return true; }
   ...> boolean odd() {return false; }
   ...> }
|  modified class Int
```

This works:
```
jshell> Match(new Int()).of(
   ...> Case($(Int::even), () -> "even"),
   ...> Case($(Int::odd), () -> "odd"),
   ...> Case($(), () -> "funny")
   ...> )
$8 ==> "even"
```

**Comment by johanhaleby** [comment]
@goerge Thanks for your response.

I don't think I expressed my self clearly enough, sorry. What I'm after is a "generic" version of Match that only takes predicates. Here's the example again:

```java
String text = Match(
    Case(x::isOdd, () -> "x is odd"),
    Case(x::isEven, () -> "x is even"),
    Case(Something::isSomething, () -> "Something"),
    Case($(), () -> "x is funny")
);
```

The important part in the example is `Case(Something::isSomething, () -> "Something")`, it doesn't have to be an int. Let's change the example a bit:

```java
String myString = "hello";
int myInt = 3;
Customer c = new Customer(..);

String text = Match(
    Case(() -> myString.length() > 2, () -> "myString is greater than 2"),
    Case(() -> myInt < 100, () -> "myInt is less than 100"),
    Case(() -> c.name.startsWith("John"), () -> "Customer name starts with John"),
    Case($(), () -> "No match")
);
```

I.e. all cases takes predicates but they are not bound to any specific "type" (i.e. `Match(c).of(..)` is bound to the "Customer" type).

Does this makes sense?

**Comment by goerge** [comment]
Ok. Got you now. Afaik this is not possible as `Match` needs a value which is than passed to the pattern of `Case`.

A hack would be something like
```
jshell> Match(new Object()).of(
   ...> Case($(x -> "12".length() == 2), () -> "string greater 2"),
   ...> Case($(), "no match")
   ...> )
$4 ==> "string greater 2"
```

**Comment by johanhaleby** [comment]
Yes that would work, but I think it's a bit ugly imho. I can of course wrap the initialization part (`Match(new Object())`) in my own method to hide it, but I would've hoped that it would be supported by the API. I don't suppose this is something that you would consider adding to the API or is the use case too slim?

**Comment by johanhaleby** [comment]
I actually have another example of where I do something similar in Haskell:

```haskell
addClubMember clubState personId
  | currentNumberOfClubMembers >= 4 = Left $ MaximumNumberClubMembersAlreadyReached currentNumberOfClubMembers
  | isClubMember clubState personId = Left $ PersonAlreadyMemberOfClub personId
  | otherwise =  Right $ ...
```

If I port this to Java and is using my proposed `Match` API then this would read something like:

```java
public Either<AddClubMemberFailed, clubState> addClubMember(ClubState clubState, PersonId personId) {
	return Match(
		Case(() -> currentNumberOfClubMembers(state) >= 4, () -> Either.left(new MaximumNumberClubMembersAlreadyReached(state.currentNumberOfClubMembers()))),
		Case(() -> isClubMember(state, personId), () -> Either.left(new PersonAlreadyMemberOfClub(personId))),
		Case($(), Either.right(..))
	);
}
```

In this simple case I could of course refactor it but the purpose of the example is to show that something similar works in other languages.

**Comment by danieldietrich** [comment]
Hi & thanks for your suggestion.

In fact we once had that API (beside other syntactic sugar) in the early days but we struggled with ambiguities. Therefore we decided to only accept Pattern* as first parameter.

Regarding the future of Vavr, the Match API will be deprecated at some point in favor of the upcoming pattern matching / object deconstruction feature of Java.

I'm aware that Java's switch will have less features. But Vavr's Match has also drawbacks. For example we are create several new instances when calling a Match expression, which puts unnecessary pressure on the GC and the CPU.

For these reasons I will close this issue. Please use the API @goerge suggested.

**Comment by johanhaleby** [comment]
@danieldietrich Thanks for your reply and thorough explanation.
