### ISSUE TITLE
Update URL in repository description

### ISSUE THREAD

**Issue by whirlwin** [vavr-io/vavr#2560]
The URL in the repository description uses HTTP, but should use HTTPS.

**Comment by danieldietrich** [comment]
Thanks for the hint.

The old one http://vavr.io redirects to https://www.vavr.io.

I changed it to the new one https://www.vavr.io. Please note that https://vavr.io does not work. I think it somehow has to do with my provider. I did not buy a SSL certificate there.

**Comment by nfekete** [comment]
You've got a let's encrypt certificate for `www.vavr.io`, which you could probably create for free for `vavr.io` as well, maybe a combined one for `vavr.io` + `www.vavr.io`. I'm not sure about what certificates Let's encrypt provides, but maybe even `vavr.io` + `*.vavr.io` would be possible.

As for why `http://vavr.io` works but `https://vavr.io` doesn't, that's because your DNS provider serves a redirect when `http://vavr.io` is accessed, but it doesn't provide the same thing on https protocol. You could work around this by assigning the 4 IP addresses of github pages directly to A records for `vavr.io` in your DNS settings.

```
» host vavr.io
vavr.io has address 217.70.184.38
vavr.io mail is handled by 10 spool.mail.gandi.net.
vavr.io mail is handled by 50 fb.mail.gandi.net.
» host 217.70.184.38
38.184.70.217.in-addr.arpa domain name pointer webredir.vip.gandi.net.
```
```
» host www.vavr.io
www.vavr.io is an alias for vavr-io.github.io.
vavr-io.github.io has address 185.199.108.153
vavr-io.github.io has address 185.199.110.153
vavr-io.github.io has address 185.199.109.153
vavr-io.github.io has address 185.199.111.153
```
```
» HEAD -E http://vavr.io
HEAD http://vavr.io
...
301 Moved Permanently
...
Location: http://www.vavr.io
...
HEAD http://www.vavr.io
...
301 Moved Permanently
...
Location: https://www.vavr.io/
Server: GitHub.com
...
HEAD https://www.vavr.io/
200 OK
...
```

**Comment by danieldietrich** [comment]
Nándor, thank you for your thoughts!

> You've got a let's encrypt certificate for `www.vavr.io`

I'm not aware of that. Currently, the site is hosted on GitHub. Maybe the certificate is owned by GitHub.

Maybe I will move the site to somewhere else midterm, probably to our sponsor http://clever-cloud.com/

Meanwhile I could test your suggestion regarding the A records.

May I ask which HEAD tool you use? Mine says (on a Mac):

```shell
$ HEAD -E http://vavr.io
HEAD: illegal option -- E
usage: head [-n lines | -c bytes] [file ...]

$ HEAD http://vavr.io
HEAD: http://vavr.io: No such file or directory
```

**Comment by danieldietrich** [comment]
I reopen this ticket in order to solve the certificate issue.

**Comment by nfekete** [comment]
My guess is that GitHub obtains a certificate from Let's Encrypt in an automated way on your behalf.

> > You've got a let's encrypt certificate for `www.vavr.io`
> I'm not aware of that. Currently, the site is hosted on GitHub. Maybe the certificate is owned by GitHub.
You can use this command to get certificate info:
```
» openssl s_client -connect www.vavr.io:443
CONNECTED(00000005)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = www.vavr.io
verify return:1
---
Certificate chain
 0 s:CN = www.vavr.io
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
...
```

> May I ask which HEAD tool you use? Mine says (on a Mac):
I use Ubuntu 18.04.3 LTS on Windows Subsystem For Linux. The package containing `HEAD` is
```
» apt-file search `where HEAD`
libwww-perl: /usr/bin/HEAD
```
Your `HEAD` seems to be the same as `head`. It appears that the HFS+ filesystem MacOS uses by default is case insensitive.
You could use  `curl` as well:
```
» curl --head http://vavr.io
HTTP/1.1 301 Moved Permanently
...
Location: http://www.vavr.io
...
```
GitHub Blog page regarding partnership with Let's Encrypt: https://github.blog/2018-05-01-github-pages-custom-domains-https/

Here's some info regarding custom domains on GitHub Pages: https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

Interestingly, my DNS registrar (Namecheap) allows for CNAME records for the root of the domain (example.com), but I'm not sure about other providers and might be against the RFC too. Here's an article about the issue: https://github.blog/2018-05-01-github-pages-custom-domains-https/

Your registrar might support flattening CNAME chains for the root of your domain through the use of virtual records like ALIAS/ANAME/(virtual)CNAME. That would add the benefit that you won't have to update the A records whenever GitHub changes the IP addresses for their CDN. Your mileage may vary, you'll need to test it out.

**Comment by danieldietrich** [comment]
Done.
