### ISSUE TITLE
Backport #2519 to 0.10.3

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2568]
See #2519

**Comment by mincong-h** [comment]
Hello @danieldietrich , I can handle this backport. However, there is no maintenance branch on v0.10, could you create one? Without it, I cannot send a pull-request... The backport is ready here: https://github.com/mincong-h/vavr/tree/v0.10. You can also compare the changes with v0.10.2 here: https://github.com/vavr-io/vavr/compare/vavr-io:v0.10.2...mincong-h:v0.10?expand=1

**Comment by danieldietrich** [comment]
Hi mincong-h, thanks for your work, it really helps! 😊
I've created the v0.10 maintenance branch: https://github.com/vavr-io/vavr/tree/v0.10

**Comment by mincong-h** [comment]
Thanks @danieldietrich ! PR sent
