### ISSUE TITLE
Try#getOrElse marked deprecated by Eclipse

### ISSUE THREAD

**Issue by oliviercailloux** [vavr-io/vavr#2574]
Using `io.vavr:vavr:1.0.0-alpha-3` in an Eclipse Maven project, `myTry.getOrElse(…);` (where `myTry` is of type `Try<Something>`) is marked as deprecated by Eclipse. The source code does not indicate getOrElse as being deprecated, however. Switching to `io.vavr:vavr:1.0.0-alpha-2` solves the problem.

I suspect either that the compiled code marks `getOrElse` as deprecated and the source and compiled code do not match in version `1.0.0-alpha-3`, or that Eclipse bugs for some reasons (but I have never seen anything similar). Can you have a look?

**Comment by oliviercailloux** [comment]
Possibly related to #2450?

**Comment by danieldietrich** [comment]
There are a lot of deprecations in the current source - too many. That makes no sense. It confuses new users who haver breaking builds on compiler warnings.

Don't think too much about it. The alpha versions should not be used. There is almost all missing in these versions. I will release a fresh version of Vavr with 1.0. It will not contain any deprecations.
