### ISSUE TITLE
Add Seq.getOption(int) and Seq.getOrElse(int, T)

### ISSUE THREAD

**Issue by emmanueltouzery** [vavr-io/vavr#2584]
Hi, would a PR adding Traversable.getOption be accepted? It would return `Option<T>` when getting a certain index instead of `T`.

 In fact it could be argued that this should be the default and [from what I can tell](https://stackoverflow.com/questions/4981689/get-item-in-the-list-in-scala), that's what scala does.

 Currently we're forced to do things like:

```java
final Option<RideInfo> rideOne = recentRidesFromNewerToOlder.headOption();
final Option<RideInfo> rideTwo = recentRidesFromNewerToOlder.length() >= 2 ? Option.of(recentRidesFromNewerToOlder.get(1)) : Option.none();
```

**Comment by danieldietrich** [comment]
Hi Emmanuel,

great idea! It would make sense to add it to Seq:

* Scala: [Seq.apply(Int)](https://www.scala-lang.org/api/current/scala/collection/immutable/IndexedSeq.html#apply(i:Int):A)
* Vavr: [Seq.get(Int)](https://javadoc.io/static/io.vavr/vavr/0.10.2/io/vavr/collection/Seq.html#get-int-)

**Comment by danieldietrich** [comment]
Maybe we should also add `getOrElse(int index, T defaultValue)` to `Seq<T>`. Map also has `getOrElse(K key, V defaultValue)`. It would save us one Option instance.

**Comment by emmanueltouzery** [comment]
ok i'll add both
