### ISSUE TITLE
document and perhaps improve Try.withResources API

### ISSUE THREAD

**Issue by xenoterracide** [vavr-io/vavr#2586]
https://stackoverflow.com/questions/61737446/opencsv-header-is-missing-required-fields-found

turns out `Try.withResources` was wrong so this is really 2 feature requests

1. Document Try.withResources here https://www.vavr.io/vavr-docs/
2. Improve API, I think what I'd really like to write, if possible
```java
            .map( f -> Try.withResources( () -> new FileReader(f) )
                    .map(CsvToBeanBuilder::new)
                    .map(b -> b.withType(AlgorithmVerification.class) )
                    .map(CsvToBeanBuilder::build)
                    .mapThrows(CsvToBean::parse)
                    .getOrElseThrow((throwable) -> new RuntimeException(f.getName(), throwable))
                )
```

**Comment by nfekete** [comment]
@xenoterracide could you please elaborate what you would like to see? I find it hard to figure out what you are missing just by looking at your stackoverflow question and answer. Could you describe it in clear english accompanied with a self-contained example?

**Comment by danieldietrich** [comment]
I regret that I introduced `Try.withResources` it is syntactic sugar that does not scale very well. Providing an internal DSL adds unnecessary ballast to the CPU and memory footprint.

Therefore Try.withResources will be removed in VAVR 1.0. Here is the migration path:

### VAVR 0.10.x

```java
Try<Void> action = Try.withResources(
    () -> new ZipFile(zipFileName)),
    () -> Files.newBufferedWriter(outputFilePath, charset)
).of((zf, writer) -> {
    ...
    return null;
});
```

### VAVR 1.0

```java
var action = Try.run(() -> {
    try (
        var zf = new ZipFile(zipFileName));
        var writer = Files.newBufferedWriter(outputFilePath, charset)
    ) {
        ...
    }
});
```

I don't think we loose anything by removing the `withResources` overloads. The opposite is true.

Here, the benefit of `Try` over `try/catch` is that an exceptional state is treated as value, which can be further transformed. It is an idiomatic and safe way to cope with errors in an application.

**Comment by xenoterracide** [comment]
```
var action = Try.run(() -> {
    try (
        var zf = new ZipFile(zipFileName));
        var writer = Files.newBufferedWriter(outputFilePath, charset)
    ) {
        ...
    }
});```

wouldn't this just leave the Closable (auto closable? I forget) item unclosed? I guess what I'd expect is some way to say this thing needs closing later, close it when I reach a terminal state in the chain.

**Comment by danieldietrich** [comment]
The _native try/catch_ part is a try with resources block that autocloses.

![try](https://user-images.githubusercontent.com/743833/82106461-6b694f00-9721-11ea-90ce-9653ceb103fe.png)

**Comment by xenoterracide** [comment]
I missed the parens in my reading, oops..

**Comment by danieldietrich** [comment]
Thanks for asking!

> 1. Document Try.withResources here https://www.vavr.io/vavr-docs/

A new documentation is part of my post 1.0-release strategy. This  will  be  handled in a different issue.

> 2. Improve API, I think what I'd really like to write, if possible

The `Try.withResources` overloads will be removed. The idiomatic way to express your example about is this:

```java
.map( f -> Try.of(() -> {
    try (var fr = new FileReader(f)) {
        return  new CsvToBeanBuilder(fr)
            .withType(AlgorithmVerification.class)
            .build()
            .parse();
    }
}))
.getOrElseThrow(err -> new RuntimeException(f.getName(), err))
```

This way  you create only one Try instance instead of 1..5 (depending on the internal state).

Personally, I would not throw a new RuntimeException at the end. The purpose of `Try` is to handle error state directly. Normally, you would  call `fold` or `onSuccess` resp. `onFailure` at some point.

I hope that helps. Thank you for your question, I will close this issue now and handle the documentation task somewhere else.
