### ISSUE TITLE
Fix Gradle 7.0 deprecations

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2589]
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead.

The testCompile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the testImplementation configuration instead.

**Comment by sleepytomcat** [comment]
There's a pull request which covers _part_ of this issue, here https://github.com/vavr-io/vavr/pull/2597

**Comment by danieldietrich** [comment]
See #2644
