### ISSUE TITLE
Seq/Map withDefault should return Seq/Map class instead of Function1

### ISSUE THREAD

**Issue by texasbruce** [vavr-io/vavr#2592]
`withDeafult` method should not be deprecated/removed because it provides benefits that getOrDefault cannot provide. 

The most important one being, it builds the default value into the map itself, as part of the map's definition, and the default value can reference a local value at definition site (could be a variable in a different scope), as opposed to `getOrDefault` which needs to provide the default value everywhere it gets called, and cannot reference local value at definition site.

Instead of returning `Function1`, we can return a wrapper class of itself. E.g. `Map::withDefault` can return a `Map` wrapped itself as underlying object, and all calls to map/flatMap just get directed to the underlying object. An example is Scala's implementation of withDefault here: https://github.com/scala/scala/blob/706ef1b291134a5e5bce2275df2c222261f73451/src/library/scala/collection/immutable/Map.scala#L176

**Comment by texasbruce** [comment]
This is related to issue https://github.com/vavr-io/vavr/issues/1194 and PR https://github.com/vavr-io/vavr/pull/2590

**Comment by danieldietrich** [comment]
As I stated [here](https://github.com/vavr-io/vavr/issues/1194#issuecomment-629715646), I see no big value of that feature. The opposite is true. There I described why it is unsafe.

I'm in doubt that it is widely used. What are your concrete use-cases? Are the workarounds I mentioned in the PR above not working for you?

**Comment by texasbruce** [comment]
`withDefault` is actually used all over our code base. 

`getOrElse` requires the default value to be accessible at call site. It's common to have a manager class creating a Map , set a default value, and pass it to the worker classes. The worker class has no access to the default value due to encapsulation.

**Comment by texasbruce** [comment]
@danieldietrich `withDefault` is actually used all over our code base.

`getOrElse` requires the default value to be accessible at call site. It's common to have a manager class creating a Map , set a default value, and pass it to the worker classes. The worker class has no access to the default value due to encapsulation. Plus you will have to repeatedly pass the default value to `getOrElse` everywhere.

**Comment by danieldietrich** [comment]
This would be your migration path:

```java
void manager() {
  Map<K, V> map = createMap();
  // 👇
  // Function<K, V> f = map.withDefault(_v_);
  Function<K, V> f = k -> map.getOrElse(k, _v_);
  // ☝️
  worker(f);
}

void worker(Function<K, V> f) {
  f.apply(_k_);
}
```

**Comment by danieldietrich** [comment]
I will close this question, withDefault is (currently) out of scope for us.
