### ISSUE TITLE
Add a version of toMap that accepts a mergeFunction

### ISSUE THREAD

**Issue by ventuno** [vavr-io/vavr#2593]
Java's [`Collectors.toMap`](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#toMap-java.util.function.Function-java.util.function.Function-java.util.function.BinaryOperator-) has a version which takes together with a `keyMapper` and a `valueMapper` a `mergeFunction` which is used to handle collisions between multiple elements mapping to the same key.

Here's an example:
```Java
Seq<Tuple2<String, Integer>> s = Vector.of(Tuple.of("a",2), Tuple.of("a",55), Tuple.of("a",3), Tuple.of("b",2));

Map<String, List<Integer>> javaMap = s.toJavaList()
  .stream()
  .collect(Collectors.toMap(
    Tuple2::_1,
    t -> List.of(t._2),
    (l1,l2) -> l1.appendAll(l2)));

assertThat(javaMap.get("a").size()).isEqualTo(3);
assertThat(javaMap.get("b").size()).isEqualTo(1);
```

The way we can achieve this by in `vavr` currently:
```Java
Map<String, Seq<Integer>> m = s.groupBy(Tuple2::_1)
  .mapValues(seq -> seq.map(Tuple2::_2).toVector());

assertThat(m.get("a").get().size()).isEqualTo(3);
assertThat(m.get("b").get().size()).isEqualTo(1);
```

This is fine, but not necessarily intuitive, especially for someone coming from Java APIs.
Thoughts on introducing a `toMap` method to `Seq` that similarly to `Collectors.toMap` takes a `mergeFunction` to handle collisions?

This version of `toMap` could just be syntactic sugar on top of `groupBy(...).mapValues(...)` which means that `mergeFunction` doesn't need to be a `BinaryOperator` like in Java, but a just a function which takes a `Seq<V>` and returns their merged value.

**Comment by danieldietrich** [comment]
Hi!
we could add the following function:

```java
// modulo generics
toMap(Function<T, K> keyMapper, Function<T, V> valueMapper, BiFunction<V, V, V> merge)
// or
toMap(Function<T, K> keyMapper, Function<T, V> valueMapper, BinaryOperator<V> merge)
```

**Note:** You can omit `.toVector()` in your example above because `seq` is a `Vector`.

```java
var m = s.groupBy(Tuple2::_1).mapValues(seq -> seq.map(Tuple2::_2));
```

**Comment by ventuno** [comment]
Thanks @danieldietrich I have a sample implementation at https://github.com/vavr-io/vavr/pull/2595 for a 
```Java
toMap(Function<T, K> keyMapper, Function<T, V> valueMapper, Function<Seq<V>, V> mergeFunction)
```
I like it better than Java's `BinaryOperator` because that means that the `mergeFunction` is called multiple times, while we have the option to simply call it once with a list of colliding values. Let me know what you think, more than happy to change as I may not be seeing the full picture here.

**Comment by danieldietrich** [comment]
Hi @ventuno,

thank you, that sounds great!

Please change your PR the following way:

1. I see your point in using a `Function<Seq<V>, V>` but I think it isn't necessarily more performant. Creating the `Seq` comes also at a cost, which might be higher than just multiple function calls. I also think that a BiFunction (resp. a BinaryOperator) cover more general use-cases, like merging collections etc. Therefore I would love to see the following signature:
    ```java
    Map<K, V> toMap(
            Function<? super T, ? extends K> keyMapper,
            Function<? super T, ? extends V> valueMapper,
            BiFunction<? super V, ? super V, ? extends V> merge)
    ```
2. Please place the implementation in `Traversable`. Currently, I'm working on a PR that partitions the conversion methods into single-valued and multi-valued and accordingly moves them to controls and collections. Therefore you don't need to bother about single-valued types.

**Comment by ventuno** [comment]
Thanks @danieldietrich! I revised my implementation based on your comment. I'm having trouble getting the compiler to agree with me when I use `? extends K`/`? extends V` so I could probably use your input on that. Other than that, I hope this is a step in the right direction :-).

**Comment by danieldietrich** [comment]
@ventuno Thank you! If you have still problems compiling your generic bounds then give me a hint, I will take a look!

**Comment by ventuno** [comment]
Thanks @danieldietrich, finally managed to get it to compile by passing the right type witnesses.

Should I also write the version of `toMap` that accepts a `Function<? super T, ? extends Tuple2<? extends K, ? extends V>> f` and the merge function?
