### ISSUE TITLE
Is there a way to specify the PRNG that `shuffle` uses?

### ISSUE THREAD

**Issue by noel-yap** [vavr-io/vavr#2606]
If `shuffle` isn't using Mersenne Twister, I would like to tell it to do so. Better would be to specify one instance of the PRNG per class. If there's no way to do this, can one be made?

**Comment by danieldietrich** [comment]
You need to implement an appropriate version of [java.util.Random](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html).

Under the hood, we call [java.util.Collections#shuffle](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#shuffle-java.util.List-java.util.Random-)

This is our API all `Seq` types provide:

![Screenshot 2020-07-06 at 23 30 48](https://user-images.githubusercontent.com/743833/86648675-5c946f80-bfe1-11ea-8473-c676f3fb8095.png)

commons-math3 provides a [MersenneTwister](https://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/random/MersenneTwister.html) implementation. You will need to subclass java.util.Random and wrap the MersenneTwister somehow.

We do not plan to provide an own implementation of a Mersenne Twister Random class.

I hope this answers you question!
