### ISSUE TITLE
How do you use Option.of(value) to achieve this?

### ISSUE THREAD

**Issue by nitishborade** [vavr-io/vavr#2617]
Hi,

Thank you for this library, however, I am unable to get my way around with Option.of(value) to achieve something like this.

```
if(list != null && !list.empty()) {
    log.info("Nothing to process")
} else {
    try {
        process1(list)
        afterProcess1DoProcess2()
        saveProcessedData(list)
    } catch(Exception e) {
        throw new MyException("Error processing", e)
    }
}
```

The code with Option I have written as

```
Option.of(valueList)
                .filter(list -> list.isEmpty())
                .toTry()
                .andThen(list -> process1(list))
                .onSuccess(list -> log.info("Success Processing 1"))
                .onFailure(e -> log.error("Failure Processing 1"))
                .andThen(list -> afterProcess1DoProcess2())
                .onSuccess(list  -> log.info("Success Processing 2"))
                .onFailure(e -> log.error("Failure Processing 2"))
                .andThen(list -> saveProcessedData())
                .onSuccess(list -> log.info("Success Saving Data"))
                .onFailure(e -> log.error("Failure Saving Data"))
                .getOrElseThrow(e -> new MyException("Failed to process and save data", e));
```

This work if the list in Option.of(list) is not null and not empty. But, how can I perform something with the above chain to also include doing something if the list is null or empty, as simple as like just `log.info("Nothing to process")`

If I use `onEmpty()`, this however executes the rest of the chain as well, whereas I would just like to return after `onEmpty()`
```
Option(valueList)
                .onEmpty("Nothing to process")
                .toTry()
                .andThen(list -> process1(list))
                .onSuccess(list -> log.info("Success Processing 1"))
                .onFailure(e -> log.error("Failure Processing 1"))
                ...
                ...

```
Any help will be immensely appreciated.

**Comment by nfekete** [comment]
I suggest you try [stackoverflow](https://stackoverflow.com/questions/tagged/vavr) or the [gitter channel](https://gitter.im/vavr-io/vavr) with this question. I recommend stackoverflow because–if your question is generic enough–it might benefit others too. Issue tracker is for issues.

**Comment by danieldietrich** [comment]
Thx! I will close it
