### ISSUE TITLE
Suggestion: Consumer0...Consumer8

### ISSUE THREAD

**Issue by Monniasza** [vavr-io/vavr#2621]
I'd like to have a consumer with more than 2 inputs, to handle 3D iteration.

Example:
```
Consumer3<Integer, Integer, Integer> cons = (x, y, z) -> {System.out.println("X: "+x+", Y: "+y+", Z: "z);};
for(int i = 0; i < 10; i++){
  for(int j = 0; j < 10; j++){
    for(int k = 0; k < 10; k++){
      cons.accept(x, y, z);
    }
  }
}
```

**Comment by danieldietrich** [comment]
I think the had them in an early stage of the library but removed them. Our strategy is to wait for primitive generics. Then we could use `Function3<T, U, V, void>` instead of `Consumer<T, U, V>`. I hope you understand!

**Comment by Monniasza** [comment]
Since I can't post bugs or feature requests on OpenJDK, it is only solution available now.

**Comment by danieldietrich** [comment]
You don't need to post that on OpenJDK, there already exists the [JEP 218: Generics over Primitive Types](https://openjdk.java.net/jeps/218). It hasn't received an update for years and the effort is declared as XL, so I don't expect it to come to Java within the next few years.

I'm not a big fan of functions of high arity. I suggest to use the more idiomatic Java way by creating proper data objects:

```java
Consumer<MyDataObject> foo = (data) -> {/* perform side effect */}

// Java 15 record but could also an old-school Java class
public record MyDataObject(String bar, int baz, double qux) {}
```

That way you even do not need to rely on Vavr.

**Comment by Monniasza** [comment]
I use Java 8, because i can't get AdoptOpenJDK 15 with HotSpot or OpenJ9 to work, so I prefer objects with all fields public.
