### ISSUE TITLE
New control model of monadic.

### ISSUE THREAD

**Issue by kevinten10** [vavr-io/vavr#2625]
### Now we have `Option` and `Either`

`Option` is a monadic container type which represents an optional value.

`Either` represents a value of two possible types.

### But this is not enough

If you want to express the third type(e.g. unknown), you may not be able to express it directly. 
In fact, unknown is a return type that meets expectations, especially in an asynchronous environment.

Whether to consider introducing a new semantic expression mode under `io.vavr.control`?

#### A function, there are _numeric_, _logical_, _instruction_ and _other_ types

Can the above types of function patterns be modeled.

### E.g

`LogicalResult` means success, failure, unknown (for _logical functions_)

`ProcessResult` represents the successful return value, the failed return value and the payload when unknown (expanded unknown semantics to `Either`)

----

**I have provided a prototype implementation, please refer to #2624 , Hope to discuss it.**

**Comment by danieldietrich** [comment]
Hi @kevinten10,

this is the Vavr core library. Our goal is to tightly align to Scala. We keep the API surface area relatively small by being relatively selective in which features we support.

> , especially in an asynchronous environment.

What's wrong with achieving the 'unknown' state by composing `Option` and `Either`, like `Option<Either<L, R>>` or `Option<Try<T>>`? We (and Scala?) do it already in the context of `Future`, where the computation is _unknown_ until the async result arrives. Why don't you use `Future`?

**Comment by kevinten10** [comment]
Of course we can use the combination of `Option<Either<L, R>>`.

But as I mentioned in #2623.

I hope to provide a higher level API.

For example, Provide a high-level expression of `Option<Either>`, because it is very complicated to use it in actual development.

The entry point of #2625 is to provide `return value object` APIs for functions with different return types.

> A function, there are numeric, logical, instruction and other types
Can the above types of function patterns be modeled.

Wish VAVR will be better in 2021.

**Comment by danieldietrich** [comment]
I will close this, see [my PR comment](https://github.com/vavr-io/vavr/pull/2624#issuecomment-748629935)
