### ISSUE TITLE
[Suggestion] Type retaining collections

### ISSUE THREAD

**Issue by Monniasza** [vavr-io/vavr#2632]
I'd like to have type retaining versions of collections added.
These would be a good supplement for ordinary type erasure collections.
Some use cases include type checking and accepting unknown type lists

**Comment by danieldietrich** [comment]
I don't exactly know what you mean (Java erases types) but we can't simply add new collection because we roughly align to Scala collections.

**Comment by Monniasza** [comment]
> I don't exactly know what you mean (Java erases types) but we can't simply add new collection because we roughly align to Scala collections.

Collections that check incoming data for type and throw an exception if the check fails, and have a method to get their type.
The type is set using a constructor argument.

**Comment by danieldietrich** [comment]
Performing runtime checks and throwing is unsafe. Types should be checked at compile time if possible.

**Comment by Monniasza** [comment]
> Performing runtime checks and throwing is unsafe. Types should be checked at compile time if possible.

The possible use of type retention is serialization, which needs to know the actual type of elements to deserialize and serialize them properly.

**Comment by danieldietrich** [comment]
Serialization is an orthogonal concern. You are able to write serializers/deserializers (that are aware of the concrete types) outside of Vavr. Take a look at vavr-jackson and vavr-gson.
