### ISSUE TITLE
Add Seq.group()

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2634]
group is a function

```
group: Seq<T> -> Seq<Seq<T>>
```

that groups subsequent equal elements in a Seq.

Example:

```java
// List(CharSeq(aaaa), CharSeq(bbb), CharSeq(cc), CharSeq(a))
CharSeq.of("aaaabbbcca").group()
```

Example use case:

```java
// Seq(Tuple2(a, 4), Tuple2(b, 3), Tuple2(c, 2), Tuple2(a, 1))
CharSeq.of("aaaabbbcca").group().map(xs -> Tuple.of(xs.head(), xs.length()))
```

Currently, we need to write code like this:

```java
CharSeq.of("aaaabbbcca").foldRight(List.<Tuple2<Character, Integer>> empty(), (c, l) ->
  l.isEmpty() || l.head()._1 != c
    ? l.prepend(Tuple.of(c, 1))
    : l.tail().prepend(l.head().map2(i -> i + 1))
)
```

**Comment by farmboy0** [comment]
Isnt that the same as Seq.slideBy(Function.identidy())?

**Comment by danieldietrich** [comment]
Indeed 😏

```java
jshell> CharSeq.of("aaaabbbcca").slideBy(Function.identity())
$1 ==> Iterator(?)

jshell> CharSeq.of("aaaabbbcca").slideBy(Function.identity()).toList()
$2 ==> List(aaaa, bbb, cc, a)
```

Differences between `group()` and `slideBy(Function)`:

* `slideBy` is defined in `Traversable`
* `slideBy` returns an `Iterator`
* `group` is defined in `Seq`
* `group` returns a collection of the same type

I would

* keep  `group()` as an alias for `slideBy(Function.identity())`
* move `group()` to `Traversable`
* change the return type of `group()` to `Iterator`

I will create a new issue for that.

Thx @farmboy0
