### ISSUE TITLE
Proposal: Future.recover() doesn't take a CheckedFunction.

### ISSUE THREAD

**Issue by qux42** [vavr-io/vavr#2638]
Hello, 

I have quite often the use case that I have a Future, that i want to recover in case a certain Exception was thrown.
This is currently only with future.RecoverWith() possible. But this adds bulkiness, because you have to create and return a new Future.

So currently the code looks like that:
```java
final Future<String> recovered = failedFuture.recoverWith(throwable -> {
                if (throwable instanceof RuntimeException) {
                    return Future.successful("yeah");
                }
                return Future.failed(throwable);
            });
```

Is it possible that the recover method can be changed to accept a CheckedFunction instead?
Then it would be possible to write following code:
```java
final Future<String> recovered = failedFuture.recover(throwable -> {
                if (throwable instanceof RuntimeException) {
                    return "yeah";
                }
                throw throwable;
            });
```

If so I could assist with an PullRequest.

Thanks

**Comment by danieldietrich** [comment]
`Try` has similar methods, e.g. [recover(Class, Function)](https://javadoc.io/static/io.vavr/vavr/0.10.3/io/vavr/control/Try.html#recover-java.lang.Class-java.util.function.Function-).

The recover function would need to run async with the same executor. This would be a solution (applied to the Future interface):

```java
default <X extends Throwable> Future<T> recover(Class<X> exceptionType, Function<? super Throwable, ? extends T> f) {
    Objects.requireNonNull(exceptionType, "exceptionType is null");
    Objects.requireNonNull(f, "f is null");
    return transformValue(t -> t.recover(exceptionType, f));
}
```

A PR is appreciated!

**Comment by sleepytomcat** [comment]
Let me jump in with PR https://github.com/vavr-io/vavr/pull/2671
