### ISSUE TITLE
Consumer to consume value after Case matches pattern

### ISSUE THREAD

**Issue by novicedev7291** [vavr-io/vavr#2643]
### We have 4 types of signature in Case matching
* `Case($pattern, o -> run(someSideEffects())`
* `Case($pattern, retVal)`
* `Case($pattern, SomeFunction)`
* `Case($pattern, SomeSupplier)`

Now I am little curious, why don't we have?
```
Case($pattern, SomeConsumer)
```
I appreciate if someone can answer it, thanks for the wonderful library.

**Comment by danieldietrich** [comment]
As far as I remember, the API once existed but the additional overloads introduced ambiguities on the call site.

**Comment by novicedev7291** [comment]
What you suggest for such case?

**Comment by danieldietrich** [comment]
Match is meant to be an expression, not a statement. I would suggest not to perform side effects.

If you need to do so, maybe you could return null.

**Comment by novicedev7291** [comment]
ok, but this may not help in my case, I have a use case where I am matching using `instanceOf` pattern and I am receiving the different objects of same interface but I need to delegate the real objects to their respective function.

Case matching converts the object in real instance object after `instanceOf` matching the class type and this saves if-else and manual casting, anyways thanks for the suggestion.

**Comment by danieldietrich** [comment]
You are welcome!

There is light at the end of the tunnel: With Java 16 we will have real pattern matching for instanceof checks in if statements. I suggest to upgrade if you can.

https://openjdk.java.net/jeps/394
