### ISSUE TITLE
Try.getOrElseThrow() like Optional.getOrElseThrow()

### ISSUE THREAD

**Issue by xenoterracide** [vavr-io/vavr#2645]
would be nice to have a `getOrElseThrow()` on `Try` like `java.util.Optional#getOrElseThrow()` I think the behavior would be simple to rethrow the caught exception as a `RuntimeException`

**Comment by danieldietrich** [comment]
The `get()` method currently rethrows the exception in an unsafe way. We use the _sneaky throw_ hack for that purpose. However, the next version will not have the sneaky throw anymore, `get()` will then throw the original exception wrapped in a `RuntimeException` in the case of a failure. There is no need to add the additional method `getOrElseThrow()`.

Meanwhile, you could either use the unsafe `get()` or `getOrElseThrow(Function.identity())`.

**Comment by nfekete** [comment]
It's also confusing a little bit, because it misleads you about where the exceptions was thrown from, especially in combination with `Try.filter`. See @xenoterracide's [question on stackoverflow](https://stackoverflow.com/questions/66748240/vavr-try-filter-nosuchelementexception).

**Comment by danieldietrich** [comment]
I created #2663 and will close this.
