### ISSUE TITLE
Typo in Try.peek

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#2652]
We need to consider the strings `failureAction` and `successAction`. Currently we use just `action` for both cases:

```java
    public final Try<T> peek(Consumer<? super Throwable> failureAction, Consumer<? super T> successAction) {
        Objects.requireNonNull(failureAction, "action is null");
        Objects.requireNonNull(successAction, "action is null");
```

**Comment by sleepytomcat** [comment]
PR https://github.com/vavr-io/vavr/pull/2661

**Comment by sleepytomcat** [comment]
@danieldietrich, I think we may close this issue as PR https://github.com/vavr-io/vavr/pull/2661 has been merged.
