### ISSUE TITLE
Question/Issue with Either::toTry

### ISSUE THREAD

**Issue by dalegaspi** [vavr-io/vavr#2653]
Hello!

i'm currently using version 0.10.3 and i've come across an interesting issue, but this is probably due to not having a complete understanding of how `Try` or `Either` works so please bear with me:

this is the code snippet:
```java
class AuthenticationException extends Exception { ... }

Z result = authenticationService.authenticate(authRequest) // returns Either<AuthenticationException, X>
  .flatMap(ap -> authenticationService.resume(authRequest, ap.getCookies())) // returns Either<AuthenticationException, X>
  .toTry() // returns Try<X>
  .flatMap(ap -> createSessionEntity(authRequest, ap.getCookies())) // returns Try<Y>
  .flatMap(this::createAuthToken) // returns Try<Z>
  .get(); // returns Z or throw exception
```

so the issue is that i _assume_ that if `authenticationService.resume(authRequest, ap.getCookies()` returns a `Left` it is mapped to a `Failure` when converted to `Try` in `.toTry()` and the ending `.get()` would throw `AuthenticationException` but this is not what's happening; instead I'm getting `java.util.NoSuchElementException` thrown at the end:

```
java.util.NoSuchElementException: get() on Left
at io.vavr.control.Either$Left.get(Either.java:1106)
```

is this expected behavior?  I'm looking at the signature of `Either::toTry` and the only other overload has a `Supplier` parameter that returns a `Throwable` if the result is empty.

i mean, i got around this by doing something like this: 

```java
var result = authenticationService.authenticate(authRequest)
  .flatMap(ap -> authenticationService.resume(authRequest, ap.getCookies()));

if (result.isLeft()) {
  throw result.getLeft();
} 

var token = result
  .toTry()
  .flatMap(ap -> createSessionEntity(authRequest, ap.getCookies()))
  .flatMap(this::createAuthToken)
  .get();
```

it works, but it loses the compactness and elegance...and let's face it: it's not as cool. 😝

thanks!

**Edit**: it didn't occur to me until now that i can use `.toEither()` on `createSessionEntity` and `createAuthToken` so i can just use `Either`s all the way to the end.  but would be nice to know the answer burning question (burning in my little brain, that is).

**Comment by yossi-c** [comment]
I think you can achieve what you want by replacing the `toTry()` with `fold(Try::failure, Try::success)`

**Comment by dalegaspi** [comment]
thanks @yossi-c your suggestion worked...i wasn't familiar with `Either::fold`...

```java
var result = authenticationService.authenticate(authRequest)
                .flatMap(ap -> authenticationService.resume(authRequest, ap.getCookies()))
                .fold(Try::failure, Try::success) // returns Try<? extends Object>
                .flatMap(ap -> createSessionEntity(authRequest, ((AuthResponsePackage) ap).getCookies()))
                .flatMap(this::createAuthToken).get();
```
oddly enough, `Either::fold` returns a `Try<? extends Object>` even though the signature leads me to believe that it should return a `Try<AuthResponsePackage>` so i have to explicitly cast the parameter to the first `flatMap(...)` after the `fold(...)` but I wouldn't agonize about it too much...😝

**Comment by evantill** [comment]
What do you think of adding this ?
```java
//proposal to add this factory method to Try<T>class
public static <E extends Throwable, T> Try<T> of(Either<E, T> either) {
    return either.fold(Try::failure, Try::success);
}
```
