### ISSUE TITLE
Add Validation.combine(...) with Iterator and varargs as argument

### ISSUE THREAD

**Issue by mstachniuk** [vavr-io/vavr#2658]
Currently the only way for combine `Validation`  is using `combine(Validation<E, T1> validation1, Validation<E, T2> validation2)` with 1-8 arguments.
However if I have a List/Set of Validation then I can't easy combine it.

**Comment by danieldietrich** [comment]
I'm afraid, the `ap(f)` function can handle only arguments `f` of type `Function` up to arity 8.

Lists and Sets are homogenous (read: have one element type, say T). I would suggest to use multiple Validators if your have many things to validate.

That said: it isn't possible at the moment. Therefore I will close this issue.
