### ISSUE TITLE
There is a problem with the documents on your website.

### ISSUE THREAD

**Issue by stfujnkk** [vavr-io/vavr#2683]
There is a problem with the documents on your website. Tuple2 in the example should be changed to $tuple2
[Website links](https://docs.vavr.io/\#_ pattern_ matching) 
```java
Match(_try).of(
       Case($Success($($Tuple2($("a"), $()))), "tuple2 -> ..."),
        Case($Failure($(instanceOf(Error.class))), "error -> ...")
);
```

**Comment by danieldietrich** [comment]
Fixed & published. Thx!
