### ISSUE TITLE
Add `Validation.getOrElseThrow(Function<E, X>)`

### ISSUE THREAD

**Issue by sir4ur0n** [vavr-io/vavr#2693]
Hello, it's been a while :smile: 

I'm using a bit Vavr these days and to my surprise, there is no function to transform and throw the `Invalid` of a `Validation`.
Is that on purpose? Or is there already such a function but I can't find it?

I would expect such a function `Validation.getOrElseThrow(Function<E, X>)` to be able to convert the invalid content into an exception.

`Validation` Javadoc does not give any hint about how to proceed either.

**Comment by danieldietrich** [comment]
Hi Julien, just a few years 😅

Validation has been treated stepmotherly compated to Option, Either and Try. Let's change that and add (at least) this method.

Generally, we should keep Either and Validation in sync - here is [Either's function signature](https://github.com/vavr-io/vavr/blob/master/src/main/java/io/vavr/control/Either.java#L446-L471).
