### ISSUE TITLE
Non Empty List would be useful in certain cases

### ISSUE THREAD

**Issue by vinzlac** [vavr-io/vavr#2702]
Hi I give you my use where I think Non empty list could be useful
imagine a class Item with code, label and timestamp
I want to group items by code and for each code have the label with the last timestamp
I will group my list by code that will return a Map<String, List<Item>>  then do a max (Item::timestamp) of values that will give me an option cause `max` return always an option
But in my case, I'm sure that my list is non empty (because I grouped by code), so a max of a such list should not return an Option<Item> but an Item cause the Option will be always non empty
Without Non Empty List, this use case is more complexe to manage (must convert an Option<Item> to an Item cause my Option is never empty)

**Comment by danieldietrich** [comment]
Thanks, I will re-open the original issue #1244 (you also commented there).
