### ISSUE TITLE
Confusing documentation for Traversable.zipWithIndex(java.util.function.BiFunction<? super T,? super java.lang.Integer,? extends U> mapper)

### ISSUE THREAD

**Issue by dbear496** [vavr-io/vavr#2704]
The documentation for `Traversable.zipWithIndex(java.util.function.BiFunction<? super T,? super java.lang.Integer,? extends U> mapper)` is as follows:
> Returns a traversable formed from this traversable and another Iterable collection by mapping elements. If one of the two iterables is longer than the other, its remaining elements are ignored.
> 
> The length of the returned traversable is the minimum of the lengths of this traversable and that iterable.
> 
> Type Parameters:
>     U - The type of the mapped elements.
> Parameters:
>     mapper - a mapper.
> Returns:
>     a new traversable containing mapped elements of this traversable and that iterable.
> Throws:
>     java.lang.NullPointerException - if mapper is null 

This refers multiple times to _that iterable_, but there is no Iterable in the parameter list. It appears this documentation may have been copied from `Traversable.zipWith(java.lang.Iterable<? extends U> that, java.util.function.BiFunction<? super T,? super U,? extends R> mapper)`, but it was never changed to reflect that the other collection is the counting numbers.

**Comment by danieldietrich** [comment]
Good spot! Thank you

**Comment by sleepytomcat** [comment]
Addressed by https://github.com/vavr-io/vavr/pull/2706
