### ISSUE TITLE
Collect to map while dealing with collisions

### ISSUE THREAD

**Issue by patrickguenther** [vavr-io/vavr#2722]
I would like to collect a stream of objects into a map, while dealing with duplicate keys analogous to the Java collector `Collectors::toMap(Function, Function, BinaryOperator)`. Is there a canonical way of doing that?

**Comment by dbear496** [comment]
Will [`Traversable.toMap`](file:///home/david/code/diepio-bot/diepio-headless/libs/vavr/build/docs/javadoc/io/vavr/collection/Traversable.html#toMap-java.util.function.Function-java.util.function.Function-java.util.function.BiFunction-) do what you want?

**Comment by patrickguenther** [comment]
Of course, yes, I think that's what I was looking for.
