### ISSUE TITLE
The Option.map() method not judge the expression return value is null or not

### ISSUE THREAD

**Issue by bigduu** [vavr-io/vavr#2736]
The below code does not judge whether the expression return value is null or not, need to use Option.of() wrap it
[        return isEmpty() ? none() : some(mapper.apply(get()));](https://github.com/vavr-io/vavr/blob/2f2304daf83924ef8c7fc5f7779153af80da149c/src/main/java/io/vavr/control/Option.java#L654)
```java
Option.of("test")
.map(it->null)
.filter(it-> it.length > 5)  //<---- will throw null pointer exception
....
```

**Comment by danieldietrich** [comment]
Marked as duplicate

**Comment by bigduu** [comment]
> It works as expected. This question has been asked many times, there exist also several blog posts why Java's `Optional` is broken (regarding the Monad laws).
> 
> 
> 
> Vavr is aligned to Scala. Here is a Scala example that behaves the same:
> 
> 
> 
> <img width="523" alt="Some(null)" src="https://user-images.githubusercontent.com/743833/220350721-12c8500d-d872-4ec0-8e78-dda23c78fa87.png">
> 
> 

Thanks for your reply
