### ISSUE TITLE
Is 1.0.0 still a thing?

### ISSUE THREAD

**Issue by ezoerner** [vavr-io/vavr#2749]
Is there still a plan to release a 1.0.0 for vavr, or has this effort been abandoned?

**Comment by danieldietrich** [comment]
Hi @ezoerner and @cebaa! Thanks for using Vavr. The release isn't abandoned. Personally, I see it as unfinished work that was paused for private reasons but it will be done. I won't give you a concrete release date but at the moment I am highly motivated to finish it.

**Comment by cebaa** [comment]
@danieldietrich Thanks for a quick update! Personal reasons obviously take precedence, but it's great to hear that vavr 1.0 is still on the radar. It makes my life much easier and I wanted to upgrade sooner than later, but the alpha designation makes using it a bit harder to rationalize (although I understand it just means the API can break, not that it's unstable or anything).

**Comment by danieldietrich** [comment]
The alpha version was meant as a playground for API changes. The _real_ 1.0 version will be more in line with the current version. However, there will be breaking changes where it makes sense. The current version grew over years. Semantically, there are some duplicates. Also the Iterable/Traversable type hierarchy will be cleaned up and the 'control' types will be semantically decoupled from the collections. In turn, the convertibility between controls and collections might be improved.

**Comment by ezoerner** [comment]
Will deprecated stuff be removed as well? Including the `Value` interface?

**Comment by danieldietrich** [comment]
The chance is high.

**Comment by bowbahdoe** [comment]
* If breaking changes are introduced, can the group/artifact be changed so as to not break the [ecosystem of libraries](https://mvnrepository.com/artifact/io.vavr/vavr/usages?p=1) which depend on the current state of things (or at least an audit to know that yeah - no abandoned library uses `Value`, etc.)? This [is what jackson does](https://github.com/FasterXML/jackson/wiki/Jackson-Releases#general)
* If you still want to maintain java 8 compatibility, it might behoove us to figure out how to do a proper multi-release jar. A `module-info` compiled at java 9 might not have been enough reason, but sealing the `Option` hierarchy at the bytecode level that is allowed (java 17) will help 21 users now that pattern matching is in the language for real, and a very similar story will be true for when it is possible to provide deconstructors.

**Comment by ullenboom** [comment]
So, is 1.0.0 still a thing? Or any updates? The lack of releases since July 2021 implies this library is dead. An official statement would provide clarity.

**Comment by bowbahdoe** [comment]
> implies this library is dead. An official statement would provide clarity.

I think that we just need to chill and let @danieldietrich live his life and hope he doesn't get hit by a bus in the meantime. He'll come back eventually.

Even if he was spending his time on this actively still and making releases, enough FP adjacent java features are being added (like deconstructors and patterns) that it might make sense to wait before doing any significant future work anyways.

**Comment by pivovarit** [comment]
> Is there still a plan to release a 1.0.0 for vavr, or has this effort been abandoned?

It's definitely on :)
