### ISSUE TITLE
Avoid synchronized block or methods

### ISSUE THREAD

**Issue by reda-alaoui** [vavr-io/vavr#2760]
According to https://docs.oracle.com/en/java/javase/21/core/virtual-threads.html#GUID-04C03FFC-066D-4857-85B9-E5A27A875AF9:

> A current limitation of the implementation of virtual threads is that performing a blocking operation while inside a synchronized block or method causes the JDK's virtual thread scheduler to block a precious OS thread, whereas it wouldn't if the blocking operation were done outside of a synchronized block or method. We call that situation "pinning".

IMHO, all synchronizd blocks or methods should be replaced with ReentrantLock usage.

**Comment by He-Pin** [comment]
Not all, only io bound I think.

**Comment by pivovarit** [comment]
This is a temporary limitation of Virtual Threads and applies only to blocking operations inside `synchronized` blocks. I went through all cases of `synchronized`, and only deprecated-for-removal `Lazy` can run blocking code inside it, and that's the only change needed here I believe

**Comment by KrnSaurabh** [comment]
Hi @pivovarit,  I would be happy to contribute. Please let me know if I can pick this up if not assigned to someone already?

**Comment by pivovarit** [comment]
Sure, it’s yours :)

**Comment by KrnSaurabh** [comment]
@pivovarit I have created a PR for review - https://github.com/vavr-io/vavr/pull/2842

**Comment by pivovarit** [comment]
Looks done to me :)
