### ISSUE TITLE
Site docs.vavr.io fora do ar.

### ISSUE THREAD

**Issue by CassioGangrel** [vavr-io/vavr#2762]
Hello! The site of the documentation is offline: http://docs.vavr.io/

**Comment by kazimir-lyshchynski** [comment]
Last commit was dated at last year. Maybe the project can be represented as dead.

**Comment by outsideMyBox** [comment]
Just for info, until it is available again, the doc can be found here: https://github.com/vavr-io/vavr-docs/blob/gh-pages/index.html

**Comment by forresthopkinsa** [comment]
Duplicate of #2756
