### ISSUE TITLE
After upgrade to 0.10.5 Cannot use requires io.vavr in Eclipse

### ISSUE THREAD

**Issue by eitan-rosenberg** [vavr-io/vavr#2905]
I just upgrade my project to 0.10.5, and I cannot use requires io.vavr; in module-info.java.

It was working ok with 0.10.4 that use Automatic-Module-Name: io.vavr in /META-INF/MANIFEST.MF

I noticed lately that the solution of using multi version jar is causing problems sometimes.

I am using the latest eclipse with java 23

Thanks in advance.

**Comment by pivovarit** [comment]
Is this an IDE issue? can you build your project just fine directly from the command line?

**Comment by eitan-rosenberg** [comment]
> Is this an IDE issue? can you build your project just fine directly from the command line?
> 
> I verified that the setup works fine with Intellij IDEA

Thanks for responding.

I do not think so.

For example, I am using org.jsoup:jsoup that is also multi-Release Jar with no problem:

![2024-10-13_10-28-19](https://github.com/user-attachments/assets/ee1083a6-8562-405b-a389-442be84273b4)

**Comment by pivovarit** [comment]
Can you confirm that you're facing the same issue when building the project from command line using Maven/Gradle (or something else)?

**Comment by eitan-rosenberg** [comment]
**Using Maven "mvn clean compile" works just fine.**

I just realize that I had similar problem with com.google.code.gson:gson

Their pom is also using moditect-maven-plugin .

I suspect that moditect-maven-plugin is cooking something that eclipse cannot chew :-)

To solve my problem, I download the source code and roll my own version using java 11 Compliance and Automatic-Module-Name.

**Comment by pivovarit** [comment]
> Using Maven "mvn clean compile" works just fine.

Ooomph! I almost had a heart attack! 😅

I had a look at _jsoup_ and their module-info looks... just like vavr's. I will keep investigating

<img width="612" alt="image" src="https://github.com/user-attachments/assets/d52d0d9e-c810-4731-a60e-b5e1f506e9de">
<img width="513" alt="image" src="https://github.com/user-attachments/assets/8695a028-f09e-4b1f-816e-2e2c05a238ab">

**Comment by eitan-rosenberg** [comment]
Wish you luck !

**Comment by eitan-rosenberg** [comment]
Today I tried to use netbeans-23.
It is working, so this proves that the problem is with Eclipse.
I will report this to eclipse.org 
My only comment is that module-info.java class code is not visible. 
Thank you for your help and time (on a Sunday.....).

**Comment by pivovarit** [comment]
The problem is that the project is JDK8-based, and including `module-info.java` will only induce more tooling issues. Plain text is as good as it gets as long as project stays Java 8 compatible

**Comment by pivovarit** [comment]
You're welcome! To be fully candid, I have absolutely no clue what fixed the issue :)

<img width="640" height="578" alt="Image" src="https://github.com/user-attachments/assets/ac726574-0eb4-4ed7-a0a2-949d8123a1a7" />
