### ISSUE TITLE
The SSL certificate for docs.vavr.io is expired

### ISSUE THREAD

**Issue by yuokada** [vavr-io/vavr#2927]
https://docs.vavr.io/
https://www.ssllabs.com/ssltest/analyze.html?d=docs.vavr.io&s=2606%3a50c0%3a8001%3a0%3a0%3a0%3a0%3a153&latest

```
~ ❯❯❯ openssl s_client -connect docs.vavr.io:443 -showcerts | openssl x509 -text -noout
Connecting to 2606:50c0:8002::153
depth=2 C=US, O=Internet Security Research Group, CN=ISRG Root X1
verify return:1
depth=1 C=US, O=Let's Encrypt, CN=R11
verify return:1
depth=0 CN=docs.vavr.io
verify error:num=10:certificate has expired
notAfter=Nov  4 05:10:06 2024 GMT
verify return:1
depth=0 CN=docs.vavr.io
notAfter=Nov  4 05:10:06 2024 GMT
verify return:1
Certificate:

....
```

**Comment by pivovarit** [comment]
Thanks, this should self-resolve soon: 
<img width="827" alt="image" src="https://github.com/user-attachments/assets/e78e5f9b-b495-4f32-b1f7-645fb1e2160f">

**Comment by pivovarit** [comment]
There are some weird issues on GitHub's site. I need to play with the DNS setup a bit. Site will be inaccessible sometimes

**Comment by pivovarit** [comment]
Something is wrong. I reached out to GitHub support.

**Comment by pivovarit** [comment]
This is done. For some reason, the previous DNS setup was not ok for GitHub Pages. One small tweak there, and we are fine :)

![image](https://github.com/user-attachments/assets/7f72f3cf-bacf-4774-b106-b07ab18aad38)

**Comment by yuokada** [comment]
Thanks for fixing. 👍
