### ISSUE TITLE
vavr-docs restoration

### ISSUE THREAD

**Issue by pivovarit** [vavr-io/vavr#2928]
At the moment, new versions of docs can't be built because the project relies on historical versions of:
- Gradle
- AsciiDoctor Gradle Plugin

Would be grateful if someone could help with bringing this back to life. I will be quite busy in upcoming weeks

https://github.com/vavr-io/vavr-docs

**Comment by xenoterracide** [comment]
no promises, but groovy or is kotlin (new default) allowed for gradle's configuration?

**Comment by pivovarit** [comment]
I think both are fine - at the end, this is just a single project for docs building :)

**Comment by geovannymcode** [comment]
Hello,
I am working on translating the documentation into Spanish. Additionally, I have updated some dependencies to facilitate the project's build process.
The changes include:

- Updated the Gradle plugin for Asciidoctor to a newer version.
- Adjustments in the `build.gradle` and `gradle.properties` files to reflect these changes.

Attached are screenshots showing the modifications made.

Looking forward to any feedback or suggestions!

<img width="955" alt="Captura de pantalla 2024-11-17 a las 2 56 09 p  m" src="https://github.com/user-attachments/assets/5ee673e1-042c-4057-b906-0ca9fe52c094">
<img width="953" alt="Captura de pantalla 2024-11-17 a las 2 56 18 p  m" src="https://github.com/user-attachments/assets/354bf082-3612-4b4a-9ab4-1a72e8ca4115">

**Comment by pivovarit** [comment]
If that works, then great! Please prepare a PR only with the build fixes and I will gladly merge it

**Comment by geovannymcode** [comment]
@pivovarit I share with you the following PR, I documentation translated into Spanish  [PR-53](https://github.com/vavr-io/vavr-docs/pull/53)

**Comment by pivovarit** [comment]
Amazing :) looks good - let me try to figure out how to publish it. Haven't done it yet...

**Comment by pivovarit** [comment]
We managed to get the project to a state where it can be safely built and published. This is now run in GitHub Actions. The build/release process relies on some legacy plugins that would need to be reworked, but I will create dedicated tasks.

Docs are now refreshed for 0.10.5

I think this is completed :)
