### ISSUE TITLE
Compare current cross product impl with Kleisli variant

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#654]
Sebastian Millies described in his blog post [Cartesian Products with Kleisli Composition](http://sebastian-millies.blogspot.de/2015/09/cartesian-products-with-kleisli.html) a Kleisli-variant for computing the cross product.

I'm curious how this variant compares to the current implementation. We should measure it (time & memory).

**Comment by RobWin** [comment]
Interesting blog post.

**Comment by danieldietrich** [comment]
Currently out-of-scope. We need to ship a major release.
